<?php
if(PHP_SAPI!=='cli')exit(1);
require_once dirname(__DIR__).'/app/application.php';
require_once __DIR__.'/helpers/phase5b_fixture.php';
$failures=[];$assert=static function(bool $ok,string $message)use(&$failures):void{if(!$ok)$failures[]=$message;};$fixture=[];$other=[];$process=null;$logFiles=[];
$writeSession=static function(int $user,string $role,int $agency):array{session_write_close();session_name('rental_agency_session');session_id('p5b2'.bin2hex(random_bytes(12)));session_start();$_SESSION=['user_id'=>$user,'role'=>$role,'agency_ids'=>[$agency],'_authenticated_at'=>time(),'_created_at'=>time(),'_last_activity'=>time(),'_regenerated_at'=>time(),'_csrf_token'=>bin2hex(random_bytes(32))];$result=[session_id(),$_SESSION['_csrf_token']];session_write_close();return$result;};
try{
    $fixture=phase5bFixture('P5B2HTTP_'.strtoupper(bin2hex(random_bytes(4))));$other=phase5bFixture('P5B2HTTP_O'.strtoupper(bin2hex(random_bytes(4))));phase5bAs($fixture,ROLE_AGENCY_MANAGER);
    $reservation=phase5bCreateReservation($fixture,'HTTP');$contract=contractCreateFromReservation(['reservation_id'=>$reservation,'idempotency_key'=>phase5bToken()]);contractIssue(['contract_id'=>$contract,'idempotency_key'=>phase5bToken()]);$detail=contractScopedDetail($contract)['contract'];$version=(int)$detail['current_version_id'];$customer=trim($detail['first_name'].' '.$detail['last_name']);$manager=$fixture['run'].' '.ROLE_AGENCY_MANAGER;
    phase5bAs($other,ROLE_AGENCY_MANAGER);$foreignReservation=phase5bCreateReservation($other,'HTTP_FOREIGN');$foreignContract=contractCreateFromReservation(['reservation_id'=>$foreignReservation,'idempotency_key'=>phase5bToken()]);contractIssue(['contract_id'=>$foreignContract,'idempotency_key'=>phase5bToken()]);$foreignNumber=contractScopedDetail($foreignContract)['contract']['contract_number'];
    [$managerSession,$managerCsrf]=$writeSession($fixture['users'][ROLE_AGENCY_MANAGER],ROLE_AGENCY_MANAGER,$fixture['agency_id']);[$fleetSession,$fleetCsrf]=$writeSession($fixture['users'][ROLE_FLEET_AGENT],ROLE_FLEET_AGENT,$fixture['agency_id']);
    $socket=stream_socket_server('tcp://127.0.0.1:0',$errno,$errstr);if(!$socket)throw new RuntimeException($errstr);$name=(string)stream_socket_get_name($socket,false);fclose($socket);$port=(int)substr(strrchr($name,':'),1);$root=dirname(__DIR__);$logFiles=[tempnam($root.'/storage','p5b2-http-out-'),tempnam($root.'/storage','p5b2-http-err-')];$process=proc_open([PHP_BINARY,'-d','session.save_path='.$root.'/storage','-S','127.0.0.1:'.$port],[['pipe','r'],['file',$logFiles[0],'a'],['file',$logFiles[1],'a']],$pipes,$root);if(!is_resource($process))throw new RuntimeException('HTTP server did not start');fclose($pipes[0]);
    $request=static function(string $url,string $session,string $method='GET',array $post=[]):array{$headers='Cookie: rental_agency_session='.$session."\r\n";$options=['method'=>$method,'header'=>$headers,'timeout'=>3,'ignore_errors'=>true,'max_redirects'=>0];if($method==='POST'){$options['header'].="Content-Type: application/x-www-form-urlencoded\r\n";$options['content']=http_build_query($post);} $body=(string)file_get_contents($url,false,stream_context_create(['http'=>$options]));return['body'=>$body,'headers'=>$http_response_header??[],'status'=>implode(' ',$http_response_header??[])];};
    $url='http://127.0.0.1:'.$port.'/backoffice/contract_detail.php?id='.$contract;$page=[];for($i=0;$i<30;$i++){try{$page=$request($url,$managerSession);if(($page['body']??'')!=='')break;}catch(Throwable){}usleep(100000);}
    $assert(($page['body']??'')!==''&&str_contains($page['body'],'Customer')&&str_contains($page['body'],'Agency representative'),'Issued page does not render both acknowledgement states');$assert(!preg_match('/SQLSTATE|PDOException|Fatal error|Unhandled/i',$page['body']??''),'Issued page renders a raw technical error');
    $before=(int)dbFetchOne('SELECT COUNT(*) n FROM contract_acknowledgements WHERE contract_id=:id',['id'=>$contract])['n'];$get=$request($url.'&action=acknowledge',$managerSession);$assert((int)dbFetchOne('SELECT COUNT(*) n FROM contract_acknowledgements WHERE contract_id=:id',['id'=>$contract])['n']===$before,'GET changed acknowledgement state');$assert(!preg_match('/SQLSTATE|PDOException|Fatal error/i',$get['body']),'GET renders a raw technical error');
    $base=['action'=>'acknowledge','contract_id'=>$contract,'contract_version_id'=>$version,'acknowledgement_type'=>'customer','language_code'=>'en','party_name'=>$customer,'acknowledgement_method'=>'in_person','idempotency_key'=>phase5bToken()];$missing=$request($url,$managerSession,'POST',$base);$assert(str_contains($missing['status'],'419')||str_contains($missing['body'],'session has expired'),'Missing CSRF token was not rejected');$assert((int)dbFetchOne('SELECT COUNT(*) n FROM contract_acknowledgements WHERE contract_id=:id',['id'=>$contract])['n']===$before,'CSRF failure changed acknowledgement state');
    $customerPost=$base+['_csrf'=>$managerCsrf];$valid=$request($url,$managerSession,'POST',$customerPost);$assert(str_contains($valid['status'],'302')&&str_contains($valid['status'],'Location:'),'Authorized acknowledgement POST did not PRG');$assert((int)dbFetchOne('SELECT COUNT(*) n FROM contract_acknowledgements WHERE contract_id=:id',['id'=>$contract])['n']===1,'Authorized acknowledgement POST did not create exactly one row');$refresh=$request($url,$managerSession);$assert((int)dbFetchOne('SELECT COUNT(*) n FROM contract_acknowledgements WHERE contract_id=:id',['id'=>$contract])['n']===1,'Browser refresh duplicated acknowledgement');$assert(!preg_match('/SQLSTATE|PDOException|Fatal error/i',$refresh['body']),'Refresh renders a raw technical error');
    $fleet=$request($url,$fleetSession,'POST',$base+['_csrf'=>$fleetCsrf]);$assert(str_contains($fleet['status'],'403'),'Unauthorized role was not safely refused');$assert((int)dbFetchOne('SELECT COUNT(*) n FROM contract_acknowledgements WHERE contract_id=:id',['id'=>$contract])['n']===1,'Unauthorized role wrote acknowledgement data');
    $foreignUrl='http://127.0.0.1:'.$port.'/backoffice/contract_detail.php?id='.$foreignContract;$foreignGet=$request($foreignUrl,$managerSession);$assert((str_contains($foreignGet['status'],'404')||str_contains($foreignGet['status'],'403'))&&!str_contains($foreignGet['body'],$foreignNumber),'Cross-agency contract read revealed data');$foreignPost=$request($foreignUrl,$managerSession,'POST',$base+['contract_id'=>$foreignContract,'_csrf'=>$managerCsrf]);$assert(!preg_match('/SQLSTATE|PDOException|Fatal error/i',$foreignPost['body']),'Cross-agency write renders a raw technical error');$assert((int)dbFetchOne('SELECT COUNT(*) n FROM contract_acknowledgements WHERE contract_id=:id',['id'=>$foreignContract])['n']===0,'Cross-agency write created acknowledgement data');
    $agencyPost=['action'=>'acknowledge','contract_id'=>$contract,'contract_version_id'=>$version,'acknowledgement_type'=>'agency_representative','language_code'=>'en','party_name'=>$manager,'acknowledgement_method'=>'in_person','idempotency_key'=>phase5bToken(),'_csrf'=>$managerCsrf];$signedPost=$request($url,$managerSession,'POST',$agencyPost);$assert(str_contains($signedPost['status'],'302'),'Agency acknowledgement POST did not PRG');$signedPage=$request($url,$managerSession);$assert(!str_contains($signedPage['body'],'name="acknowledgement_type"')&&!str_contains($signedPage['body'],'name="contract_version_id"'),'Signed page still displays acknowledgement controls');$assert(!preg_match('/SQLSTATE|PDOException|Fatal error|Unhandled/i',$signedPage['body']),'Signed page renders a raw technical error');
}catch(Throwable $e){$failures[]='HTTP acknowledgement security test failed: '.$e->getMessage();}
finally{if(is_resource($process)){proc_terminate($process);proc_close($process);}foreach($logFiles as$file)if($file&&is_file($file))unlink($file);if($other)try{phase5bCleanup($other);}catch(Throwable $e){$failures[]='Foreign HTTP cleanup failed: '.$e->getMessage();}if($fixture)try{phase5bCleanup($fixture);}catch(Throwable $e){$failures[]='HTTP cleanup failed: '.$e->getMessage();}}
if($failures){foreach(array_unique($failures)as$f)fwrite(STDERR,"FAIL: $f\n");exit(1);}echo "Phase 5B.2 HTTP acknowledgement security tests passed: rendering, GET safety, CSRF, PRG, authorization, agency isolation, signed read-only state, and safe errors.\n";
