<?php
if(PHP_SAPI!=='cli')exit(1);
define('CONTRACT_ACKNOWLEDGEMENT_TEST_HOOK',true);
function contractAcknowledgementTestHook(string $stage,array $context): void
{
    $hook=$GLOBALS['contract_acknowledgement_test_hook']??null;
    if(is_callable($hook))$hook($stage,$context);
}
require_once dirname(__DIR__).'/app/application.php';
require_once __DIR__.'/helpers/phase5b_fixture.php';
$failures=[];$assert=static function(bool $ok,string $message)use(&$failures):void{if(!$ok)$failures[]=$message;};
$throws=static function(callable $fn,string $class)use(&$assert):?Throwable{try{$fn();$assert(false,'Expected '.$class);return null;}catch(Throwable $e){$assert($e instanceof $class,'Expected '.$class.', got '.get_class($e).': '.$e->getMessage());return$e;}};
$run='P5B2_'.strtoupper(bin2hex(random_bytes(4)));$fixture=[];$other=[];$root=dirname(__DIR__);
$issued=static function(array $fixture,string $suffix)use($run):array{phase5bAs($fixture,ROLE_AGENCY_MANAGER);$reservation=phase5bCreateReservation($fixture,$suffix);$contract=contractCreateFromReservation(['reservation_id'=>$reservation,'idempotency_key'=>phase5bToken()]);contractIssue(['contract_id'=>$contract,'idempotency_key'=>phase5bToken()]);$row=contractScopedDetail($contract)['contract'];return[$contract,(int)$row['current_version_id'],$row];};
$input=static function(int $contract,int $version,string $type,string $party,string $key):array{return['contract_id'=>$contract,'contract_version_id'=>$version,'acknowledgement_type'=>$type,'language_code'=>'en','party_name'=>$party,'acknowledgement_method'=>'in_person','idempotency_key'=>$key];};
try{
    $fixture=phase5bFixture($run);$other=phase5bFixture($run.'O');
    phase5bAs($fixture,ROLE_OWNER);foreach(['contract.view','contract.acknowledge_customer','contract.acknowledge_agency','contract.sign']as$p)$assert(can($p),'Owner missing '.$p);
    phase5bAs($fixture,ROLE_AGENCY_MANAGER);foreach(['contract.view','contract.acknowledge_customer','contract.acknowledge_agency','contract.sign']as$p)$assert(can($p),'Manager missing '.$p);
    phase5bAs($fixture,ROLE_RENTAL_AGENT);$assert(can('contract.acknowledge_customer')&&can('contract.acknowledge_agency')&&!can('contract.sign'),'Rental-agent acknowledgement permission matrix is wrong');
    phase5bAs($fixture,ROLE_FLEET_AGENT);$assert(!can('contract.acknowledge_customer')&&!can('contract.acknowledge_agency'),'Fleet agent can acknowledge');

    [$draft]=$issued($fixture,'DRAFT'); // make a separate draft without issue.
    $draftReservation=phase5bCreateReservation($fixture,'ACK_DRAFT');$draft=contractCreateFromReservation(['reservation_id'=>$draftReservation,'idempotency_key'=>phase5bToken()]);
    $draftRow=contractScopedDetail($draft)['contract'];$customer=trim($draftRow['first_name'].' '.$draftRow['last_name']);
    $throws(fn()=>contractRecordAcknowledgement($input($draft,(int)$draftRow['current_version_id'],'customer',$customer,phase5bToken())),DomainException::class);

    [$cancel,$cancelVersion,$cancelRow]=$issued($fixture,'CANCEL');contractCancel(['contract_id'=>$cancel,'reason'=>'P5B2 cancellation','idempotency_key'=>phase5bToken()]);
    $throws(fn()=>contractRecordAcknowledgement($input($cancel,$cancelVersion,'customer',trim($cancelRow['first_name'].' '.$cancelRow['last_name']),phase5bToken())),DomainException::class);

    [$contract,$version,$row]=$issued($fixture,'CUSTOMER_FIRST');$customer=trim($row['first_name'].' '.$row['last_name']);$managerName=$run.' '.ROLE_AGENCY_MANAGER;
    $immutableBefore=dbFetchOne('SELECT id,agency_id,contract_id,version_number,language_code,snapshot_json,snapshot_sha256,terms_text,predecessor_version_id,change_reason,created_by,created_at FROM contract_versions WHERE id=:id',['id'=>$version]);
    $versionCountBefore=(int)dbFetchOne('SELECT COUNT(*) n FROM contract_versions WHERE contract_id=:id',['id'=>$contract])['n'];
    $customerKey=phase5bToken();$customerInput=$input($contract,$version,'customer',$customer,$customerKey);
    $assert(contractRecordAcknowledgement($customerInput)===$contract,'Customer acknowledgement did not return contract');
    $assert(contractRecordAcknowledgement($customerInput)===$contract,'Customer acknowledgement replay failed');
    $state=dbFetchOne('SELECT status,signed_at FROM rental_contracts WHERE id=:id',['id'=>$contract]);$assert($state['status']==='issued'&&$state['signed_at']===null,'First acknowledgement changed status');
    $throws(fn()=>contractRecordAcknowledgement($input($contract,$version,'customer',$customer,phase5bToken())),DomainException::class);
    $conflict=$input($contract,$version,'agency_representative',$managerName,$customerKey);$throws(fn()=>contractRecordAcknowledgement($conflict),DomainException::class);
    $assert((int)dbFetchOne('SELECT COUNT(*) n FROM contract_acknowledgements WHERE contract_id=:id',['id'=>$contract])['n']===1,'Customer acknowledgement duplicated');
    $assert(contractRecordAcknowledgement($input($contract,$version,'agency_representative',$managerName,phase5bToken()))===$contract,'Agency acknowledgement failed');
    $state=dbFetchOne('SELECT status,signed_at FROM rental_contracts WHERE id=:id',['id'=>$contract]);$assert($state['status']==='signed'&&$state['signed_at']!==null,'Second acknowledgement did not sign');
    $precision=dbFetchOne("SELECT DATETIME_PRECISION p FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='rental_contracts' AND COLUMN_NAME='signed_at'");$assert((int)$precision['p']===6,'signed_at is not DATETIME(6)');
    $assert((int)dbFetchOne("SELECT COUNT(*) n FROM contract_status_history WHERE contract_id=:id AND from_status='issued' AND to_status='signed'",['id'=>$contract])['n']===1,'Signed history is not exactly once');
    $assert((int)dbFetchOne("SELECT COUNT(*) n FROM audit_logs WHERE agency_id=:agency AND entity_id=:id AND action='contract_signed'",['agency'=>$fixture['agency_id'],'id'=>$contract])['n']===1,'Signed audit is not exactly once');
    $assert(contractRecordAcknowledgement($customerInput)===$contract,'Completed acknowledgement replay failed after signing');
    $throws(fn()=>contractRecordAcknowledgement($input($contract,$version,'customer',$customer,phase5bToken())),DomainException::class);
    $immutableAfter=dbFetchOne('SELECT id,agency_id,contract_id,version_number,language_code,snapshot_json,snapshot_sha256,terms_text,predecessor_version_id,change_reason,created_by,created_at FROM contract_versions WHERE id=:id',['id'=>$version]);
    $assert($immutableAfter===$immutableBefore,'Acknowledgement changed immutable contract-version fields');
    $assert((int)dbFetchOne('SELECT COUNT(*) n FROM contract_versions WHERE contract_id=:id',['id'=>$contract])['n']===$versionCountBefore,'Acknowledgement created an additional contract version');

    [$agencyFirst,$agencyVersion,$agencyRow]=$issued($fixture,'AGENCY_FIRST');$agencyCustomer=trim($agencyRow['first_name'].' '.$agencyRow['last_name']);contractRecordAcknowledgement($input($agencyFirst,$agencyVersion,'agency_representative',$managerName,phase5bToken()));$assert(dbFetchOne('SELECT status FROM rental_contracts WHERE id=:id',['id'=>$agencyFirst])['status']==='issued','Agency-first acknowledgement did not remain issued');contractRecordAcknowledgement($input($agencyFirst,$agencyVersion,'customer',$agencyCustomer,phase5bToken()));$assert(dbFetchOne('SELECT status FROM rental_contracts WHERE id=:id',['id'=>$agencyFirst])['status']==='signed','Customer second did not sign');

    [$foreign,$foreignVersion,$foreignRow]=$issued($other,'FOREIGN');$throws(fn()=>contractRecordAcknowledgement($input($contract,$foreignVersion,'customer',$customer,phase5bToken())),InvalidArgumentException::class);
    [$versionCase,$versionCaseId,$versionCaseRow]=$issued($fixture,'VERSION');$wrongLanguage=$input($versionCase,$versionCaseId,'customer',trim($versionCaseRow['first_name'].' '.$versionCaseRow['last_name']),phase5bToken());$wrongLanguage['language_code']='fr';$throws(fn()=>contractRecordAcknowledgement($wrongLanguage),DomainException::class);$badMethod=$wrongLanguage;$badMethod['language_code']='en';$badMethod['acknowledgement_method']='remote';$throws(fn()=>contractRecordAcknowledgement($badMethod),InvalidArgumentException::class);$badParty=$wrongLanguage;$badParty['language_code']='en';$badParty['party_name']='';$throws(fn()=>contractRecordAcknowledgement($badParty),InvalidArgumentException::class);
    phase5bAs($fixture,ROLE_RENTAL_AGENT);$agentName=$run.' '.ROLE_RENTAL_AGENT;$impersonation=$input($versionCase,$versionCaseId,'agency_representative',$managerName,phase5bToken());$throws(fn()=>contractRecordAcknowledgement($impersonation),InvalidArgumentException::class);$assert(contractRecordAcknowledgement($input($versionCase,$versionCaseId,'agency_representative',$agentName,phase5bToken()))===$versionCase,'Rental agent acknowledgement was not permitted');
    phase5bAs($fixture,ROLE_AGENCY_MANAGER);

    [$rollback,$rollbackVersion,$rollbackRow]=$issued($fixture,'ROLLBACK');$rollbackCustomer=trim($rollbackRow['first_name'].' '.$rollbackRow['last_name']);$rollbackInput=$input($rollback,$rollbackVersion,'customer',$rollbackCustomer,phase5bToken());$GLOBALS['contract_acknowledgement_test_hook']=static function(string $stage):void{if($stage==='after_acknowledgement_audit')throw new RuntimeException('Forced acknowledgement rollback');};$throws(fn()=>contractRecordAcknowledgement($rollbackInput),RuntimeException::class);unset($GLOBALS['contract_acknowledgement_test_hook']);
    $rollbackState=dbFetchOne('SELECT status,signed_at FROM rental_contracts WHERE id=:id',['id'=>$rollback]);$assert($rollbackState['status']==='issued'&&$rollbackState['signed_at']===null,'Forced failure committed a signed contract state');$assert((int)dbFetchOne('SELECT COUNT(*) n FROM contract_acknowledgements WHERE contract_id=:id',['id'=>$rollback])['n']===0,'Forced failure retained acknowledgement row');$assert((int)dbFetchOne("SELECT COUNT(*) n FROM audit_logs WHERE agency_id=:agency AND entity_id=:id AND action='contract_customer_acknowledged'",['agency'=>$fixture['agency_id'],'id'=>$rollback])['n']===0,'Forced failure retained acknowledgement audit');$assert((int)dbFetchOne("SELECT COUNT(*) n FROM audit_logs WHERE agency_id=:agency AND entity_id=:id AND action='contract_signed'",['agency'=>$fixture['agency_id'],'id'=>$rollback])['n']===0,'Forced failure retained signed audit');$assert((int)dbFetchOne("SELECT COUNT(*) n FROM contract_status_history WHERE contract_id=:id AND to_status='signed'",['id'=>$rollback])['n']===0,'Forced failure retained signed history');$assert((int)dbFetchOne("SELECT COUNT(*) n FROM rental_operation_idempotency_keys WHERE origin_agency_id=:agency AND operation_type='contract_acknowledgement' AND status='in_progress'",['agency'=>$fixture['agency_id']])['n']===0,'Forced failure left idempotency residue');$assert(contractRecordAcknowledgement($rollbackInput)===$rollback,'Retry after forced rollback failed');

    [$same,$sameVersion,$sameRow]=$issued($fixture,'CONC_SAME');$sameCustomer=trim($sameRow['first_name'].' '.$sameRow['last_name']);$runtime=$root.'/storage';$base=['user_id'=>$fixture['users'][ROLE_AGENCY_MANAGER],'role'=>ROLE_AGENCY_MANAGER,'agency_id'=>$fixture['agency_id'],'operation'=>'acknowledge'];$pair=phase5bPair($runtime,$base+['args'=>$input($same,$sameVersion,'customer',$sameCustomer,phase5bToken())],$base+['args'=>$input($same,$sameVersion,'customer',$sameCustomer,phase5bToken())]);$okCount=(int)($pair['a']['ok']??false)+(int)($pair['b']['ok']??false);$assert($okCount===1,'Same-type concurrency did not have exactly one winner');$loser=($pair['a']['ok']??false)?$pair['b']:$pair['a'];$assert(($loser['class']??'')===DomainException::class,'Same-type concurrency loser was not a safe domain refusal');$sameState=dbFetchOne('SELECT status,signed_at FROM rental_contracts WHERE id=:id',['id'=>$same]);$assert($sameState['status']==='issued'&&$sameState['signed_at']===null,'Same-type concurrency changed contract state');$assert((int)dbFetchOne("SELECT COUNT(*) n FROM contract_acknowledgements WHERE contract_id=:id AND acknowledgement_type='customer'",['id'=>$same])['n']===1,'Same-type concurrency duplicated acknowledgement');$assert((int)dbFetchOne("SELECT COUNT(*) n FROM audit_logs WHERE agency_id=:agency AND entity_id=:id AND action='contract_customer_acknowledged'",['agency'=>$fixture['agency_id'],'id'=>$same])['n']===1,'Same-type concurrency duplicated acknowledgement audit');$assert((int)dbFetchOne("SELECT COUNT(*) n FROM contract_status_history WHERE contract_id=:id AND to_status='signed'",['id'=>$same])['n']===0,'Same-type concurrency created signed history');$assert((int)dbFetchOne("SELECT COUNT(*) n FROM audit_logs WHERE agency_id=:agency AND entity_id=:id AND action='contract_signed'",['agency'=>$fixture['agency_id'],'id'=>$same])['n']===0,'Same-type concurrency created signed audit');$assert((int)dbFetchOne("SELECT COUNT(*) n FROM rental_operation_idempotency_keys WHERE origin_agency_id=:agency AND operation_type='contract_acknowledgement' AND status='in_progress'",['agency'=>$fixture['agency_id']])['n']===0,'Same-type concurrency left idempotency residue');
    [$different,$differentVersion,$differentRow]=$issued($fixture,'CONC_DIFFERENT');$differentCustomer=trim($differentRow['first_name'].' '.$differentRow['last_name']);$differentCustomerInput=$input($different,$differentVersion,'customer',$differentCustomer,phase5bToken());$differentAgencyInput=$input($different,$differentVersion,'agency_representative',$managerName,phase5bToken());$pair=phase5bPair($runtime,$base+['args'=>$differentCustomerInput],$base+['args'=>$differentAgencyInput]);$assert(($pair['a']['ok']??false)&&($pair['b']['ok']??false),'Different-type concurrency did not complete');$differentState=dbFetchOne('SELECT status,signed_at FROM rental_contracts WHERE id=:id',['id'=>$different]);$assert($differentState['status']==='signed'&&$differentState['signed_at']!==null,'Different-type concurrency did not sign');$assert((int)dbFetchOne('SELECT COUNT(*) n FROM contract_acknowledgements WHERE contract_id=:id',['id'=>$different])['n']===2,'Different-type concurrency did not create exactly two acknowledgements');foreach(['customer'=>'contract_customer_acknowledged','agency_representative'=>'contract_agency_representative_acknowledged']as$type=>$event){$assert((int)dbFetchOne('SELECT COUNT(*) n FROM contract_acknowledgements WHERE contract_id=:id AND acknowledgement_type=:type',['id'=>$different,'type'=>$type])['n']===1,'Different-type concurrency missing '.$type.' acknowledgement');$assert((int)dbFetchOne('SELECT COUNT(*) n FROM audit_logs WHERE agency_id=:agency AND entity_id=:id AND action=:action',['agency'=>$fixture['agency_id'],'id'=>$different,'action'=>$event])['n']===1,'Different-type concurrency missing '.$type.' audit');}$assert((int)dbFetchOne("SELECT COUNT(*) n FROM contract_status_history WHERE contract_id=:id AND from_status='issued' AND to_status='signed'",['id'=>$different])['n']===1,'Different-type concurrency duplicated signed history');$assert((int)dbFetchOne("SELECT COUNT(*) n FROM audit_logs WHERE agency_id=:agency AND entity_id=:id AND action='contract_signed'",['agency'=>$fixture['agency_id'],'id'=>$different])['n']===1,'Different-type concurrency duplicated signed audit');$signedAt=$differentState['signed_at'];$assert(contractRecordAcknowledgement($differentCustomerInput)===$different,'Different-type replay failed');$assert(dbFetchOne('SELECT signed_at FROM rental_contracts WHERE id=:id',['id'=>$different])['signed_at']===$signedAt,'Idempotent replay rewrote signed_at');$assert((int)dbFetchOne("SELECT COUNT(*) n FROM rental_operation_idempotency_keys WHERE origin_agency_id=:agency AND operation_type='contract_acknowledgement' AND status='in_progress'",['agency'=>$fixture['agency_id']])['n']===0,'Different-type concurrency left idempotency residue');
    foreach(['en','fr','ar']as$lang){$translations=include $root.'/app/translations/'.$lang.'.php';foreach(['section.contract_acknowledgements','action.acknowledge_customer','validation.contract_ack_version']as$key)$assert(isset($translations[$key]),'Missing '.$lang.' acknowledgement translation '.$key);}
    $source=(string)file_get_contents($root.'/backoffice/contract_detail.php');$assert(str_contains($source,"requestMethod()==='POST'")&&str_contains($source,'requireCsrfPost()'),'Acknowledgement controller lacks POST/CSRF guard');
}catch(Throwable $e){$failures[]='Unexpected Phase 5B.2 failure: '.$e->getMessage();}
finally{try{if($other)phase5bCleanup($other);if($fixture)phase5bCleanup($fixture);}catch(Throwable $e){$failures[]='Cleanup failed: '.$e->getMessage();}}
if($failures){foreach(array_unique($failures)as$f)fwrite(STDERR,"FAIL: $f\n");exit(1);}echo "Phase 5B.2 acknowledgement tests passed: permissions, scope, version binding, signing, idempotency, audit/history, rollback, concurrency, security guards, translations, and cleanup.\n";
