<?php
require_once __DIR__ . '/../app/application.php';

function p4Worker(array $argv)
{
    $worker=$argv[2]??'';$runtime=$argv[3]??'';$user=(int)($argv[4]??0);$agency=(int)($argv[5]??0);$customer=(int)($argv[6]??0);$vehicle=(int)($argv[7]??0);
    if(!in_array($worker,['A','B'],true)||!is_dir($runtime)||!$user||!$agency||!$customer||!$vehicle)exit(3);
    $_SESSION['user_id']=$user;$_SESSION['role']=ROLE_AGENCY_MANAGER;$_SESSION['agency_ids']=[$agency];
    try{
        $pickup=new DateTimeImmutable('2035-03-10 10:00:00');$return=new DateTimeImmutable('2035-03-12 10:00:00');
        $initial=dbFetchOne('SELECT id FROM vehicles WHERE id=:vehicle AND agency_id=:agency AND archived_at IS NULL',['vehicle'=>$vehicle,'agency'=>$agency]);
        if(!$initial||vehicleHasConflict($vehicle,$pickup,$return))throw new RuntimeException('initial validation');
        file_put_contents($runtime.'/ready-'.$worker,'READY');$deadline=microtime(true)+15;while(!is_file($runtime.'/go')&&microtime(true)<$deadline)usleep(20000);if(!is_file($runtime.'/go'))throw new RuntimeException('barrier timeout');
        createReservation(['agency_id'=>$agency,'return_agency_id'=>$agency,'customer_id'=>$customer,'vehicle_id'=>$vehicle,'status'=>'pending','source'=>'agency','pickup_at'=>'2035-03-10T10:00','return_at'=>'2035-03-12T10:00','options_total'=>'0.00','fees_total'=>'0.00','discount_percent'=>'0.00','tax_rate'=>'20.00','deposit_amount'=>'0.00']);
        file_put_contents($runtime.'/result-'.$worker,'COMMITTED');exit(0);
    }catch(DomainException$e){file_put_contents($runtime.'/result-'.$worker,'CONFLICT');exit(0);}catch(Throwable$e){file_put_contents($runtime.'/result-'.$worker,'FAILED_GENERIC');exit(2);}
}
if(($argv[1]??'')==='--concurrency-worker')p4Worker($argv);

function p4ReplacementWorker(array $argv)
{
    $worker=$argv[2]??'';$runtime=$argv[3]??'';$user=(int)($argv[4]??0);$agency=(int)($argv[5]??0);$reservationId=(int)($argv[6]??0);$vehicleId=(int)($argv[7]??0);$expected=(string)($argv[8]??'');
    if(!in_array($worker,['A','B'],true)||!is_dir($runtime)||!$user||!$agency||!$reservationId||!$vehicleId||$expected==='')exit(3);
    $_SESSION['user_id']=$user;$_SESSION['role']=ROLE_AGENCY_MANAGER;$_SESSION['agency_ids']=[$agency];
    try{
        $reservation=scopedReservationRecord($reservationId);if(!$reservation)throw new RuntimeException('initial validation');
        file_put_contents($runtime.'/replace-ready-'.$worker,'READY');$deadline=microtime(true)+15;while(!is_file($runtime.'/replace-go')&&microtime(true)<$deadline)usleep(20000);if(!is_file($runtime.'/replace-go'))throw new RuntimeException('barrier timeout');
        updateReservationAllocation($reservationId,['mode'=>'replace','vehicle_id'=>$vehicleId,'updated_at'=>$expected]);
        file_put_contents($runtime.'/replace-result-'.$worker,'COMMITTED');exit(0);
    }catch(DomainException$e){file_put_contents($runtime.'/replace-result-'.$worker,'CONFLICT');exit(0);}catch(Throwable$e){file_put_contents($runtime.'/replace-result-'.$worker,'FAILED_GENERIC');exit(2);}
}
if(($argv[1]??'')==='--replacement-worker')p4ReplacementWorker($argv);

$failures=[];$stage='bootstrap';$assert=function($condition,$message)use(&$failures){if(!$condition)$failures[]=$message;};$run='P4_TEST_'.strtoupper(bin2hex(random_bytes(5)));$runtime=dirname(__DIR__).'/storage/phase4_test_runtime_'.$run;$agencyId=0;$otherAgencyId=0;$userIds=[];$categoryId=0;$vehicleIds=[];$otherVehicleId=0;$customerIds=[];$filePaths=[];$cleanupFailures=[];
$setActor=function($id,$role,$agencies){$_SESSION['user_id']=$id;$_SESSION['role']=$role;$_SESSION['agency_ids']=$agencies;};
$cleanup=function()use(&$agencyId,&$otherAgencyId,&$userIds,&$filePaths,&$runtime,$run,&$cleanupFailures){
    try{if(db()->inTransaction())db()->rollBack();$agencies=array_values(array_filter([$agencyId,$otherAgencyId]));if($agencies){$ph=implode(',',array_fill(0,count($agencies),'?'));$reservationIds=array_map('intval',array_column(dbFetchAll("SELECT id FROM reservations WHERE agency_id IN ($ph)",$agencies),'id'));if($reservationIds){$rp=implode(',',array_fill(0,count($reservationIds),'?'));foreach(['reservation_options','reservation_status_history']as$table)dbExecute("DELETE FROM $table WHERE reservation_id IN ($rp)",$reservationIds);dbExecute("DELETE FROM customer_requests WHERE reservation_id IN ($rp)",$reservationIds);dbExecute("DELETE FROM notifications WHERE reservation_id IN ($rp)",$reservationIds);dbExecute("DELETE FROM deposits WHERE reservation_id IN ($rp)",$reservationIds);dbExecute("DELETE FROM payments WHERE reservation_id IN ($rp)",$reservationIds);dbExecute("DELETE FROM invoices WHERE reservation_id IN ($rp)",$reservationIds);dbExecute("DELETE FROM reservations WHERE id IN ($rp)",$reservationIds);}dbExecute("DELETE FROM audit_logs WHERE agency_id IN ($ph)",$agencies);$customerIds=array_map('intval',array_column(dbFetchAll("SELECT id FROM customers WHERE agency_id IN ($ph)",$agencies),'id'));if($customerIds){$cp=implode(',',array_fill(0,count($customerIds),'?'));dbExecute("DELETE FROM customer_documents WHERE customer_id IN ($cp)",$customerIds);dbExecute("DELETE FROM additional_drivers WHERE customer_id IN ($cp)",$customerIds);dbExecute("DELETE FROM customer_status_history WHERE customer_id IN ($cp)",$customerIds);dbExecute("DELETE FROM customers WHERE id IN ($cp)",$customerIds);}$vehicleIds=array_map('intval',array_column(dbFetchAll("SELECT id FROM vehicles WHERE agency_id IN ($ph)",$agencies),'id'));if($vehicleIds){$vp=implode(',',array_fill(0,count($vehicleIds),'?'));dbExecute("DELETE FROM vehicle_media WHERE vehicle_id IN ($vp)",$vehicleIds);dbExecute("DELETE FROM vehicle_status_history WHERE vehicle_id IN ($vp)",$vehicleIds);dbExecute("DELETE FROM vehicle_documents WHERE vehicle_id IN ($vp)",$vehicleIds);dbExecute("DELETE FROM maintenance_records WHERE vehicle_id IN ($vp)",$vehicleIds);dbExecute("DELETE FROM vehicles WHERE id IN ($vp)",$vehicleIds);}dbExecute("DELETE FROM vehicle_categories WHERE agency_id IN ($ph)",$agencies);}
        if($userIds){$up=implode(',',array_fill(0,count($userIds),'?'));dbExecute("DELETE FROM user_agencies WHERE user_id IN ($up)",$userIds);dbExecute("DELETE FROM users WHERE id IN ($up)",$userIds);}if($agencies){$ph=implode(',',array_fill(0,count($agencies),'?'));dbExecute("DELETE FROM agencies WHERE id IN ($ph)",$agencies);}
    }catch(Throwable$e){$cleanupFailures[]='database cleanup';}
    foreach($filePaths as$path){if(is_file($path)&&!@unlink($path))$cleanupFailures[]='file cleanup';}if(is_dir($runtime)){foreach(glob($runtime.'/*')?:[]as$f)if(is_file($f))@unlink($f);@rmdir($runtime);}unset($_SESSION['user_id'],$_SESSION['role'],$_SESSION['agency_ids']);
};
register_shutdown_function($cleanup);

try{
    $stage='schema';
    foreach(['tax_rate']as$column)$assert((bool)dbFetchOne('SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=\'reservations\' AND COLUMN_NAME=:column',['column'=>$column]),"Missing reservations.$column");
    $assert(tableExists('customer_status_history'),'customer_status_history missing');
    $baselineIndex=dbFetchOne("SELECT GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) columns_list,MIN(NON_UNIQUE) non_unique FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='customer_status_history' AND INDEX_NAME='uq_customer_status_history_baseline'");$assert(($baselineIndex['columns_list']??'')==='baseline_customer_id'&&(int)($baselineIndex['non_unique']??1)===0,'Baseline unique index invalid');
    $historyColumns=dbFetchAll("SELECT COLUMN_NAME,COLUMN_TYPE,IS_NULLABLE,GENERATION_EXPRESSION FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='customer_status_history' ORDER BY ORDINAL_POSITION");$assert(count($historyColumns)===10,'History column count invalid');$historyMap=[];foreach($historyColumns as$column)$historyMap[$column['COLUMN_NAME']]=$column;$assert(($historyMap['changed_at']['COLUMN_TYPE']??'')==='datetime(6)'&&($historyMap['changed_at']['IS_NULLABLE']??'')==='NO','History timestamp definition invalid');$assert(stripos((string)($historyMap['baseline_customer_id']['GENERATION_EXPRESSION']??''),'migration_baseline')!==false,'Baseline generated expression invalid');
    $foreignKeys=dbFetchAll("SELECT tc.CONSTRAINT_NAME,tc.CONSTRAINT_TYPE,GROUP_CONCAT(k.COLUMN_NAME ORDER BY k.ORDINAL_POSITION) local_columns,MAX(k.REFERENCED_TABLE_SCHEMA) parent_schema,MAX(k.REFERENCED_TABLE_NAME) parent_table,GROUP_CONCAT(k.REFERENCED_COLUMN_NAME ORDER BY k.ORDINAL_POSITION) parent_columns,MAX(rc.UPDATE_RULE) update_rule,MAX(rc.DELETE_RULE) delete_rule FROM information_schema.TABLE_CONSTRAINTS tc JOIN information_schema.KEY_COLUMN_USAGE k ON k.CONSTRAINT_SCHEMA=tc.CONSTRAINT_SCHEMA AND k.TABLE_NAME=tc.TABLE_NAME AND k.CONSTRAINT_NAME=tc.CONSTRAINT_NAME JOIN information_schema.REFERENTIAL_CONSTRAINTS rc ON rc.CONSTRAINT_SCHEMA=tc.CONSTRAINT_SCHEMA AND rc.TABLE_NAME=tc.TABLE_NAME AND rc.CONSTRAINT_NAME=tc.CONSTRAINT_NAME WHERE tc.CONSTRAINT_SCHEMA=DATABASE() AND tc.TABLE_NAME='customer_status_history' GROUP BY tc.CONSTRAINT_NAME,tc.CONSTRAINT_TYPE");$foreignKeyMap=[];foreach($foreignKeys as$foreignKey){if($foreignKey['update_rule']==='NO ACTION')$foreignKey['update_rule']='RESTRICT';if($foreignKey['delete_rule']==='NO ACTION')$foreignKey['delete_rule']='RESTRICT';$foreignKeyMap[$foreignKey['CONSTRAINT_NAME']]=$foreignKey;}$expectedForeignKeys=['fk_customer_status_history_customer_agency'=>['customer_id,agency_id','customers','id,agency_id'],'fk_customer_status_history_agency'=>['agency_id','agencies','id'],'fk_customer_status_history_user'=>['changed_by','users','id']];$assert(count($foreignKeyMap)===3,'History foreign-key count invalid');foreach($expectedForeignKeys as$name=>$expected){$foreignKey=$foreignKeyMap[$name]??[];$assert(($foreignKey['CONSTRAINT_TYPE']??'')==='FOREIGN KEY'&&($foreignKey['local_columns']??'')===$expected[0]&&($foreignKey['parent_schema']??'')===getenv('DB_NAME')&&($foreignKey['parent_table']??'')===$expected[1]&&($foreignKey['parent_columns']??'')===$expected[2]&&($foreignKey['update_rule']??'')==='RESTRICT'&&($foreignKey['delete_rule']??'')==='RESTRICT','History exact foreign-key definition invalid: '.$name);}
    $checkRows=dbFetchAll("SELECT tc.CONSTRAINT_NAME,tc.CONSTRAINT_TYPE,cc.CHECK_CLAUSE FROM information_schema.TABLE_CONSTRAINTS tc JOIN information_schema.CHECK_CONSTRAINTS cc ON cc.CONSTRAINT_SCHEMA=tc.CONSTRAINT_SCHEMA AND cc.TABLE_NAME=tc.TABLE_NAME AND cc.CONSTRAINT_NAME=tc.CONSTRAINT_NAME WHERE tc.CONSTRAINT_SCHEMA=DATABASE() AND tc.TABLE_NAME='customer_status_history'");$checkMap=[];foreach($checkRows as$check)$checkMap[$check['CONSTRAINT_NAME']]=[$check['CONSTRAINT_TYPE'],preg_replace('/[`\\s]+/','',(string)$check['CHECK_CLAUSE'])];$expectedChecks=['chk_customer_history_previous_status'=>"previous_statusisnullorprevious_statusin('new','regular','VIP','watchlist','blocked','archived')",'chk_customer_history_new_status'=>"new_statusin('new','regular','VIP','watchlist','blocked','archived')",'chk_customer_history_action'=>"action_typein('migration_baseline','created','status_changed','blocked','unblocked','archived')",'chk_customer_history_reason'=>"action_typenotin('blocked','unblocked','archived')orchar_length(trim(coalesce(reason,'')))between1and255"];$assert(count($checkMap)===4,'History check-constraint count invalid');foreach($expectedChecks as$name=>$expected)$assert(($checkMap[$name][0]??'')==='CHECK'&&($checkMap[$name][1]??'')===$expected,'History exact check definition invalid: '.$name);
    $duplicateBaselines=(int)dbFetchOne("SELECT COUNT(*) n FROM (SELECT customer_id FROM customer_status_history WHERE action_type='migration_baseline' GROUP BY customer_id HAVING COUNT(*)>1) duplicates")['n'];$assert($duplicateBaselines===0,'Duplicate customer migration baselines found');
    $untrackedCustomers=(int)dbFetchOne("SELECT COUNT(*) n FROM customers c LEFT JOIN customer_status_history h ON h.customer_id=c.id AND h.action_type IN ('migration_baseline','created') WHERE h.id IS NULL")['n'];$assert($untrackedCustomers===0,'Customer without migration baseline or server-created history found');
    $stage='agencies';dbExecute("INSERT INTO agencies(name,code,status) VALUES(:name,:code,'active')",['name'=>$run.' Agency','code'=>substr($run,0,25)]);$agencyId=(int)db()->lastInsertId();dbExecute("INSERT INTO agencies(name,code,status) VALUES(:name,:code,'active')",['name'=>$run.' Other','code'=>substr($run.'_O',0,30)]);$otherAgencyId=(int)db()->lastInsertId();
    $stage='users';foreach([[ROLE_OWNER,'owner'],[ROLE_AGENCY_MANAGER,'manager'],[ROLE_RENTAL_AGENT,'agent']]as[$role,$label]){$email=strtolower($run.'_'.$label.'@example.test');dbExecute("INSERT INTO users(fullname,email,email_normalized,password_hash,role,status) VALUES(:name,:email,:normalized,:hash,:role,'active')",['name'=>$run.' '.$label,'email'=>$email,'normalized'=>$email,'hash'=>password_hash(bin2hex(random_bytes(18)),PASSWORD_DEFAULT),'role'=>$role]);$uid=(int)db()->lastInsertId();$userIds[]=$uid;dbExecute('INSERT INTO user_agencies(user_id,agency_id,is_primary) VALUES(:user,:agency,1)',['user'=>$uid,'agency'=>$agencyId]);}
    [$ownerId,$managerId,$agentId]=$userIds;$setActor($managerId,ROLE_AGENCY_MANAGER,[$agencyId]);
    $stage='vehicles';dbExecute("INSERT INTO vehicle_categories(agency_id,name,code,base_daily_price,recommended_deposit,status) VALUES(:agency,:name,:code,200,500,'active')",['agency'=>$agencyId,'name'=>$run.' Category','code'=>substr($run,0,25)]);$categoryId=(int)db()->lastInsertId();
    foreach(['A','B','C','D','E']as$suffix){dbExecute("INSERT INTO vehicles(agency_id,category_id,registration_number,vin,brand,model,base_daily_price,recommended_deposit,status,created_by,updated_by) VALUES(:agency,:category,:registration,:vin,'Test','Vehicle',200,500,'available',:creator,:updater)",['agency'=>$agencyId,'category'=>$categoryId,'registration'=>substr($run.'-'.$suffix,0,40),'vin'=>substr($run.'VIN'.$suffix,0,80),'creator'=>$managerId,'updater'=>$managerId]);$vehicleIds[]=(int)db()->lastInsertId();}
    dbExecute("INSERT INTO vehicle_categories(agency_id,name,code,base_daily_price,recommended_deposit,status) VALUES(:agency,:name,:code,200,500,'active')",['agency'=>$otherAgencyId,'name'=>$run.' Other Category','code'=>substr($run.'OC',0,25)]);$otherCategoryId=(int)db()->lastInsertId();dbExecute("INSERT INTO vehicles(agency_id,category_id,registration_number,vin,brand,model,base_daily_price,recommended_deposit,status,created_by,updated_by) VALUES(:agency,:category,:registration,:vin,'Other','Vehicle',200,500,'available',:creator,:updater)",['agency'=>$otherAgencyId,'category'=>$otherCategoryId,'registration'=>substr($run.'-OTHER',0,40),'vin'=>substr($run.'VINOTHER',0,80),'creator'=>$managerId,'updater'=>$managerId]);$otherVehicleId=(int)db()->lastInsertId();
    $profile=['customer_type'=>'individual','first_name'=>$run,'last_name'=>'Customer','identity_number'=>$run.'ID','nationality'=>'MA','date_of_birth'=>'1990-01-01','address'=>'Test','phone'=>'+212600000001','whatsapp'=>'','email'=>strtolower($run.'@example.test'),'licence_number'=>$run.'LIC','licence_issue_date'=>'2020-01-01','licence_expires_at'=>'2036-01-01','licence_country'=>'MA','company_name'=>'','ice'=>'','tax_identifier'=>'','company_registration_number'=>'','billing_address'=>'','notes'=>''];$customerId=createCustomerProfile($agencyId,$profile);$customerIds[]=$customerId;
    $baselineCount=(int)dbFetchOne("SELECT COUNT(*) n FROM customer_status_history WHERE customer_id=:id AND action_type='migration_baseline'",['id'=>$customerId])['n'];$createdCount=(int)dbFetchOne("SELECT COUNT(*) n FROM customer_status_history WHERE customer_id=:id AND action_type='created'",['id'=>$customerId])['n'];$assert($baselineCount===0&&$createdCount===1,'New customer history is not server-derived');
    $setActor($agentId,ROLE_RENTAL_AGENT,[$agencyId]);$fresh=scopedCustomerRecord($customerId);try{changeCustomerLifecycle($customerId,'block','test reason',$fresh['updated_at']);$assert(false,'Rental agent blocked customer');}catch(AuthorizationException$e){$assert(true,'Rental lifecycle denial');}
    $setActor($managerId,ROLE_AGENCY_MANAGER,[$agencyId]);$fresh=scopedCustomerRecord($customerId);changeCustomerLifecycle($customerId,'block','Risk review',$fresh['updated_at']);$blocked=scopedCustomerRecord($customerId);$assert($blocked['status']==='blocked','Manager block failed');changeCustomerLifecycle($customerId,'unblock','Review cleared',$blocked['updated_at']);$assert(scopedCustomerRecord($customerId)['status']==='new','Server-derived unblock target failed');
    try{authorizedReturnAgency($agencyId,$otherAgencyId);$assert(false,'Unauthorized cross-agency return accepted');}catch(AuthorizationException$e){$assert(true,'Cross-agency return denied');}
    $reservationId=createReservation(['agency_id'=>$agencyId,'return_agency_id'=>$agencyId,'customer_id'=>$customerId,'vehicle_id'=>$vehicleIds[0],'status'=>'pending','source'=>'agency','pickup_at'=>'2034-01-01T10:00','return_at'=>'2034-01-03T10:00','options_total'=>'10.00','fees_total'=>'5.00','discount_percent'=>'10.00','tax_rate'=>'20.00','deposit_amount'=>'500.00']);
    $reservation=scopedReservationRecord($reservationId);$oldDaily=$reservation['daily_price'];$oldDiscount=$reservation['discount_percent'];updateReservationAllocation($reservationId,['mode'=>'extend','vehicle_id'=>$vehicleIds[0],'pickup_at'=>'2034-01-01T10:00','return_at'=>'2034-01-05T10:00','updated_at'=>$reservation['updated_at']]);$extended=scopedReservationRecord($reservationId);$assert($extended['daily_price']===$oldDaily&&$extended['discount_percent']===$oldDiscount&&$extended['tax_rate']==='20.00'&&(int)$extended['rental_days']===4,'Extension did not preserve commercial terms');
    dbExecute('UPDATE reservations SET tax_rate=NULL WHERE id=:id',['id'=>$reservationId]);$legacy=scopedReservationRecord($reservationId);$setActor($agentId,ROLE_RENTAL_AGENT,[$agencyId]);try{resolveLegacyReservationTaxRate($reservationId,'20.00','test',$legacy['updated_at']);$assert(false,'Rental agent resolved legacy tax');}catch(AuthorizationException$e){$assert(true,'Legacy tax denial');}
    $setActor($managerId,ROLE_AGENCY_MANAGER,[$agencyId]);$legacy=scopedReservationRecord($reservationId);$oldTotal=$legacy['total_amount'];resolveLegacyReservationTaxRate($reservationId,'20.00','Verified original tax terms',$legacy['updated_at']);$resolved=scopedReservationRecord($reservationId);$assert($resolved['tax_rate']==='20.00'&&$resolved['total_amount']===$oldTotal,'Legacy tax remediation changed historical totals');
    $stage='operational transitions';$newPending=function($vehicle,$pickup,$return)use($agencyId,$customerId){return createReservation(['agency_id'=>$agencyId,'return_agency_id'=>$agencyId,'customer_id'=>$customerId,'vehicle_id'=>$vehicle,'status'=>'pending','source'=>'agency','pickup_at'=>$pickup,'return_at'=>$return,'options_total'=>'0.00','fees_total'=>'0.00','discount_percent'=>'0.00','tax_rate'=>'20.00','deposit_amount'=>'0.00']);};
    try{lockReservationVehicleRows(999999999,999999999,$agencyId);$assert(false,'Missing transition vehicle accepted');}catch(DomainException$e){$assert(true,'Missing transition vehicle rejected');}
    foreach(['maintenance','damaged','blocked','sold','retired']as$offset=>$invalidStatus){$year=2040+$offset;$pendingId=$newPending($vehicleIds[1],$year.'-01-10T10:00',$year.'-01-12T10:00');dbExecute('UPDATE vehicles SET status=:status WHERE id=:id',['status'=>$invalidStatus,'id'=>$vehicleIds[1]]);try{transitionReservation($pendingId,'confirmed');$assert(false,'Invalid vehicle status accepted for confirmation: '.$invalidStatus);}catch(DomainException$e){$assert(true,'Invalid vehicle status rejected');}$state=scopedReservationRecord($pendingId);$vehicleState=dbFetchOne('SELECT status FROM vehicles WHERE id=:id',['id'=>$vehicleIds[1]]);$assert($state['status']==='pending'&&$vehicleState['status']===$invalidStatus,'Failed confirmation did not roll back cleanly');dbExecute("UPDATE vehicles SET status='available' WHERE id=:id",['id'=>$vehicleIds[1]]);}
    $archivedTransitionId=$newPending($vehicleIds[1],'2046-01-10T10:00','2046-01-12T10:00');dbExecute('UPDATE vehicles SET archived_at=NOW() WHERE id=:id',['id'=>$vehicleIds[1]]);try{transitionReservation($archivedTransitionId,'confirmed');$assert(false,'Archived vehicle accepted for confirmation');}catch(DomainException$e){$assert(true,'Archived transition vehicle rejected');}$assert(scopedReservationRecord($archivedTransitionId)['status']==='pending','Archived transition changed reservation state');dbExecute('UPDATE vehicles SET archived_at=NULL WHERE id=:id',['id'=>$vehicleIds[1]]);
    $crossTransitionId=$newPending($vehicleIds[1],'2047-01-10T10:00','2047-01-12T10:00');dbExecute('UPDATE reservations SET vehicle_id=:vehicle WHERE id=:id',['vehicle'=>$otherVehicleId,'id'=>$crossTransitionId]);try{transitionReservation($crossTransitionId,'confirmed');$assert(false,'Cross-agency vehicle accepted for confirmation');}catch(DomainException$e){$assert(true,'Cross-agency transition vehicle rejected');}$assert(scopedReservationRecord($crossTransitionId)['status']==='pending'&&dbFetchOne('SELECT status FROM vehicles WHERE id=:id',['id'=>$otherVehicleId])['status']==='available','Cross-agency transition changed state');dbExecute('UPDATE reservations SET vehicle_id=:vehicle WHERE id=:id',['vehicle'=>$vehicleIds[1],'id'=>$crossTransitionId]);
    $conflictTransitionId=$newPending($vehicleIds[1],'2048-01-10T10:00','2048-01-12T10:00');dbExecute("INSERT INTO maintenance_records(vehicle_id,maintenance_type,entry_at,estimated_exit_at,status,created_by,updated_by) VALUES(:vehicle,'test','2048-01-10 09:00:00','2048-01-12 11:00:00','scheduled',:user,:user2)",['vehicle'=>$vehicleIds[1],'user'=>$managerId,'user2'=>$managerId]);try{transitionReservation($conflictTransitionId,'confirmed');$assert(false,'Conflict recheck accepted maintenance overlap');}catch(DomainException$e){$assert(true,'Conflict recheck rejected maintenance overlap');}$assert(scopedReservationRecord($conflictTransitionId)['status']==='pending'&&dbFetchOne('SELECT status FROM vehicles WHERE id=:id',['id'=>$vehicleIds[1]])['status']==='available','Conflict rejection changed reservation or vehicle state');
    $readyId=$newPending($vehicleIds[0],'2050-01-10T10:00','2050-01-12T10:00');transitionReservation($readyId,'confirmed');$assert(dbFetchOne('SELECT status FROM vehicles WHERE id=:id',['id'=>$vehicleIds[0]])['status']==='reserved','Confirmation did not reserve vehicle');transitionReservation($readyId,'deposit_paid');transitionReservation($readyId,'ready');try{transitionReservation($readyId,'active');$assert(false,'Direct rental activation bypassed checkout orchestration');}catch(DomainException$e){$assert(true,'Direct rental activation rejected');}$assert(scopedReservationRecord($readyId)['status']==='ready'&&dbFetchOne('SELECT status FROM vehicles WHERE id=:id',['id'=>$vehicleIds[0]])['status']==='reserved','Rejected direct activation changed reservation or vehicle state');transitionReservation($readyId,'cancelled','test cleanup');
    $uploadDir=dirname(__DIR__).'/storage/uploads/phase4_tests';if(!is_dir($uploadDir))mkdir($uploadDir,0750,true);$file=$uploadDir.'/'.strtolower($run).'.pdf';file_put_contents($file,"%PDF-1.4\n% Phase 4 test\n");$filePaths[]=$file;$relative='storage/uploads/phase4_tests/'.basename($file);dbExecute("INSERT INTO customer_documents(customer_id,document_type,storage_path,original_name,mime_type,file_size,created_by) VALUES(:customer,'other',:path,'test.pdf','application/pdf',:size,:user)",['customer'=>$customerId,'path'=>$relative,'size'=>filesize($file),'user'=>$managerId]);$docId=(int)db()->lastInsertId();$metadata=dbFetchOne('SELECT id,storage_path,mime_type FROM customer_documents WHERE id=:id',['id'=>$docId]);$assert(authorizedProtectedFile($metadata)['mime_type']==='application/pdf','Protected document validation failed');try{authorizedProtectedFile(['id'=>$docId,'storage_path'=>'storage/uploads/../outside','mime_type'=>'application/pdf']);$assert(false,'Traversal path accepted');}catch(InvalidArgumentException$e){$assert(true,'Traversal rejected');}
    if(!is_dir($runtime))mkdir($runtime,0750,true);$command=function($label)use($runtime,$managerId,$agencyId,$customerId,$vehicleIds){return escapeshellarg(PHP_BINARY).' '.escapeshellarg(__FILE__).' --concurrency-worker '.escapeshellarg($label).' '.escapeshellarg($runtime).' '.escapeshellarg((string)$managerId).' '.escapeshellarg((string)$agencyId).' '.escapeshellarg((string)$customerId).' '.escapeshellarg((string)$vehicleIds[1]);};$processes=[];foreach(['A','B']as$label){$pipes=[];$processes[$label]=['process'=>proc_open($command($label),[['pipe','r'],['file',PHP_OS_FAMILY==='Windows'?'NUL':'/dev/null','a'],['file',PHP_OS_FAMILY==='Windows'?'NUL':'/dev/null','a']],$pipes),'pipes'=>$pipes];}
    $deadline=microtime(true)+15;while((!is_file($runtime.'/ready-A')||!is_file($runtime.'/ready-B'))&&microtime(true)<$deadline)usleep(20000);$assert(is_file($runtime.'/ready-A')&&is_file($runtime.'/ready-B'),'Concurrency workers did not both pass initial validation');file_put_contents($runtime.'/go','GO');foreach($processes as$label=>$entry){$wait=microtime(true)+20;while(($status=proc_get_status($entry['process']))['running']&&microtime(true)<$wait)usleep(50000);if(($status['running']??false))proc_terminate($entry['process']);proc_close($entry['process']);}$results=[trim((string)@file_get_contents($runtime.'/result-A')),trim((string)@file_get_contents($runtime.'/result-B'))];sort($results);$count=(int)dbFetchOne("SELECT COUNT(*) n FROM reservations WHERE vehicle_id=:vehicle AND pickup_at<'2035-03-12 10:00:00' AND return_at>'2035-03-10 10:00:00'",['vehicle'=>$vehicleIds[1]])['n'];$assert($results===['COMMITTED','CONFLICT'],'True concurrency outcomes invalid: '.implode(',',array_map(fn($value)=>$value!==''?$value:'MISSING',$results)));$assert($count===1,'True concurrency final count invalid: '.$count);
    $stage='opposite replacement concurrency';$swapA=$newPending($vehicleIds[3],'2060-01-10T10:00','2060-01-12T10:00');$swapB=$newPending($vehicleIds[4],'2061-01-10T10:00','2061-01-12T10:00');$swapARecord=scopedReservationRecord($swapA);$swapBRecord=scopedReservationRecord($swapB);$replaceCommand=function($label,$reservation,$vehicle,$updatedAt)use($runtime,$managerId,$agencyId){return escapeshellarg(PHP_BINARY).' '.escapeshellarg(__FILE__).' --replacement-worker '.escapeshellarg($label).' '.escapeshellarg($runtime).' '.escapeshellarg((string)$managerId).' '.escapeshellarg((string)$agencyId).' '.escapeshellarg((string)$reservation).' '.escapeshellarg((string)$vehicle).' '.escapeshellarg($updatedAt);};$processes=[];foreach([['A',$swapA,$vehicleIds[4],$swapARecord['updated_at']],['B',$swapB,$vehicleIds[3],$swapBRecord['updated_at']]]as[$label,$swapReservation,$swapVehicle,$swapUpdated]){$pipes=[];$processes[$label]=['process'=>proc_open($replaceCommand($label,$swapReservation,$swapVehicle,$swapUpdated),[['pipe','r'],['file',PHP_OS_FAMILY==='Windows'?'NUL':'/dev/null','a'],['file',PHP_OS_FAMILY==='Windows'?'NUL':'/dev/null','a']],$pipes),'pipes'=>$pipes];}
    $deadline=microtime(true)+15;while((!is_file($runtime.'/replace-ready-A')||!is_file($runtime.'/replace-ready-B'))&&microtime(true)<$deadline)usleep(20000);$assert(is_file($runtime.'/replace-ready-A')&&is_file($runtime.'/replace-ready-B'),'Opposite replacement workers did not both reach the barrier');file_put_contents($runtime.'/replace-go','GO');foreach($processes as$entry){$wait=microtime(true)+20;while(($status=proc_get_status($entry['process']))['running']&&microtime(true)<$wait)usleep(50000);if(($status['running']??false))proc_terminate($entry['process']);proc_close($entry['process']);}$replacementResults=[trim((string)@file_get_contents($runtime.'/replace-result-A')),trim((string)@file_get_contents($runtime.'/replace-result-B'))];sort($replacementResults);$swapAFinal=scopedReservationRecord($swapA);$swapBFinal=scopedReservationRecord($swapB);$assert($replacementResults===['COMMITTED','COMMITTED'],'Opposite concurrent replacements did not serialize safely: '.implode(',',array_map(fn($value)=>$value!==''?$value:'MISSING',$replacementResults)));$assert((int)$swapAFinal['vehicle_id']===$vehicleIds[4]&&(int)$swapBFinal['vehicle_id']===$vehicleIds[3],'Opposite concurrent replacements produced inconsistent allocations');$assert(dbFetchOne('SELECT status FROM vehicles WHERE id=:id',['id'=>$vehicleIds[3]])['status']==='available'&&dbFetchOne('SELECT status FROM vehicles WHERE id=:id',['id'=>$vehicleIds[4]])['status']==='available','Pending replacement concurrency changed vehicle states');
}catch(Throwable$e){$failures[]='Unexpected Phase 4 test failure at '.$stage.'.';}
finally{$cleanup();}
$remaining=(int)dbFetchOne("SELECT COUNT(*) n FROM agencies WHERE name LIKE :prefix",['prefix'=>$run.'%'])['n'];if($remaining!==0)$cleanupFailures[]='post-cleanup agency verification';if($cleanupFailures)$failures[]='Phase 4 cleanup failed: '.implode(', ',array_unique($cleanupFailures));
if($failures){foreach($failures as$f)fwrite(STDERR,'FAIL: '.$f.PHP_EOL);exit(1);}echo "Phase 4 integration tests passed: schema, RBAC, lifecycle, strict vehicle-state transitions, replacement rollback, ordered replacement concurrency, pricing, protected files, and cleanup.\n";
