<?php
if(PHP_SAPI!=='cli')exit(1);
define('INSPECTION_PHOTO_CLEANUP_TEST_HOOK',true);
require_once dirname(__DIR__).'/app/application.php';require_once __DIR__.'/helpers/phase5b_fixture.php';
$fail=[];$assert=static function(bool $ok,string $message)use(&$fail):void{if(!$ok)$fail[]=$message;};$created=[];$directories=[];$fixture=[];
$relative=static function(string $absolute):string{$root=realpath(inspectionPhotoRoot());return'inspection-photo-private/'.ltrim(str_replace('\\','/',substr($absolute,strlen($root))),'/');};
$file=static function(string $directory,int $age=0)use(&$created):string{$path=$directory.'/'.bin2hex(random_bytes(24)).'.jpg';file_put_contents($path,'P5B5 cleanup test');if($age)touch($path,time()-$age);$created[]=$path;return$path;};
$inspection=static function(array $fixture):int{phase5bAs($fixture,ROLE_AGENCY_MANAGER);$reservation=phase5bCreateReservation($fixture,'CLEANUP');$contract=contractCreateFromReservation(['reservation_id'=>$reservation,'idempotency_key'=>phase5bToken()]);dbExecute("INSERT INTO vehicle_inspections(agency_id,origin_agency_id,performing_agency_id,reservation_id,contract_id,vehicle_id,customer_id,inspection_type,inspected_at,mileage,fuel_level,created_by)VALUES(:agency,:origin,:performing,:reservation,:contract,:vehicle,:customer,'checkout',NOW(6),1,50,:actor)",['agency'=>$fixture['agency_id'],'origin'=>$fixture['agency_id'],'performing'=>$fixture['agency_id'],'reservation'=>$reservation,'contract'=>$contract,'vehicle'=>$fixture['vehicle_id'],'customer'=>$fixture['customer_id'],'actor'=>currentUserId()]);return(int)db()->lastInsertId();};
$cli=static function(array $arguments):array{$command=escapeshellarg(PHP_BINARY).' -d session.save_path='.escapeshellarg(dirname(__DIR__).'/storage').' '.escapeshellarg(dirname(__DIR__).'/bin/cleanup_inspection_photo_orphans.php');foreach($arguments as$argument)$command.=' '.escapeshellarg($argument);$output=[];$code=0;exec($command.' 2>&1',$output,$code);return[$code,implode("\n",$output)];};
try{
    $root=inspectionPhotoRoot();inspectionPhotoEnsureDirectory($root);$grace=(int)appConfig('inspection_photo_orphan_grace_seconds');$token=bin2hex(random_bytes(12));$stage=$root.'/staging/'.$token;inspectionPhotoEnsureDirectory($stage);$directories[]=$stage;$scope='inspection-photo-private/staging/'.$token;
    $oldest=$file($stage,$grace+300);$newer=$file($stage,$grace+200);$young=$file($stage,0);$junk=$stage.'/not-a-controlled-file.txt';file_put_contents($junk,'keep');$created[]=$junk;
    $outside=dirname(__DIR__).'/storage/P5B5_cleanup_outside_'.bin2hex(random_bytes(5)).'.txt';file_put_contents($outside,'outside');$created[]=$outside;$link=$stage.'/'.bin2hex(random_bytes(24)).'.jpg';$linked=@symlink($outside,$link);if($linked)$created[]=$link;else{$source=(string)file_get_contents(dirname(__DIR__).'/app/inspection_photo_service.php');$assert(str_contains($source,'$file->isLink()')&&str_contains($source,'is_link($candidate[\'path\'])'),'Cleanup source lacks its symlink refusal guard');fwrite(STDOUT,"NOTE: Symlink creation is unavailable in this Windows sandbox; source-level guard verified.\n");}
    $one=inspectionPhotoCleanupOrphans(false,1,$scope);$assert($one['would_remove']===[$relative($oldest)],'Limit did not deterministically select the oldest candidate first');$dry=inspectionPhotoCleanupOrphans(false,20,$scope);$assert($dry['would_remove']===[$relative($oldest),$relative($newer)],'Dry run was not deterministic or selected young/out-of-pattern/symlink files');$assert(is_file($oldest)&&is_file($newer),'Dry run removed a candidate');$run=inspectionPhotoCleanupOrphans(true,20,$scope);$assert($run['removed']===$dry['would_remove'],'Execute did not remove the deterministic candidate list');$assert(!is_file($oldest)&&!is_file($newer),'Execute did not remove stale controlled files');$assert(is_file($young)&&is_file($junk)&&is_file($outside)&&($linked?is_link($link):true),'Cleanup removed a young, out-of-pattern, symlink, or outside file');
    $fixture=phase5bFixture('P5B5C_'.strtoupper(bin2hex(random_bytes(4))));$inspectionId=$inspection($fixture);$final=$root.'/final/'.$fixture['agency_id'].'/'.$inspectionId;inspectionPhotoEnsureDirectory($final);$directories[]=$final;$referenced=$file($final,$grace+300);$stored=$relative($referenced);dbExecute('INSERT INTO inspection_photos(agency_id,inspection_id,photo_type,photo_slot,storage_path,original_name,mime_type,file_size,sha256,protected_file,captured_at,created_by)VALUES(:agency,:inspection,\'front\',\'front\',:path,\'P5B5 cleanup\',\'image/jpeg\',:size,:sha,1,NOW(6),:actor)',['agency'=>$fixture['agency_id'],'inspection'=>$inspectionId,'path'=>$stored,'size'=>filesize($referenced),'sha'=>hash_file('sha256',$referenced),'actor'=>currentUserId()]);$photo=(int)db()->lastInsertId();$finalScope='inspection-photo-private/final/'.$fixture['agency_id'].'/'.$inspectionId;$assert(inspectionPhotoCleanupOrphans(false,20,$finalScope)['would_remove']===[],'Referenced evidence was selected for cleanup');dbExecute('UPDATE inspection_photos SET archived_at=NOW(6),archived_by=:actor,archive_reason=\'P5B5 cleanup archive\' WHERE id=:id',['actor'=>currentUserId(),'id'=>$photo]);inspectionPhotoCleanupOrphans(true,20,$finalScope);$assert(is_file($referenced),'Archived referenced evidence was removed');
    [$dryCode,$dryOutput]=$cli(['--dry-run','--limit=1']);$assert($dryCode===0,'Explicit --dry-run did not exit 0');$assert(!str_contains($dryOutput,inspectionPhotoRoot()),'CLI printed an absolute private-storage path');foreach([['--dry-run','--execute'],['--limit=0'],['--limit=abc'],['--unknown']]as$args){[$code]=$cli($args);$assert($code===2,'Invalid cleanup CLI combination did not exit 2: '.implode(' ',$args));}
    foreach([$young,$junk,$link]as$path)if(is_file($path)||is_link($path))@unlink($path);inspectionPhotoRemoveEmptyControlledDirectory($stage);$assert(!is_dir($stage),'Empty controlled staging directory was not removed');
}catch(Throwable $e){$fail[]='Unexpected cleanup failure: '.$e->getMessage();}
finally{foreach($created as$path)if(is_file($path)||is_link($path))@unlink($path);foreach(array_reverse($directories)as$directory)inspectionPhotoRemoveEmptyControlledDirectory($directory);try{if($fixture)phase5bCleanup($fixture);}catch(Throwable $e){$fail[]='Fixture cleanup failed: '.$e->getMessage();}}
if($fail){foreach(array_unique($fail)as$message)fwrite(STDERR,"FAIL: $message\n");exit(1);}echo "Phase 5B.5 inspection-photo cleanup tests passed: isolated deterministic selection, explicit CLI flags, reference preservation, symlink/outside safety, and empty-directory cleanup.\n";
