<?php
if(PHP_SAPI!=='cli')exit(1);
define('INSPECTION_PHOTO_TEST_HOOK',true);function inspectionPhotoCliTestHook(string $stage,array $context=[]):void{}
require_once dirname(__DIR__).'/app/application.php';require_once __DIR__.'/helpers/phase5b_fixture.php';
$fail=[];$assert=static function(bool $ok,string $message)use(&$fail):void{if(!$ok)$fail[]=$message;};$fixture=[];$tmp=[];$stored=[];$server=null;$sessionFile=null;
try{
 $run='P5B5H_'.strtoupper(bin2hex(random_bytes(4)));$fixture=phase5bFixture($run);phase5bAs($fixture,ROLE_AGENCY_MANAGER);$reservation=phase5bCreateReservation($fixture,'HTTP');$contract=contractCreateFromReservation(['reservation_id'=>$reservation,'idempotency_key'=>phase5bToken()]);dbExecute("INSERT INTO vehicle_inspections(agency_id,origin_agency_id,performing_agency_id,reservation_id,contract_id,vehicle_id,customer_id,inspection_type,inspected_at,mileage,fuel_level,created_by) VALUES(:agency,:origin,:performing,:r,:c,:v,:u,'checkout',NOW(6),1,50,:actor)",['agency'=>$fixture['agency_id'],'origin'=>$fixture['agency_id'],'performing'=>$fixture['agency_id'],'r'=>$reservation,'c'=>$contract,'v'=>$fixture['vehicle_id'],'u'=>$fixture['customer_id'],'actor'=>currentUserId()]);$inspection=(int)db()->lastInsertId();$uploads=[];foreach(inspectionPhotoSlots()as$slot){$path=dirname(__DIR__).'/storage/'.$run.'_'.$slot.'.jpg';$im=imagecreatetruecolor(8,8);imagejpeg($im,$path,90);imagedestroy($im);$tmp[]=$path;$uploads[$slot]=['name'=>$slot.'.jpg','type'=>'image/jpeg','tmp_name'=>$path,'error'=>UPLOAD_ERR_OK,'size'=>filesize($path)];}$result=inspectionPhotoPersistBundle($inspection,inspectionPhotoStageBundle($uploads),phase5bToken());$assert($result===$inspection,'HTTP fixture photo creation failed');$photo=dbFetchOne('SELECT * FROM inspection_photos WHERE inspection_id=:id ORDER BY id LIMIT 1',['id'=>$inspection]);$stored[]=inspectionPhotoPath($photo['storage_path']);
 $sid='p5b5'.bin2hex(random_bytes(10));$now=time();$data='user_id|i:'.$fixture['users'][ROLE_AGENCY_MANAGER].';role|s:14:"AGENCY_MANAGER";agency_ids|a:1:{i:0;i:'.$fixture['agency_id'].';}_authenticated_at|i:'.$now.';_created_at|i:'.$now.';_last_activity|i:'.$now.';_regenerated_at|i:'.$now.';';$sessionFile=dirname(__DIR__).'/storage/sess_'.$sid;file_put_contents($sessionFile,$data);
 $port=18000+random_int(100,800);$descriptor=[['pipe','r'],['pipe','w'],['pipe','w']];$server=proc_open([PHP_BINARY,'-d','session.save_path=storage','-S','127.0.0.1:'.$port,'dev_router.php'],$descriptor,$pipes,dirname(__DIR__));if(!is_resource($server))throw new RuntimeException('Server start failed');fclose($pipes[0]);$ready=false;for($i=0;$i<20;$i++){$socket=@fsockopen('127.0.0.1',$port);if($socket){fclose($socket);$ready=true;break;}usleep(150000);}$assert($ready,'Local HTTP server did not become ready');
 $request=static function(string $url,array $headers=[]):array{$context=stream_context_create(['http'=>['ignore_errors'=>true,'timeout'=>5,'header'=>implode("\r\n",$headers)]]);$body=@file_get_contents($url,false,$context);return[$body===false?'':$body,$http_response_header??[]];};[$anon,$anonHeaders]=$request('http://127.0.0.1:'.$port.'/backoffice/inspection_photo.php?id='.$photo['id']);$assert(str_contains(implode("\n",$anonHeaders),'302'),'Anonymous photo request did not redirect to authentication');[$body,$headers]=$request('http://127.0.0.1:'.$port.'/backoffice/inspection_photo.php?id='.$photo['id'],['Cookie: rental_agency_session='.$sid]);$head=implode("\n",$headers);$assert(str_contains($head,'200'),'Authorized protected delivery did not return 200');$assert(str_contains($head,'Content-Type: image/jpeg')&&str_contains($head,'X-Content-Type-Options: nosniff')&&str_contains($head,'Cache-Control: private, no-store, max-age=0'),'Protected response headers are incomplete');$assert(strlen($body)===(int)$photo['file_size'],'Protected response length mismatch');[$direct,$directHeaders]=$request('http://127.0.0.1:'.$port.'/storage/'.$photo['storage_path']);$assert(str_contains(implode("\n",$directHeaders),'404'),'Direct private storage URL was not denied');[$traversal,$traversalHeaders]=$request('http://127.0.0.1:'.$port.'/storage/%2e%2e/app/config.php');$assert(str_contains(implode("\n",$traversalHeaders),'404'),'Encoded traversal was not denied');$assert(!str_contains($body,dirname(__DIR__))&&!preg_match('/SQLSTATE|PDOException|Fatal/i',$body),'Protected response leaked server internals');
}catch(Throwable $e){$fail[]='Unexpected HTTP/security failure: '.$e->getMessage();}
finally{if(is_resource($server)){proc_terminate($server);proc_close($server);}if($sessionFile&&is_file($sessionFile))@unlink($sessionFile);foreach($tmp as$file)if(is_file($file))@unlink($file);if($fixture){foreach(dbFetchAll('SELECT storage_path FROM inspection_photos WHERE agency_id=:agency',['agency'=>$fixture['agency_id']])as$row){$path=inspectionPhotoPath($row['storage_path']);if($path&&is_file($path))@unlink($path);}}foreach($stored as$file)if($file&&is_file($file))@unlink($file);inspectionPhotoPruneEmptyControlledDirectories();try{if($fixture)phase5bCleanup($fixture);}catch(Throwable $e){$fail[]='Cleanup failed: '.$e->getMessage();}}
if($fail){foreach($fail as$message)fwrite(STDERR,"FAIL: $message\n");exit(1);}echo "Phase 5B.5 HTTP/security tests passed: authentication, protected delivery, headers, direct-storage denial, traversal denial, and disclosure scan.\n";
