<?php
if(PHP_SAPI!=='cli')exit(1);
$root=dirname(__DIR__);$migrationPath=$root.'/database/migrations/007_contracts_rental_operations.sql';$migration=(string)file_get_contents($migrationPath);$runner=(string)file_get_contents($root.'/bin/migrate.php');$databaseHelper=(string)file_get_contents($root.'/app/database.php');$connectionBootstrap=(string)file_get_contents($root.'/assets/connectDB.php');$failures=[];
$assert=static function(bool $ok,string $message)use(&$failures):void{if(!$ok)$failures[]=$message;};

/* Source assertions always run, before a database connection is required. */
$tokens=[
    "version='006_finance_core'",'information_schema.COLUMNS','COLUMN_TYPE','IS_NULLABLE','COLUMN_DEFAULT','GENERATION_EXPRESSION','DATETIME_PRECISION','information_schema.STATISTICS','SEQ_IN_INDEX','information_schema.KEY_COLUMN_USAGE','information_schema.REFERENTIAL_CONSTRAINTS','UPDATE_RULE','DELETE_RULE','information_schema.CHECK_CONSTRAINTS','CHECK_CLAUSE',
    'rental_contracts','contract_versions','contract_status_history','contract_acknowledgements','rental_operation_idempotency_keys','vehicle_inspections','inspection_photos',
    'live_reservation_id BIGINT UNSIGNED GENERATED ALWAYS AS',"CASE WHEN status IN('draft','issued','signed','active') THEN reservation_id ELSE NULL END",
    'active_photo_slot VARCHAR(190) GENERATED ALWAYS AS',"CASE WHEN archived_at IS NULL THEN CONCAT(inspection_id,'|',photo_slot) ELSE NULL END",
    'DATETIME(6)','ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci','utf8mb4_unicode_ci','ON UPDATE RESTRICT ON DELETE RESTRICT',
    "('rental_contracts','issued_at','datetime(6)','YES','NULL')",'default_mode VARCHAR(64)',"COALESCE(UPPER(c.COLUMN_DEFAULT),'NULL')<>'NULL'",
    'migration_007_contract_','INSERT IGNORE INTO contract_status_history','incompatible partial rental-operation table','incompatible generated expression',
];
foreach($tokens as$token)$assert(str_contains($migration,$token),'Migration source token missing: '.$token);
$assert(str_contains($runner,'db()->exec($sql);'),'Migration runner does not execute trusted migration SQL directly');
$assert(!str_contains($runner,'prepare($sql)')&&!str_contains($runner,'dbExecute($sql'),'Migration runner prepares trusted migration SQL');
$assert(!str_contains($runner,'PDO::ATTR_EMULATE_PREPARES => true'),'Migration runner weakens PDO prepare mode');
$assert(!str_contains($runner,'prepare($sql)'), 'Migration runner prepares complete migration SQL');
$assert(str_contains($connectionBootstrap,'PDO::ATTR_EMULATE_PREPARES => false'),'Application connection no longer enforces native prepares');
$assert(substr_count($databaseHelper,'->prepare($sql)')>=3,'Application database helpers no longer use native parameterized prepares');
foreach([
    'uq_contracts_live_reservation','idx_contracts_agency_status_created','idx_contracts_agency_reservation','uq_contract_versions_scoped_identity','idx_contract_versions_contract_language','idx_contract_history_contract','uq_contract_ack_version_party','idx_contract_ack_contract','uq_rental_idempotency','idx_rental_idem_performing','uq_inspection_active_photo_slot','idx_inspection_photos_evidence',
    'fk_contracts_reservation_agency','fk_contracts_current_version_agency','fk_contract_versions_predecessor_agency','fk_contract_history_reservation','fk_contract_ack_version','fk_rental_idem_performing_agency','fk_inspections_contract_agency','fk_inspections_reservation_agency','fk_inspection_photos_inspection_agency',
    'chk_contract_status','chk_contract_cancellation','chk_contract_lifecycle_moments','chk_contract_version_language','chk_contract_version_digest','chk_contract_ack_type','chk_rental_idem_completion','chk_inspection_post_return','chk_inspection_photo_slot',
]as$name)$assert(str_contains($migration,$name),'Migration exact structure missing: '.$name);
$sourceIndexes=[
 'uq_contracts_live_reservation'=>'live_reservation_id',
 'idx_contracts_agency_status_created'=>'agency_id,status,created_at,id',
 'idx_contracts_agency_reservation'=>'agency_id,reservation_id,id',
 'uq_contract_versions_scoped_identity'=>'id,agency_id,contract_id',
 'idx_contract_versions_contract_language'=>'agency_id,contract_id,language_code,version_number,id',
 'idx_contract_history_contract'=>'agency_id,contract_id,occurred_at,id',
 'idx_contract_ack_contract'=>'agency_id,contract_id,acknowledged_at,id',
 'uq_rental_idempotency'=>'origin_agency_id,operation_type,key_hash',
 'idx_rental_idem_performing'=>'performing_agency_id,operation_type,created_at,id',
 'uq_inspection_active_photo_slot'=>'active_photo_slot',
 'idx_inspection_photos_evidence'=>'agency_id,inspection_id,photo_slot,archived_at,id',
];
foreach($sourceIndexes as$name=>$columns){$assert(str_contains($migration,$name),'Migration index missing: '.$name);$assert(str_contains($migration,$columns),'Migration index order missing: '.$name.' => '.$columns);}
$sourceFks=[
 'fk_contracts_reservation_agency'=>['reservation_id,agency_id','id,agency_id'],
 'fk_contracts_current_version_agency'=>['current_version_id,agency_id,id','id,agency_id,contract_id'],
 'fk_contract_versions_predecessor_agency'=>['predecessor_version_id,agency_id,contract_id','id,agency_id,contract_id'],
 'fk_contract_history_reservation'=>['reservation_id,agency_id','id,agency_id'],
 'fk_contract_ack_version'=>['contract_version_id,agency_id,contract_id','id,agency_id,contract_id'],
 'fk_rental_idem_performing_agency'=>['performing_agency_id','id'],
 'fk_inspections_contract_agency'=>['contract_id,agency_id','id,agency_id'],
 'fk_inspections_reservation_agency'=>['reservation_id,agency_id','id,agency_id'],
 'fk_inspection_photos_inspection_agency'=>['inspection_id,agency_id','id,agency_id'],
];
foreach($sourceFks as$name=>$columns){$assert(str_contains($migration,$name),'Migration foreign key missing: '.$name);foreach($columns as$columnSet)$assert(str_contains($migration,$columnSet),'Migration foreign-key ordered columns missing: '.$name.' => '.$columnSet);}
$sourceColumns=[
 'issued_at'=>'issued_at DATETIME(6)',
 'signed_at'=>'signed_at DATETIME(6)',
 'activated_at'=>'activated_at DATETIME(6)',
 'completed_at'=>'completed_at DATETIME(6)',
 'cancelled_at'=>'cancelled_at DATETIME(6)',
 'occurred_at'=>'occurred_at DATETIME(6)',
 'acknowledged_at'=>'acknowledged_at DATETIME(6)',
 'created_at'=>'created_at DATETIME(6)',
 'captured_at'=>'captured_at DATETIME(6)',
];
foreach($sourceColumns as$name=>$definition)$assert(str_contains($migration,$definition),'Migration important column/precision missing: '.$name);
$assert(!preg_match('/\bDROP\s+TABLE\b/i',$migration),'Migration contains destructive DROP TABLE DDL');
$assert(!preg_match('/\bDELETE\s+FROM\b/i',$migration),'Migration deletes historical data');
$assert(!preg_match('/\bREPLACE\s+INTO\b/i',$migration),'Migration silently replaces data');
$assert(!str_contains($migration,'INSERT INTO schema_migrations')&&!str_contains($migration,'INSERT IGNORE INTO schema_migrations'),'Migration records its own version');
if($failures){foreach(array_unique($failures)as$f)fwrite(STDERR,"FAIL: $f\n");exit(1);}

require_once $root.'/app/application.php';
$readIndex=static function(string $table,string $index):?array{return dbFetchOne("SELECT MAX(NON_UNIQUE) non_unique,GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX SEPARATOR ',') cols FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:table AND INDEX_NAME=:index GROUP BY TABLE_NAME,INDEX_NAME",['table'=>$table,'index'=>$index]);};
$readFk=static function(string $table,string $name):?array{$rows=dbFetchAll("SELECT k.COLUMN_NAME,k.REFERENCED_TABLE_NAME,k.REFERENCED_COLUMN_NAME,r.UPDATE_RULE,r.DELETE_RULE FROM information_schema.KEY_COLUMN_USAGE k JOIN information_schema.REFERENTIAL_CONSTRAINTS r ON r.CONSTRAINT_SCHEMA=k.CONSTRAINT_SCHEMA AND r.TABLE_NAME=k.TABLE_NAME AND r.CONSTRAINT_NAME=k.CONSTRAINT_NAME WHERE k.CONSTRAINT_SCHEMA=DATABASE() AND k.TABLE_NAME=:table AND k.CONSTRAINT_NAME=:name AND k.REFERENCED_TABLE_NAME IS NOT NULL ORDER BY k.ORDINAL_POSITION",['table'=>$table,'name'=>$name]);if(!$rows)return null;return['local'=>implode(',',array_column($rows,'COLUMN_NAME')),'parent'=>$rows[0]['REFERENCED_TABLE_NAME'],'ref'=>implode(',',array_column($rows,'REFERENCED_COLUMN_NAME')),'update'=>strtoupper($rows[0]['UPDATE_RULE']),'delete'=>strtoupper($rows[0]['DELETE_RULE'])];};
$assert((bool)dbFetchOne("SELECT 1 FROM schema_migrations WHERE version='007_contracts_rental_operations'"),'Migration 007 is not recorded in the configured database.');
foreach(['rental_contracts','contract_versions','contract_status_history','contract_acknowledgements','rental_operation_idempotency_keys','vehicle_inspections','inspection_photos']as$table){$meta=dbFetchOne('SELECT ENGINE,TABLE_COLLATION FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:table',['table'=>$table]);$assert($meta&&strtoupper($meta['ENGINE'])==='INNODB'&&strtolower($meta['TABLE_COLLATION'])==='utf8mb4_unicode_ci',$table.' engine/collation mismatch');}
foreach(['rental_contracts'=>['agency_id','issued_at','current_version_id','cancelled_by','live_reservation_id'],'contract_versions'=>['agency_id','predecessor_version_id','snapshot_sha256'],'contract_status_history'=>['agency_id','contract_id','reservation_id','from_status','to_status','occurred_at','metadata_json','baseline_key'],'contract_acknowledgements'=>['agency_id','contract_id','contract_version_id','acknowledgement_type','language_code','acknowledged_at'],'rental_operation_idempotency_keys'=>['origin_agency_id','performing_agency_id','operation_type','key_hash','payload_hash','created_at','completed_at'],'vehicle_inspections'=>['agency_id','origin_agency_id','performing_agency_id','reservation_id','post_return_vehicle_state','damage_notes','completed_at'],'inspection_photos'=>['agency_id','photo_slot','sha256','protected_file','archived_at','active_photo_slot']]as$table=>$columns)foreach($columns as$column)$assert((bool)dbFetchOne('SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:table AND COLUMN_NAME=:column',['table'=>$table,'column'=>$column]),$table.'.'.$column.' missing');
foreach([['rental_contracts','issued_at'],['contract_versions','created_at'],['contract_status_history','occurred_at'],['contract_acknowledgements','acknowledged_at'],['rental_operation_idempotency_keys','created_at'],['vehicle_inspections','completed_at'],['inspection_photos','captured_at']]as[$table,$column]){$row=dbFetchOne('SELECT DATETIME_PRECISION p FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:table AND COLUMN_NAME=:column',['table'=>$table,'column'=>$column]);$assert($row&&(int)$row['p']===6,$table.'.'.$column.' is not DATETIME(6)');}
$generated=[['rental_contracts','live_reservation_id',"CASE WHEN status IN('draft','issued','signed','active') THEN reservation_id ELSE NULL END"],['inspection_photos','active_photo_slot',"CASE WHEN archived_at IS NULL THEN CONCAT(inspection_id,'|',photo_slot) ELSE NULL END"]];
foreach($generated as[$table,$column,$expected]){$row=dbFetchOne('SELECT GENERATION_EXPRESSION expression FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=:table AND COLUMN_NAME=:column',['table'=>$table,'column'=>$column]);$normalize=static fn(string $v):string=>strtolower(str_replace(['`',' ','(',')',"\n","\r","\t"],'',$v));$assert($row&&$normalize((string)$row['expression'])===$normalize($expected),$table.'.'.$column.' generated expression mismatch');}
foreach([['rental_contracts','uq_contracts_live_reservation','live_reservation_id',0],['rental_contracts','idx_contracts_agency_status_created','agency_id,status,created_at,id',1],['contract_versions','uq_contract_versions_scoped_identity','id,agency_id,contract_id',0],['contract_versions','idx_contract_versions_contract_language','agency_id,contract_id,language_code,version_number,id',1],['contract_status_history','uq_contract_history_baseline','baseline_key',0],['contract_acknowledgements','uq_contract_ack_version_party','contract_version_id,acknowledgement_type',0],['rental_operation_idempotency_keys','uq_rental_idempotency','origin_agency_id,operation_type,key_hash',0],['rental_operation_idempotency_keys','idx_rental_idem_performing','performing_agency_id,operation_type,created_at,id',1],['inspection_photos','uq_inspection_active_photo_slot','active_photo_slot',0],['inspection_photos','idx_inspection_photos_evidence','agency_id,inspection_id,photo_slot,archived_at,id',1]]as[$table,$index,$cols,$nonUnique]){$row=$readIndex($table,$index);$assert($row&&(int)$row['non_unique']===$nonUnique&&$row['cols']===$cols,$table.'.'.$index.' wrong uniqueness/order');}
foreach([['rental_contracts','fk_contracts_reservation_agency','reservation_id,agency_id','reservations','id,agency_id'],['rental_contracts','fk_contracts_current_version_agency','current_version_id,agency_id,id','contract_versions','id,agency_id,contract_id'],['contract_versions','fk_contract_versions_predecessor_agency','predecessor_version_id,agency_id,contract_id','contract_versions','id,agency_id,contract_id'],['contract_acknowledgements','fk_contract_ack_version','contract_version_id,agency_id,contract_id','contract_versions','id,agency_id,contract_id'],['vehicle_inspections','fk_inspections_contract_agency','contract_id,agency_id','rental_contracts','id,agency_id'],['inspection_photos','fk_inspection_photos_inspection_agency','inspection_id,agency_id','vehicle_inspections','id,agency_id,contract_id']]as[$table,$name,$local,$parent,$ref]){$row=$readFk($table,$name);$expectedRef=$name==='fk_inspection_photos_inspection_agency'?'id,agency_id':$ref;$assert($row&&$row['local']===$local&&$row['parent']===$parent&&$row['ref']===$expectedRef&&in_array($row['update'],['RESTRICT','NO ACTION'],true)&&in_array($row['delete'],['RESTRICT','NO ACTION'],true),$table.'.'.$name.' wrong ordered FK/rule');}
foreach(['chk_contract_status','chk_contract_cancellation','chk_contract_lifecycle_moments','chk_contract_version_language','chk_contract_version_digest','chk_contract_ack_type','chk_contract_ack_language','chk_contract_ack_method','chk_rental_idem_status','chk_rental_idem_completion','chk_inspection_type','chk_inspection_status','chk_inspection_fuel','chk_inspection_post_return','chk_inspection_photo_slot']as$name)$assert((bool)dbFetchOne("SELECT 1 FROM information_schema.TABLE_CONSTRAINTS WHERE CONSTRAINT_SCHEMA=DATABASE() AND CONSTRAINT_NAME=:name AND CONSTRAINT_TYPE='CHECK'",['name'=>$name]),'CHECK missing: '.$name);
if($failures){foreach(array_unique($failures)as$f)fwrite(STDERR,"FAIL: $f\n");exit(1);}
echo "Phase 5B migration structural assertions passed.\n";

$charset=preg_match('/^[A-Za-z0-9_]+$/',(string)getenv('DB_CHARSET'))?(string)getenv('DB_CHARSET'):'utf8mb4';$dsn='mysql:host='.getenv('DB_HOST').';port='.(int)getenv('DB_PORT').';charset='.$charset;$admin=null;$created=[];$run='p5b_recovery_'.strtolower(bin2hex(random_bytes(4)));
$id=static function(string $value):string{if(!preg_match('/^[A-Za-z0-9_]+$/',$value))throw new RuntimeException('Unsafe disposable identifier');return chr(96).$value.chr(96);};
try{$admin=new PDO($dsn,(string)getenv('DB_USER'),(string)getenv('DB_PASSWORD'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_EMULATE_PREPARES=>false]);$probe=$run.'_probe';$admin->exec('CREATE DATABASE '.$id($probe).' CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');$admin->exec('DROP DATABASE '.$id($probe));}catch(Throwable$e){fwrite(STDERR,"PENDING: Privileged disposable-database scenarios are PENDING because CREATE DATABASE authority is unavailable.\n");exit(2);}
$connect=static function(string $database)use($dsn):PDO{return new PDO($dsn.';dbname='.$database,(string)getenv('DB_USER'),(string)getenv('DB_PASSWORD'),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_EMULATE_PREPARES=>false]);};
$newDb=static function(string $label)use($admin,$id,$run,&$created):string{$database=$run.'_'.$label;$admin->exec('CREATE DATABASE '.$id($database).' CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');$created[]=$database;return$database;};
$prepare=static function(PDO $pdo)use($root):void{foreach(['001_authoritative_schema.sql','003_operational_extensions.sql','004_vehicle_detail_media.sql','005_customer_reservation_workspace.sql','006_finance_core.sql']as$file)$pdo->exec((string)file_get_contents($root.'/database/migrations/'.$file));foreach(['001_authoritative_schema','002_import_legacy_data','003_operational_extensions','004_vehicle_detail_media','005_customer_reservation_workspace','006_finance_core']as$version)$pdo->prepare('INSERT IGNORE INTO schema_migrations(version)VALUES(?)')->execute([$version]);};
$run007=static function(string $database)use($root):array{$old=(string)getenv('DB_NAME');putenv('DB_NAME='.$database);$process=proc_open([PHP_BINARY,'-d','session.save_path='.$root.'/storage',$root.'/bin/migrate.php'],[['pipe','r'],['pipe','w'],['pipe','w']],$pipes,$root);if(!is_resource($process)){putenv('DB_NAME='.$old);return['code'=>1,'out'=>''];}fclose($pipes[0]);$out=(string)stream_get_contents($pipes[1]).(string)stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$code=proc_close($process);putenv('DB_NAME='.$old);return compact('code','out');};
$seed=static function(PDO $pdo,string $tag='P5B'):array{$pdo->exec("INSERT INTO agencies(name,code,status)VALUES('$tag A','$tag"."A','active'),('$tag B','$tag"."B','active')");$a=(int)$pdo->query("SELECT id FROM agencies WHERE code='$tag"."A'")->fetchColumn();$b=(int)$pdo->query("SELECT id FROM agencies WHERE code='$tag"."B'")->fetchColumn();$pdo->exec("INSERT INTO users(fullname,email,email_normalized,password_hash,role,status)VALUES('$tag User','$tag@example.test','$tag@example.test','x','OWNER','active')");$u=(int)$pdo->lastInsertId();$pdo->exec("INSERT INTO customers(agency_id,first_name,last_name,status,created_by,updated_by)VALUES($a,'$tag','Customer','regular',$u,$u)");$customer=(int)$pdo->lastInsertId();$pdo->exec("INSERT INTO vehicle_categories(agency_id,name,code,status)VALUES($a,'$tag Category','$tag"."CAT','active')");$category=(int)$pdo->lastInsertId();$pdo->exec("INSERT INTO vehicles(agency_id,category_id,registration_number,brand,model,status,created_by,updated_by)VALUES($a,$category,'$tag"."VEH','P5B','Fixture','available',$u,$u)");$vehicle=(int)$pdo->lastInsertId();$pdo->exec("INSERT INTO reservations(reference,agency_id,return_agency_id,customer_id,vehicle_id,category_id,status,source,pickup_at,return_at,currency,daily_price,rental_days,tax_rate,total_amount,advance_amount,legacy_finance_paid_amount,remaining_amount,deposit_amount,pricing_snapshot_json,finance_tracking_started_at,created_by,updated_by)VALUES('$tag"."RES',$a,$a,$customer,$vehicle,$category,'confirmed','agency','2035-01-01 10:00:00','2035-01-02 10:00:00','MAD',100,1,0,100,0,0,100,0,'{}',NOW(6),$u,$u)");$reservation=(int)$pdo->lastInsertId();return compact('a','b','u','customer','category','vehicle','reservation');};
$contract=static function(PDO $pdo,array $x,string $number,string $status='generated'):int{$pdo->exec("INSERT INTO rental_contracts(reservation_id,contract_number,status,current_version,created_by,updated_by)VALUES({$x['reservation']},'$number','$status',1,{$x['u']},{$x['u']})");$contract=(int)$pdo->lastInsertId();$pdo->exec("INSERT INTO contract_versions(contract_id,version_number,language_code,snapshot_json,terms_text,created_by)VALUES($contract,1,'fr','{}','P5B_TEST',{$x['u']})");return$contract;};
$fingerprint=static function(PDO $pdo):array{$out=[];foreach(['rental_contracts','contract_versions','contract_status_history','vehicle_inspections','inspection_photos']as$table){$rows=$pdo->query("SELECT * FROM $table ORDER BY 1")->fetchAll(PDO::FETCH_ASSOC);$out[$table]=hash('sha256',json_encode($rows,JSON_THROW_ON_ERROR));}return$out;};
$failureScenario=static function(string $label,callable $mutator,bool $withFixture=false)use($newDb,$connect,$prepare,$run007,$seed,$fingerprint,&$assert):void{$database=$newDb($label);$pdo=$connect($database);$prepare($pdo);$fixture=$withFixture?$seed($pdo,'X'.strtoupper(substr($label,0,8))):null;$before=$fingerprint($pdo);$mutator($pdo,$fixture);$result=$run007($database);$assert($result['code']===1,$label.' did not fail closed');$assert((int)$pdo->query("SELECT COUNT(*) FROM schema_migrations WHERE version='007_contracts_rental_operations'")->fetchColumn()===0,$label.' recorded migration 007');$assert($fingerprint($pdo)===$before,$label.' deleted, rewrote, or relinked historical rows');};

try{
    /* 1, 2, 21: clean installation, recorded rerun, and baseline retry. */
    $database=$newDb('clean');$pdo=$connect($database);$prepare($pdo);$fixture=$seed($pdo,'P5BCLEAN');$legacy=$contract($pdo,$fixture,'P5B-CLEAN','generated');$first=$run007($database);$assert($first['code']===0&&str_contains($first['out'],'APPLY 007_contracts_rental_operations'),'Clean installation failed');$assert((int)$pdo->query("SELECT COUNT(*) FROM contract_status_history WHERE contract_id=$legacy")->fetchColumn()===1,'Clean install baseline history missing');$rerun=$run007($database);$assert($rerun['code']===0&&str_contains($rerun['out'],'SKIP 007_contracts_rental_operations'),'Recorded migration rerun failed');$pdo->exec("DELETE FROM schema_migrations WHERE version='007_contracts_rental_operations'");$retry=$run007($database);$assert($retry['code']===0&&(int)$pdo->query("SELECT COUNT(*) FROM contract_status_history WHERE contract_id=$legacy")->fetchColumn()===1,'Retry-safe baseline history failed');
    /* 3: compatible interrupted DDL with a missing ordinary index. */
    $database=$newDb('partial');$pdo=$connect($database);$prepare($pdo);$pdo->exec($migration);$pdo->exec('ALTER TABLE rental_contracts DROP INDEX idx_contracts_agency_status_created');$partial=$run007($database);$assert($partial['code']===0,'Compatible missing-object recovery failed');$assert((int)$pdo->query("SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='rental_contracts' AND INDEX_NAME='idx_contracts_agency_status_created'")->fetchColumn()===4,'Missing ordinary index was not restored');
    /* 4–19: same-name incompatibilities and data preflight failures. */
    $failureScenario('column_type',static function(PDO $p):void{$p->exec('ALTER TABLE rental_contracts ADD COLUMN agency_id INT NULL');});
    $failureScenario('column_null_default',static function(PDO $p):void{$p->exec('ALTER TABLE rental_contracts ADD COLUMN issued_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)');});
    $failureScenario('generated',static function(PDO $p):void{$p->exec('ALTER TABLE rental_contracts ADD COLUMN live_reservation_id BIGINT UNSIGNED GENERATED ALWAYS AS (reservation_id) PERSISTENT');});
    $failureScenario('non_unique_index',static function(PDO $p):void{$p->exec("ALTER TABLE rental_contracts ADD COLUMN live_reservation_id BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN status IN('draft','issued','signed','active') THEN reservation_id ELSE NULL END) PERSISTENT, ADD KEY uq_contracts_live_reservation(live_reservation_id)");});
    $failureScenario('index_order',static function(PDO $p):void{$p->exec('ALTER TABLE rental_contracts ADD COLUMN agency_id BIGINT UNSIGNED NULL, ADD KEY idx_contracts_agency_status_created(status,agency_id,created_at,id)');});
    $failureScenario('fk_local_order',static function(PDO $p):void{$p->exec('ALTER TABLE rental_contracts ADD COLUMN agency_id BIGINT UNSIGNED NULL, ADD CONSTRAINT fk_contracts_reservation_agency FOREIGN KEY(agency_id,reservation_id) REFERENCES reservations(id,agency_id) ON UPDATE RESTRICT ON DELETE RESTRICT');});
    $failureScenario('fk_ref_order',static function(PDO $p):void{$p->exec('ALTER TABLE reservations ADD UNIQUE KEY uq_p5b_wrong_order(agency_id,id)');$p->exec('ALTER TABLE rental_contracts ADD COLUMN agency_id BIGINT UNSIGNED NULL, ADD CONSTRAINT fk_contracts_reservation_agency FOREIGN KEY(reservation_id,agency_id) REFERENCES reservations(agency_id,id) ON UPDATE RESTRICT ON DELETE RESTRICT');});
    $failureScenario('fk_cascade',static function(PDO $p):void{$p->exec('ALTER TABLE rental_contracts ADD COLUMN agency_id BIGINT UNSIGNED NULL, ADD CONSTRAINT fk_contracts_reservation_agency FOREIGN KEY(reservation_id,agency_id) REFERENCES reservations(id,agency_id) ON UPDATE RESTRICT ON DELETE CASCADE');});
    $failureScenario('permissive_check',static function(PDO $p):void{$p->exec("ALTER TABLE rental_contracts ADD CONSTRAINT chk_contract_status CHECK(status<>'')");});
    $failureScenario('duplicate_live',static function(PDO $p,array $x)use($contract):void{$contract($p,$x,'P5B-DUP-1','draft');$p->exec("INSERT INTO rental_contracts(reservation_id,contract_number,status,current_version,created_by,updated_by)VALUES({$x['reservation']},'P5B-DUP-2','draft',1,{$x['u']},{$x['u']})");},true);
    $failureScenario('cross_contract',static function(PDO $p,array $x)use($contract):void{$id=$contract($p,$x,'P5B-CROSS-C','draft');$p->exec('ALTER TABLE rental_contracts ADD COLUMN agency_id BIGINT UNSIGNED NULL');$p->exec("UPDATE rental_contracts SET agency_id={$x['b']} WHERE id=$id");},true);
    $failureScenario('cross_version',static function(PDO $p,array $x)use($contract):void{$id=$contract($p,$x,'P5B-CROSS-V','generated');$p->exec('ALTER TABLE rental_contracts ADD COLUMN agency_id BIGINT UNSIGNED NULL');$p->exec('ALTER TABLE contract_versions ADD COLUMN agency_id BIGINT UNSIGNED NULL');$p->exec("UPDATE rental_contracts SET agency_id={$x['a']} WHERE id=$id");$p->exec("UPDATE contract_versions SET agency_id={$x['b']} WHERE contract_id=$id");},true);
    $failureScenario('invalid_status',static function(PDO $p,array $x)use($contract):void{$contract($p,$x,'P5B-BAD','unapproved');},true);
    $failureScenario('duplicate_photo',static function(PDO $p,array $x)use($contract):void{$id=$contract($p,$x,'P5B-PHOTO','draft');$p->exec("INSERT INTO vehicle_inspections(contract_id,vehicle_id,customer_id,inspection_type,inspected_at,mileage,fuel_level,status,created_by)VALUES($id,{$x['vehicle']},{$x['customer']},'checkout','2035-01-01 10:00:00',1,50,'draft',{$x['u']})");$inspection=(int)$p->lastInsertId();$p->exec("INSERT INTO inspection_photos(inspection_id,photo_type,storage_path,mime_type,file_size,captured_at,created_by)VALUES($inspection,'front','a.jpg','image/jpeg',1,'2035-01-01 10:00:00',{$x['u']}),($inspection,'front','b.jpg','image/jpeg',1,'2035-01-01 10:00:00',{$x['u']})");},true);
    $failureScenario('engine_collation',static function(PDO $p):void{$p->exec('ALTER TABLE rental_contracts CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci');});
    $failureScenario('partial_wrong_defs',static function(PDO $p):void{$p->exec("CREATE TABLE rental_operation_idempotency_keys(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,origin_agency_id INT NOT NULL,operation_type VARCHAR(50) NOT NULL,key_hash CHAR(64) NOT NULL,payload_hash CHAR(64) NOT NULL,status VARCHAR(20) NOT NULL,created_by BIGINT UNSIGNED NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");});
    /* 20: retry after a failed partial migration after repairing only the disposable fixture. */
    $database=$newDb('failed_retry');$pdo=$connect($database);$prepare($pdo);$pdo->exec("CREATE TABLE rental_operation_idempotency_keys(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,origin_agency_id INT NOT NULL,operation_type VARCHAR(50) NOT NULL,key_hash CHAR(64) NOT NULL,payload_hash CHAR(64) NOT NULL,status VARCHAR(20) NOT NULL,created_by BIGINT UNSIGNED NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");$failed=$run007($database);$assert($failed['code']===1,'Failed partial fixture did not fail');$assert((int)$pdo->query("SELECT COUNT(*) FROM schema_migrations WHERE version='007_contracts_rental_operations'")->fetchColumn()===0,'Failed partial fixture recorded 007');$pdo->exec('DROP TABLE rental_operation_idempotency_keys');$assert($run007($database)['code']===0,'Retry after failed partial fixture failed');
}catch(Throwable $e){$failures[]='Unexpected privileged Phase 5B migration recovery failure: '.$e->getMessage();}
finally{foreach(array_reverse($created)as$database)try{$admin->exec('DROP DATABASE IF EXISTS '.$id($database));$check=$admin->prepare('SELECT COUNT(*) FROM information_schema.SCHEMATA WHERE SCHEMA_NAME=?');$check->execute([$database]);if((int)$check->fetchColumn()!==0)$failures[]='Disposable database was not removed: '.$database;}catch(Throwable $e){$failures[]='Disposable database cleanup failed: '.$database;}}
if($failures){foreach(array_unique($failures)as$f)fwrite(STDERR,"FAIL: $f\n");exit(1);}
echo "Phase 5B privileged disposable migration scenarios passed: clean install, rerun, compatible recovery, incompatible structures, preflights, failed-partial retry, baseline replay, and cleanup.\n";
