<?php
if(PHP_SAPI!=='cli')exit(1);
define('INSPECTION_PHOTO_TEST_HOOK',true);
require_once __DIR__.'/../app/application.php';
require_once __DIR__.'/helpers/phase5b_fixture.php';
require_once __DIR__.'/helpers/phase5b6_catalogue.php';

$failures=[];$assert=static function(bool $condition,string $message)use(&$failures):void{if(!$condition)$failures[]=$message;};
$root=dirname(__DIR__);$run='P5B6HTTP_'.strtoupper(bin2hex(random_bytes(4)));$fixtures=[];$temporaryFiles=[];$sessionFiles=[];$logs=[];$server=null;$responses=[];$errorResponses=[];$childEvidence=[];$inventoryBefore=p5b6RuntimeInventory();

$runChild=static function(string $test)use($root,$assert,&$childEvidence):void{
    $runtimeBefore=p5b6RuntimeInventory();
    $process=proc_open([PHP_BINARY,'-d','session.save_path='.$root.'/storage',$root.'/'.$test],[['pipe','r'],['pipe','w'],['pipe','w']],$pipes,$root);
    if(!is_resource($process)){$assert(false,'Could not start '.$test);return;}
    fclose($pipes[0]);$stdout=(string)stream_get_contents($pipes[1]);$stderr=(string)stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$exit=proc_close($process);
    $childEvidence[$test]=['exit'=>$exit,'stdout'=>trim($stdout),'stderr'=>trim($stderr)];$assert($exit===0,$test.' failed: '.$stderr.$stdout);$assert(!preg_match(p5b6DisclosurePattern(),$stderr),$test.' stderr disclosed internals');
    $runtimeAfter=p5b6RuntimeInventory();foreach(array_values(array_diff($runtimeAfter,$runtimeBefore))as$relative){if(!preg_match('#^final/[0-9]+/$#',$relative))continue;$directory=inspectionPhotoRoot().'/'.rtrim($relative,'/');$items=is_dir($directory)?array_values(array_diff(scandir($directory)?:[],['.','..'])):['not-a-directory'];if($items===[])@rmdir($directory);}$assert(p5b6RuntimeInventory()===$runtimeBefore,$test.' left controlled runtime entries');
};

try{
    foreach(['tests/contract_acknowledgement_phase5b2_http.php','tests/inspection_photos_phase5b5_http.php','tests/rental_checkout_phase5b3_http.php','tests/rental_checkin_phase5b4_http.php']as$child)$runChild($child);

    $fixture=phase5bFixture($run);$fixtures[]=$fixture;$foreign=phase5bFixture($run.'_FOREIGN');$fixtures[]=$foreign;$uploadFixture=phase5bFixture($run.'_UPLOAD');$fixtures[]=$uploadFixture;
    dbExecute("INSERT INTO users(fullname,email,email_normalized,password_hash,role,status)VALUES(:name,:email,:email2,:hash,:role,'active')",['name'=>$run.' CUSTOMER','email'=>strtolower($run.'_customer@example.test'),'email2'=>strtolower($run.'_customer@example.test'),'hash'=>password_hash(bin2hex(random_bytes(16)),PASSWORD_DEFAULT),'role'=>ROLE_CUSTOMER]);$fixture['users'][ROLE_CUSTOMER]=(int)db()->lastInsertId();$fixtures[0]=$fixture;
    $ctx=p5b6PrepareCheckout($fixture,'MAIN',$temporaryFiles);$foreignCtx=p5b6PrepareCheckout($foreign,'FOREIGN',$temporaryFiles);$uploadCtx=p5b6PrepareCheckout($uploadFixture,'UPLOAD',$temporaryFiles,false);
    phase5bAs($fixture,ROLE_AGENCY_MANAGER);$eligibleReservation=phase5bCreateReservation($fixture,'CREATE','confirmed');$issuedReservation=phase5bCreateReservation($fixture,'ISSUE','confirmed');$issuedContract=contractCreateFromReservation(['reservation_id'=>$issuedReservation,'idempotency_key'=>phase5bToken()]);$cancelReservation=phase5bCreateReservation($fixture,'CANCEL','confirmed');$cancelContract=contractCreateFromReservation(['reservation_id'=>$cancelReservation,'idempotency_key'=>phase5bToken()]);
    phase5bAs($foreign,ROLE_AGENCY_MANAGER);$foreignDetail=contractScopedDetail($foreignCtx['contract'])['contract'];phase5bAs($fixture,ROLE_AGENCY_MANAGER);

    foreach([
        'manager'=>[$fixture['users'][ROLE_AGENCY_MANAGER],ROLE_AGENCY_MANAGER,[$fixture['agency_id']]],
        'agent'=>[$fixture['users'][ROLE_RENTAL_AGENT],ROLE_RENTAL_AGENT,[$fixture['agency_id']]],
        'accountant'=>[$fixture['users'][ROLE_ACCOUNTANT],ROLE_ACCOUNTANT,[$fixture['agency_id']]],
        'fleet'=>[$fixture['users'][ROLE_FLEET_AGENT],ROLE_FLEET_AGENT,[$fixture['agency_id']]],
        'customer'=>[$fixture['users'][ROLE_CUSTOMER],ROLE_CUSTOMER,[]],
        'owner'=>[$fixture['users'][ROLE_OWNER],ROLE_OWNER,[]],
        'no_agency'=>[$fixture['users'][ROLE_AGENCY_MANAGER],ROLE_AGENCY_MANAGER,[]],
        'upload_manager'=>[$uploadFixture['users'][ROLE_AGENCY_MANAGER],ROLE_AGENCY_MANAGER,[$uploadFixture['agency_id']]],
    ]as$name=>$identity){[$sessions[$name],$csrf[$name],$sessionFiles[]]=p5b6Session($identity[0],$identity[1],$identity[2]);}
    [$inactiveSession,$inactiveCsrf,$sessionFiles[]]=p5b6Session($fixture['users'][ROLE_AGENCY_MANAGER],ROLE_AGENCY_MANAGER,[$fixture['agency_id']]);

    $socket=stream_socket_server('tcp://127.0.0.1:0',$errno,$error);if(!$socket)throw new RuntimeException($error);$name=(string)stream_socket_get_name($socket,false);fclose($socket);$port=(int)substr(strrchr($name,':'),1);$base='http://127.0.0.1:'.$port;
    $logs=[tempnam($root.'/storage','p5b6-http-out-'),tempnam($root.'/storage','p5b6-http-err-')];
    $server=proc_open([PHP_BINARY,'-d','session.save_path='.$root.'/storage','-S','127.0.0.1:'.$port,'dev_router.php'],[['pipe','r'],['file',$logs[0],'a'],['file',$logs[1],'a']],$pipes,$root);if(!is_resource($server))throw new RuntimeException('Phase 5B.6 HTTP server did not start.');fclose($pipes[0]);
    $ready=false;for($attempt=0;$attempt<30;$attempt++){$probe=p5b6HttpRequest($base.'/backoffice/contracts.php',$sessions['manager']);if($probe['body']!==''){$ready=true;break;}usleep(100000);}if(!$ready)throw new RuntimeException('Phase 5B.6 HTTP server did not become ready: '.trim((string)@file_get_contents($logs[1])));

    $routes=[
        'contracts'=>$base.'/backoffice/contracts.php',
        'contract_detail'=>$base.'/backoffice/contract_detail.php?id='.$ctx['contract'],
        'contract_print'=>$base.'/backoffice/contract_print.php?id='.$ctx['contract'].'&lang=en',
        'inspections'=>$base.'/backoffice/inspections.php',
        'inspection_photo'=>$base.'/backoffice/inspection_photo.php?id='.$ctx['checkout_photos'][0]['id'],
        'reservation_detail'=>$base.'/backoffice/reservation_detail.php?id='.$ctx['reservation'],
    ];
    foreach($routes as$name=>$url){$anonymous=p5b6HttpRequest($url);$responses[]=$anonymous;$assert(p5b6Status($anonymous,302)||p5b6Status($anonymous,403),$name.' did not require authentication');}
    foreach($routes as$name=>$url){$manager=p5b6HttpRequest($url,$sessions['manager']);$responses[]=$manager;$assert(p5b6Status($manager,200),$name.' refused an authorized manager');}
    foreach(['contracts','contract_detail','contract_print']as$name){$agent=p5b6HttpRequest($routes[$name],$sessions['agent']);$responses[]=$agent;$assert(p5b6Status($agent,200),'Rental agent refused from '.$name);}
    foreach(['inspections','inspection_photo']as$name){$fleet=p5b6HttpRequest($routes[$name],$sessions['fleet']);$responses[]=$fleet;$assert(p5b6Status($fleet,200),'Fleet agent refused from '.$name);}
    foreach(['accountant','customer']as$role)foreach($routes as$name=>$url){$denied=p5b6HttpRequest($url,$sessions[$role]);$errorResponses[]=$denied;$assert(p5b6Status($denied,403)||p5b6Status($denied,404),$role.' was not refused from '.$name);}
    foreach($routes as$name=>$url){$owner=p5b6HttpRequest($url,$sessions['owner']);$responses[]=$owner;$assert(p5b6Status($owner,200),'Owner refused from '.$name);}
    $noAgency=p5b6HttpRequest($routes['contracts'],$sessions['no_agency']);$responses[]=$noAgency;$assert(p5b6Status($noAgency,200)&&!str_contains($noAgency['body'],$foreignDetail['contract_number'])&&!str_contains($noAgency['body'],$foreign['run']),'No-agency session disclosed Phase 5B data');
    dbExecute("UPDATE users SET status='inactive' WHERE id=:id",['id'=>$fixture['users'][ROLE_AGENCY_MANAGER]]);$inactive=p5b6HttpRequest($routes['contracts'],$inactiveSession);$errorResponses[]=$inactive;$assert(p5b6Status($inactive,302)||p5b6Status($inactive,403),'Inactive user was not denied');dbExecute("UPDATE users SET status='active' WHERE id=:id",['id'=>$fixture['users'][ROLE_AGENCY_MANAGER]]);

    $foreignRoutes=[
        $base.'/backoffice/contract_detail.php?id='.$foreignCtx['contract'],
        $base.'/backoffice/contract_print.php?id='.$foreignCtx['contract'].'&lang=en',
        $base.'/backoffice/inspection_photo.php?id='.$foreignCtx['checkout_photos'][0]['id'],
        $base.'/backoffice/reservation_detail.php?id='.$foreignCtx['reservation'],
    ];
    foreach($foreignRoutes as$url){$foreignResponse=p5b6HttpRequest($url,$sessions['manager']);$errorResponses[]=$foreignResponse;$assert(p5b6Status($foreignResponse,404)||p5b6Status($foreignResponse,403),'Foreign entity GET was not refused');$assert(!str_contains($foreignResponse['body'],$foreignDetail['contract_number'])&&!str_contains($foreignResponse['body'],$foreign['run']),'Foreign entity GET disclosed identity');}
    foreach([$routes['contracts'],$routes['inspections']]as$url){$list=p5b6HttpRequest($url,$sessions['manager']);$responses[]=$list;$assert(!str_contains($list['body'],$foreignDetail['contract_number'])&&!str_contains($list['body'],$foreign['run']),'Scoped list disclosed foreign data');}
    foreach(['abc','0','-1','1.5','%20'.$ctx['contract'].'%20','999999999999999999999999999999']as$bad){foreach(['contract_detail.php','contract_print.php']as$page){$malformed=p5b6HttpRequest($base.'/backoffice/'.$page.'?id='.$bad,$sessions['manager']);$errorResponses[]=$malformed;$assert(p5b6Status($malformed,404),$page.' accepted malformed ID '.$bad);}}
    foreach(['abc','0','-1','1.5','%20'.$ctx['checkout_photos'][0]['id'].'%20','999999999999999999999999999999']as$bad){$malformed=p5b6HttpRequest($base.'/backoffice/inspection_photo.php?id='.$bad,$sessions['manager']);$errorResponses[]=$malformed;$assert(p5b6Status($malformed,404),'Photo route accepted malformed ID '.$bad);}

    $contractCountBefore=(int)dbFetchOne('SELECT COUNT(*) n FROM rental_contracts WHERE reservation_id=:reservation',['reservation'=>$eligibleReservation])['n'];
    $create=['action'=>'create','reservation_id'=>(string)$eligibleReservation,'idempotency_key'=>phase5bToken()];
    foreach([p5b6HttpRequest($routes['contracts'],$sessions['manager'],'POST',$create),p5b6HttpRequest($routes['contracts'],$sessions['manager'],'POST',$create+['_csrf'=>'invalid'])]as$csrfFailure){$errorResponses[]=$csrfFailure;$assert(p5b6Status($csrfFailure,419),'Contract creation CSRF failure was accepted');}
    foreach([['x'=>1],'abc','0','-1','1.5',' '.$eligibleReservation.' ','999999999999999999999999999999']as$bad){$crafted=$create;$crafted['reservation_id']=$bad;$crafted['_csrf']=$csrf['manager'];$result=p5b6HttpRequest($routes['contracts'],$sessions['manager'],'POST',$crafted);$errorResponses[]=$result;$assert(p5b6Status($result,302),'Crafted contract ID lacked safe PRG');$assert((int)dbFetchOne('SELECT COUNT(*) n FROM rental_contracts WHERE reservation_id=:reservation',['reservation'=>$eligibleReservation])['n']===$contractCountBefore,'Crafted contract ID created a contract');}
    $validCreate=p5b6HttpRequest($routes['contracts'],$sessions['manager'],'POST',$create+['_csrf'=>$csrf['manager'],'actor_id'=>999,'agency_id'=>$foreign['agency_id'],'role'=>ROLE_OWNER,'customer_id'=>$foreign['customer_id'],'vehicle_id'=>$foreign['vehicle_id']]);$assert(p5b6Status($validCreate,302),'Valid contract creation failed');$createdContract=(int)dbFetchOne('SELECT id FROM rental_contracts WHERE reservation_id=:reservation',['reservation'=>$eligibleReservation])['id'];$createdRow=dbFetchOne('SELECT agency_id,reservation_id,created_by FROM rental_contracts WHERE id=:id',['id'=>$createdContract]);$assert((int)$createdRow['agency_id']===$fixture['agency_id']&&(int)$createdRow['reservation_id']===$eligibleReservation&&(int)$createdRow['created_by']===$fixture['users'][ROLE_AGENCY_MANAGER],'Forged authoritative contract fields were trusted');

    $issueUrl=$base.'/backoffice/contract_detail.php?id='.$issuedContract;$issue=['action'=>'issue','contract_id'=>(string)$issuedContract,'idempotency_key'=>phase5bToken()];
    foreach([p5b6HttpRequest($issueUrl,$sessions['manager'],'POST',$issue),p5b6HttpRequest($issueUrl,$sessions['manager'],'POST',$issue+['_csrf'=>'invalid'])]as$csrfFailure){$errorResponses[]=$csrfFailure;$assert(p5b6Status($csrfFailure,419),'Contract issue CSRF failure was accepted');}
    $validIssue=p5b6HttpRequest($issueUrl,$sessions['manager'],'POST',$issue+['_csrf'=>$csrf['manager']]);$assert(p5b6Status($validIssue,302)&&dbFetchOne('SELECT status FROM rental_contracts WHERE id=:id',['id'=>$issuedContract])['status']==='issued','Valid contract issue failed');$issuedDetail=contractScopedDetail($issuedContract)['contract'];$issuedVersion=(int)$issuedDetail['current_version_id'];
    $ackUrl=$issueUrl;$ackBase=['action'=>'acknowledge','contract_id'=>(string)$issuedContract,'contract_version_id'=>(string)$issuedVersion,'acknowledgement_type'=>'customer','language_code'=>'en','party_name'=>trim($issuedDetail['first_name'].' '.$issuedDetail['last_name']),'acknowledgement_method'=>'in_person','idempotency_key'=>phase5bToken()];
    foreach([p5b6HttpRequest($ackUrl,$sessions['manager'],'POST',$ackBase),p5b6HttpRequest($ackUrl,$sessions['manager'],'POST',$ackBase+['_csrf'=>'invalid'])]as$csrfFailure){$errorResponses[]=$csrfFailure;$assert(p5b6Status($csrfFailure,419),'Acknowledgement CSRF failure was accepted');}
    foreach([['x'=>1],'abc','0','-1','1.5',' '.$issuedVersion.' ','999999999999999999999999999999']as$bad){$crafted=$ackBase;$crafted['contract_version_id']=$bad;$crafted['_csrf']=$csrf['manager'];$result=p5b6HttpRequest($ackUrl,$sessions['manager'],'POST',$crafted);$errorResponses[]=$result;$assert(p5b6Status($result,302),'Crafted version ID lacked safe PRG');$assert((int)dbFetchOne('SELECT COUNT(*) n FROM contract_acknowledgements WHERE contract_id=:contract',['contract'=>$issuedContract])['n']===0,'Crafted version ID created an acknowledgement');}
    $customerKey=$ackBase['idempotency_key'];$validAck=p5b6HttpRequest($ackUrl,$sessions['manager'],'POST',$ackBase+['_csrf'=>$csrf['manager'],'actor_id'=>999,'agency_id'=>$foreign['agency_id'],'role'=>ROLE_OWNER,'reservation_id'=>$foreignCtx['reservation'],'vehicle_id'=>$foreignCtx['vehicle']]);$assert(p5b6Status($validAck,302),'Valid customer acknowledgement failed');$ackRow=dbFetchOne('SELECT agency_id,recorded_by FROM contract_acknowledgements WHERE contract_id=:contract AND acknowledgement_type=\'customer\'',['contract'=>$issuedContract]);$assert((int)$ackRow['agency_id']===$fixture['agency_id']&&(int)$ackRow['recorded_by']===$fixture['users'][ROLE_AGENCY_MANAGER],'Forged acknowledgement authority was trusted');
    $changedReplay=$ackBase;$changedReplay['acknowledgement_type']='agency_representative';$changedReplay['party_name']=$fixture['run'].' '.ROLE_AGENCY_MANAGER;$changedReplay['_csrf']=$csrf['manager'];$conflict=p5b6HttpRequest($ackUrl,$sessions['manager'],'POST',$changedReplay);$errorResponses[]=$conflict;$assert((int)dbFetchOne('SELECT COUNT(*) n FROM contract_acknowledgements WHERE contract_id=:contract',['contract'=>$issuedContract])['n']===1,'Changed-payload acknowledgement replay mutated data');
    $agencyAck=$changedReplay;$agencyAck['idempotency_key']=phase5bToken();$signed=p5b6HttpRequest($ackUrl,$sessions['manager'],'POST',$agencyAck);$assert(p5b6Status($signed,302)&&dbFetchOne('SELECT status FROM rental_contracts WHERE id=:id',['id'=>$issuedContract])['status']==='signed','Valid agency acknowledgement/signing failed');
    $cancelUrl=$base.'/backoffice/contract_detail.php?id='.$cancelContract;$cancel=['action'=>'cancel','contract_id'=>(string)$cancelContract,'reason'=>'Phase 5B.6 HTTP cancellation','idempotency_key'=>phase5bToken()];
    foreach([p5b6HttpRequest($cancelUrl,$sessions['manager'],'POST',$cancel),p5b6HttpRequest($cancelUrl,$sessions['manager'],'POST',$cancel+['_csrf'=>'invalid'])]as$csrfFailure){$errorResponses[]=$csrfFailure;$assert(p5b6Status($csrfFailure,419),'Contract cancellation CSRF failure was accepted');}
    $validCancel=p5b6HttpRequest($cancelUrl,$sessions['manager'],'POST',$cancel+['_csrf'=>$csrf['manager']]);$assert(p5b6Status($validCancel,302)&&dbFetchOne('SELECT status FROM rental_contracts WHERE id=:id',['id'=>$cancelContract])['status']==='cancelled','Valid contract cancellation failed');

    $uploadUrl=$routes['inspections'];$uploadFields=['action'=>'photo_bundle','inspection_id'=>(string)$uploadCtx['checkout'],'idempotency_key'=>phase5bToken(),'_csrf'=>$csrf['upload_manager']];
    foreach([p5b6HttpRequest($uploadUrl,$sessions['upload_manager'],'POST',array_diff_key($uploadFields,['_csrf'=>true])),p5b6HttpRequest($uploadUrl,$sessions['upload_manager'],'POST',array_replace($uploadFields,['_csrf'=>'invalid']))]as$csrfFailure){$errorResponses[]=$csrfFailure;$assert(p5b6Status($csrfFailure,419),'Photo upload CSRF failure was accepted');}
    $boundary='----------------p5b6'.bin2hex(random_bytes(8));$multipart='';foreach($uploadFields as$name=>$value)$multipart.='--'.$boundary."\r\nContent-Disposition: form-data; name=\"$name\"\r\n\r\n$value\r\n";
    foreach(inspectionPhotoSlots()as$slot){$path=$root.'/storage/p5b6-http-upload-'.bin2hex(random_bytes(6)).'.jpg';$image=imagecreatetruecolor(8,8);imagejpeg($image,$path,90);imagedestroy($image);$temporaryFiles[]=$path;$multipart.='--'.$boundary."\r\nContent-Disposition: form-data; name=\"photos[$slot]\"; filename=\"$slot.jpg\"\r\nContent-Type: image/jpeg\r\n\r\n".file_get_contents($path)."\r\n";}$multipart.='--'.$boundary."--\r\n";
    $uploaded=p5b6HttpRequest($uploadUrl,$sessions['upload_manager'],'POST',[],$multipart,['Content-Type: multipart/form-data; boundary='.$boundary,'Content-Length: '.strlen($multipart)]);$uploadedCount=(int)dbFetchOne('SELECT COUNT(*) n FROM inspection_photos WHERE inspection_id=:inspection AND archived_at IS NULL',['inspection'=>$uploadCtx['checkout']])['n'];$uploadFeedback=$uploadedCount===6?'':trim(preg_replace('/\s+/',' ',strip_tags(p5b6HttpRequest($uploadUrl,$sessions['upload_manager'])['body'])));$assert(p5b6Status($uploaded,302)&&$uploadedCount===6,'Valid protected photo upload failed: '.$uploadFeedback);$uploadedPhoto=(int)(dbFetchOne('SELECT id FROM inspection_photos WHERE inspection_id=:inspection ORDER BY id LIMIT 1',['inspection'=>$uploadCtx['checkout']])['id']??0);
    $archive=['action'=>'photo_archive','photo_id'=>(string)$uploadedPhoto,'reason'=>'Phase 5B.6 archive'];foreach([p5b6HttpRequest($uploadUrl,$sessions['upload_manager'],'POST',$archive),p5b6HttpRequest($uploadUrl,$sessions['upload_manager'],'POST',$archive+['_csrf'=>'invalid'])]as$csrfFailure){$errorResponses[]=$csrfFailure;$assert(p5b6Status($csrfFailure,419),'Photo archive CSRF failure was accepted');}$archived=p5b6HttpRequest($uploadUrl,$sessions['upload_manager'],'POST',$archive+['_csrf'=>$csrf['upload_manager']]);$assert(p5b6Status($archived,302),'Valid photo archive failed');$archivedRead=p5b6HttpRequest($base.'/backoffice/inspection_photo.php?id='.$uploadedPhoto,$sessions['upload_manager']);$errorResponses[]=$archivedRead;$assert(p5b6Status($archivedRead,404),'Archived protected photo remained readable');

    $inspectionPage=p5b6HttpRequest($routes['inspections'],$sessions['manager']);$responses[]=$inspectionPage;$assert(str_contains($inspectionPage['body'],'name="action" value="rental_checkout"')&&str_contains($inspectionPage['body'],'name="inspection_id" value="'.$ctx['checkout'].'"'),'Eligible checkout form was hidden');
    $checkout=['action'=>'rental_checkout','inspection_id'=>(string)$ctx['checkout'],'idempotency_key'=>phase5bToken(),'mileage'=>'125','fuel_level'=>'50.00','handed_over_at'=>(new DateTimeImmutable('now'))->format('Y-m-d H:i:s'),'comment'=>'Phase 5B.6 HTTP'];
    foreach([p5b6HttpRequest($uploadUrl,$sessions['manager'],'POST',$checkout),p5b6HttpRequest($uploadUrl,$sessions['manager'],'POST',$checkout+['_csrf'=>'invalid'])]as$csrfFailure){$errorResponses[]=$csrfFailure;$assert(p5b6Status($csrfFailure,419),'Checkout CSRF failure was accepted');}
    foreach([['x'=>1],'abc','0','-1','1.5',' '.$ctx['checkout'].' ','999999999999999999999999999999',$foreignCtx['checkout']]as$bad){$crafted=$checkout;$crafted['inspection_id']=$bad;$crafted['idempotency_key']=phase5bToken();$crafted['_csrf']=$csrf['manager'];$result=p5b6HttpRequest($uploadUrl,$sessions['manager'],'POST',$crafted);$errorResponses[]=$result;$assert(p5b6Status($result,302),'Crafted checkout ID lacked safe PRG');$assert(dbFetchOne('SELECT status FROM reservations WHERE id=:id',['id'=>$ctx['reservation']])['status']==='ready','Crafted checkout ID mutated local rental');}
    foreach(['accountant','fleet','customer']as$role){$denied=p5b6HttpRequest($uploadUrl,$sessions[$role],'POST',$checkout+['_csrf'=>$csrf[$role]]);$errorResponses[]=$denied;$assert(p5b6Status($denied,403),'Unauthorized '.$role.' completed checkout');}
    $checkoutKey=$checkout['idempotency_key'];$completedCheckout=p5b6HttpRequest($uploadUrl,$sessions['manager'],'POST',$checkout+['_csrf'=>$csrf['manager'],'reservation_id'=>$foreignCtx['reservation'],'contract_id'=>$foreignCtx['contract'],'vehicle_id'=>$foreignCtx['vehicle'],'customer_id'=>$foreignCtx['customer'],'actor_id'=>999,'agency_id'=>$foreign['agency_id'],'role'=>ROLE_OWNER]);$assert(p5b6Status($completedCheckout,302)&&dbFetchOne('SELECT status FROM reservations WHERE id=:id',['id'=>$ctx['reservation']])['status']==='active','Valid checkout with forged non-authoritative fields failed');
    $changedCheckout=$checkout;$changedCheckout['mileage']='126';$changedCheckout['_csrf']=$csrf['manager'];$checkoutConflict=p5b6HttpRequest($uploadUrl,$sessions['manager'],'POST',$changedCheckout);$errorResponses[]=$checkoutConflict;$assert((int)dbFetchOne("SELECT COUNT(*) n FROM audit_logs WHERE entity_id=:id AND action='rental.checkout'",['id'=>$ctx['reservation']])['n']===1,'Changed-payload checkout replay duplicated mutation');
    $afterCheckout=p5b6HttpRequest($routes['inspections'],$sessions['manager']);$responses[]=$afterCheckout;$assert(!str_contains($afterCheckout['body'],'name="inspection_id" value="'.$ctx['checkout'].'"')||!str_contains($afterCheckout['body'],'name="action" value="rental_checkout"'),'Checkout form remained eligible after completion');

    phase5bAs($fixture,ROLE_AGENCY_MANAGER);$ctx=p5b6PrepareReturn($fixture,$ctx,$temporaryFiles);$arabicPage=p5b6HttpRequest($routes['inspections'].'?lang=ar',$sessions['manager']);$responses[]=$arabicPage;$assert(preg_match('/<html[^>]+lang="ar"[^>]+dir="rtl"/i',$arabicPage['body'])===1,'Arabic inspection page lacks lang/RTL');$assert(str_contains($arabicPage['body'],'name="action" value="rental_checkin"')&&str_contains($arabicPage['body'],'name="inspection_id" value="'.$ctx['return_inspection'].'"'),'Eligible check-in form was hidden');$assert(str_contains($arabicPage['body'],'<bdi')&&str_contains($arabicPage['body'],$fixture['run']),'Arabic Phase 5B references were not isolated');
    $checkin=['action'=>'rental_checkin','inspection_id'=>(string)$ctx['return_inspection'],'idempotency_key'=>phase5bToken(),'mileage'=>'150','fuel_level'=>'40.00','returned_at'=>(new DateTimeImmutable('now'))->format('Y-m-d H:i:s'),'vehicle_condition'=>'good','comment'=>'Phase 5B.6 HTTP'];
    foreach([p5b6HttpRequest($uploadUrl,$sessions['manager'],'POST',$checkin),p5b6HttpRequest($uploadUrl,$sessions['manager'],'POST',$checkin+['_csrf'=>'invalid'])]as$csrfFailure){$errorResponses[]=$csrfFailure;$assert(p5b6Status($csrfFailure,419),'Check-in CSRF failure was accepted');}
    foreach([['x'=>1],'abc','0','-1','1.5',' '.$ctx['return_inspection'].' ','999999999999999999999999999999',$foreignCtx['checkout']]as$bad){$crafted=$checkin;$crafted['inspection_id']=$bad;$crafted['idempotency_key']=phase5bToken();$crafted['_csrf']=$csrf['manager'];$result=p5b6HttpRequest($uploadUrl,$sessions['manager'],'POST',$crafted);$errorResponses[]=$result;$assert(p5b6Status($result,302),'Crafted check-in ID lacked safe PRG');$assert(dbFetchOne('SELECT status FROM reservations WHERE id=:id',['id'=>$ctx['reservation']])['status']==='active','Crafted check-in ID mutated local rental');}
    $completedCheckin=p5b6HttpRequest($uploadUrl,$sessions['manager'],'POST',$checkin+['_csrf'=>$csrf['manager'],'reservation_id'=>$foreignCtx['reservation'],'contract_id'=>$foreignCtx['contract'],'vehicle_id'=>$foreignCtx['vehicle'],'customer_id'=>$foreignCtx['customer'],'actor_id'=>999,'agency_id'=>$foreign['agency_id'],'role'=>ROLE_OWNER]);$assert(p5b6Status($completedCheckin,302)&&dbFetchOne('SELECT status FROM reservations WHERE id=:id',['id'=>$ctx['reservation']])['status']==='completed','Valid check-in with forged non-authoritative fields failed');
    $changedCheckin=$checkin;$changedCheckin['vehicle_condition']='damaged';$changedCheckin['_csrf']=$csrf['manager'];$checkinConflict=p5b6HttpRequest($uploadUrl,$sessions['manager'],'POST',$changedCheckin);$errorResponses[]=$checkinConflict;$assert((int)dbFetchOne("SELECT COUNT(*) n FROM audit_logs WHERE entity_id=:id AND action='rental.checkin'",['id'=>$ctx['reservation']])['n']===1,'Changed-payload check-in replay duplicated mutation');
    $afterCheckin=p5b6HttpRequest($routes['inspections'],$sessions['manager']);$responses[]=$afterCheckin;$assert(!str_contains($afterCheckin['body'],'name="inspection_id" value="'.$ctx['return_inspection'].'"')||!str_contains($afterCheckin['body'],'name="action" value="rental_checkin"'),'Check-in form remained eligible after completion');

    foreach(['en'=>'ltr','fr'=>'ltr','ar'=>'rtl']as$language=>$direction){$print=p5b6HttpRequest($base.'/backoffice/contract_print.php?id='.$ctx['contract'].'&lang='.$language,$sessions['manager']);$responses[]=$print;$version=dbFetchOne('SELECT terms_text FROM contract_versions WHERE contract_id=:contract AND language_code=:language',['contract'=>$ctx['contract'],'language'=>$language]);$assert(p5b6Status($print,200)&&preg_match('/<html[^>]+lang="'.$language.'"[^>]+dir="'.$direction.'"/i',$print['body'])===1,$language.' print language/direction mismatch');$assert(str_contains($print['body'],htmlspecialchars((string)$version['terms_text'],ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')),$language.' print did not render immutable localized terms');$assert(substr_count($print['body'],'<bdi>')>=8,$language.' print lacks reference/value isolation');$assert(str_contains($print['body'],$foreignDetail['contract_number'])===false,$language.' print disclosed foreign contract');}

    foreach($responses as$response)if(str_contains(implode('\n',$response['headers']),'Content-Type: text/html')||str_starts_with(ltrim($response['body']),'<!doctype html>')){foreach(p5b6TranslationKeys()as$key)$assert(!str_contains($response['body'],$key),'Raw translation key rendered: '.$key);$assert(mb_check_encoding($response['body'],'UTF-8'),'HTTP response is not valid UTF-8');$assert(!preg_match(p5b6DisclosurePattern(),$response['body']),'Successful HTTP response disclosed internals');}
    foreach($errorResponses as$response){$assert(!preg_match(p5b6DisclosurePattern(),$response['body']),'Error HTTP response disclosed internals');foreach($csrf as$token)$assert(!str_contains($response['body'],$token),'Error response disclosed a CSRF token');}
}catch(Throwable $exception){$failures[]='Unexpected Phase 5B.6 HTTP failure: '.$exception->getMessage();}
finally{
    if(is_resource($server)){proc_terminate($server);proc_close($server);$server=null;}
    foreach($logs as$file)if($file&&is_file($file)){foreach($csrf??[]as$token)$assert(!str_contains((string)file_get_contents($file),$token),'Runtime log disclosed a CSRF token');$log=(string)file_get_contents($file);$assert(!preg_match(p5b6DisclosurePattern(),$log),'Runtime log disclosed protected internals');@unlink($file);}
    foreach($sessionFiles as$file)if($file&&is_file($file))@unlink($file);
    foreach($temporaryFiles as$file)if(is_file($file)&&!is_link($file))@unlink($file);
    foreach(array_reverse($fixtures)as$fixture){try{p5b6RemoveFixtureFiles($fixture);phase5bCleanup($fixture);$agencyDirectory=inspectionPhotoRoot().'/final/'.(int)$fixture['agency_id'];for($attempt=0;$attempt<20&&is_dir($agencyDirectory);$attempt++){inspectionPhotoPruneEmptyControlledDirectories();@rmdir($agencyDirectory);if(is_dir($agencyDirectory))usleep(100000);}}catch(Throwable $exception){$failures[]='Phase 5B.6 HTTP cleanup failed: '.$exception->getMessage();}}
    inspectionPhotoPruneEmptyControlledDirectories();
}

$inventoryAfter=p5b6RuntimeInventory();$newInventory=array_values(array_diff($inventoryAfter,$inventoryBefore));$assert($newInventory===[],'Phase 5B.6 HTTP left controlled runtime files: '.implode(',',$newInventory));foreach($sessionFiles as$file)$assert(!is_file($file),'Phase 5B.6 HTTP left session file '.$file);foreach($logs as$file)$assert(!$file||!is_file($file),'Phase 5B.6 HTTP left log file '.$file);
$dbResidue=['agencies'=>(int)dbFetchOne("SELECT COUNT(*) n FROM agencies WHERE name LIKE 'P5B6HTTP%'")['n'],'reservations'=>(int)dbFetchOne("SELECT COUNT(*) n FROM reservations WHERE reference LIKE 'P5B6HTTP%'")['n'],'contracts'=>(int)dbFetchOne("SELECT COUNT(*) n FROM rental_contracts rc JOIN reservations r ON r.id=rc.reservation_id WHERE r.reference LIKE 'P5B6HTTP%'")['n'],'versions'=>(int)dbFetchOne("SELECT COUNT(*) n FROM contract_versions cv JOIN rental_contracts rc ON rc.id=cv.contract_id JOIN reservations r ON r.id=rc.reservation_id WHERE r.reference LIKE 'P5B6HTTP%'")['n'],'acknowledgements'=>(int)dbFetchOne("SELECT COUNT(*) n FROM contract_acknowledgements ca JOIN rental_contracts rc ON rc.id=ca.contract_id JOIN reservations r ON r.id=rc.reservation_id WHERE r.reference LIKE 'P5B6HTTP%'")['n'],'inspections'=>(int)dbFetchOne("SELECT COUNT(*) n FROM vehicle_inspections vi JOIN reservations r ON r.id=vi.reservation_id WHERE r.reference LIKE 'P5B6HTTP%'")['n'],'photos'=>(int)dbFetchOne("SELECT COUNT(*) n FROM inspection_photos ip JOIN vehicle_inspections vi ON vi.id=ip.inspection_id JOIN reservations r ON r.id=vi.reservation_id WHERE r.reference LIKE 'P5B6HTTP%'")['n'],'checkout_in_progress'=>(int)dbFetchOne("SELECT COUNT(*) n FROM rental_operation_idempotency_keys WHERE operation_type='rental_checkout' AND status='in_progress'")['n'],'checkin_in_progress'=>(int)dbFetchOne("SELECT COUNT(*) n FROM rental_operation_idempotency_keys WHERE operation_type='rental_checkin' AND status='in_progress'")['n']];foreach($dbResidue as$name=>$count)$assert($count===0,'Phase 5B.6 HTTP DB residue '.$name.'='.$count);
if($failures){foreach(array_unique($failures)as$message)fwrite(STDERR,"FAIL: $message\n");exit(1);}
echo 'Phase 5B.6 HTTP child regressions: '.json_encode(array_map(static fn($row)=>$row['exit'],$childEvidence),JSON_UNESCAPED_SLASHES).".\n";
echo 'Phase 5B.6 HTTP route/RBAC catalogue: '.json_encode(p5b6Catalogue()['routes'],JSON_UNESCAPED_SLASHES).".\n";
echo 'Phase 5B.6 HTTP cleanup: runtime_before='.count($inventoryBefore).', runtime_after='.count($inventoryAfter).', runtime_new='.count($newInventory).', sessions='.count($sessionFiles).', logs='.count($logs).', db='.json_encode($dbResidue,JSON_UNESCAPED_SLASHES).".\n";
echo "Phase 5B.6 HTTP/security tests passed: routes, authentication, RBAC, agency IDOR, strict IDs, crafted POST, CSRF, protected photos, EN/FR/AR print and RTL, UI eligibility, disclosure, logs, and cleanup.\n";
