<?php
if(PHP_SAPI!=='cli')exit(1);require_once __DIR__.'/../app/application.php';require_once __DIR__.'/helpers/phase5b_fixture.php';require_once __DIR__.'/helpers/rental_checkin_phase5b4_fixture.php';
$fail=[];$assert=static function(bool $ok,string $message)use(&$fail):void{if(!$ok)$fail[]=$message;};$fixtures=[];$files=[];$process=null;$logs=[];$inventoryBefore=p5b4Inventory();$controllerLog='';
try{
    $fixture=phase5bFixture('P5B4HTTP_'.strtoupper(bin2hex(random_bytes(4))));$fixtures[]=$fixture;$agentFixture=phase5bFixture('P5B4HTTP_A'.strtoupper(bin2hex(random_bytes(4))));$fixtures[]=$agentFixture;$foreignFixture=phase5bFixture('P5B4HTTP_F'.strtoupper(bin2hex(random_bytes(4))));$fixtures[]=$foreignFixture;
    $ctx=p5b4Eligible($fixture,'MANAGER',$files);$agentCtx=p5b4Eligible($agentFixture,'AGENT',$files);$foreignCtx=p5b4Eligible($foreignFixture,'FOREIGN',$files);
    [$manager,$csrf]=p5b4Session($fixture['users'][ROLE_AGENCY_MANAGER],ROLE_AGENCY_MANAGER,[$fixture['agency_id']]);[$agent,$agentCsrf]=p5b4Session($agentFixture['users'][ROLE_RENTAL_AGENT],ROLE_RENTAL_AGENT,[$agentFixture['agency_id']]);[$accountant,$accountantCsrf]=p5b4Session($fixture['users'][ROLE_ACCOUNTANT],ROLE_ACCOUNTANT,[$fixture['agency_id']]);[$fleet,$fleetCsrf]=p5b4Session($fixture['users'][ROLE_FLEET_AGENT],ROLE_FLEET_AGENT,[$fixture['agency_id']]);[$customer,$customerCsrf]=p5b4Session($fixture['users'][ROLE_ACCOUNTANT],ROLE_CUSTOMER,[$fixture['agency_id']]);[$noAgency,$noAgencyCsrf]=p5b4Session($fixture['users'][ROLE_RENTAL_AGENT],ROLE_RENTAL_AGENT,[]);[$inactiveManager,$inactiveManagerCsrf]=p5b4Session($fixture['users'][ROLE_AGENCY_MANAGER],ROLE_AGENCY_MANAGER,[$fixture['agency_id']]);[$inactiveAgent,$inactiveAgentCsrf]=p5b4Session($fixture['users'][ROLE_RENTAL_AGENT],ROLE_RENTAL_AGENT,[$fixture['agency_id']]);
    $commandFile=tempnam(dirname(__DIR__).'/storage','p5b4-controller-');$logFile=tempnam(dirname(__DIR__).'/storage','p5b4-controller-log-');$outFile=tempnam(dirname(__DIR__).'/storage','p5b4-controller-out-');file_put_contents($commandFile,json_encode(['session'=>$manager,'csrf'=>$csrf,'inspection_id'=>$ctx['inspection'],'idempotency_key'=>phase5bToken()]));$controller=proc_open([PHP_BINARY,'-d','session.save_path='.dirname(__DIR__).'/storage',__DIR__.'/helpers/rental_checkin_phase5b4_controller_error.php',$commandFile],[['pipe','r'],['file',$outFile,'a'],['file',$logFile,'a']],$pipes,dirname(__DIR__));if(is_resource($controller)){fclose($pipes[0]);proc_close($controller);}$controllerLog=(string)file_get_contents($logFile);foreach([$commandFile,$logFile,$outFile]as$file)if(is_file($file))unlink($file);
    $assert(str_contains($controllerLog,'RuntimeException')&&!preg_match('/P5B4_INTERNAL|SQLSTATE|PDOException|[A-Z]:\\\\|inspection-photo-private|payload_hash|key_hash|stack trace/i',$controllerLog),'Unexpected controller log did not contain only the exception class');

    $socket=stream_socket_server('tcp://127.0.0.1:0',$errno,$err);if(!$socket)throw new RuntimeException($err);$name=(string)stream_socket_get_name($socket,false);fclose($socket);$port=(int)substr(strrchr($name,':'),1);$root=dirname(__DIR__);$logs=[tempnam($root.'/storage','p5b4-http-out-'),tempnam($root.'/storage','p5b4-http-err-')];$process=proc_open([PHP_BINARY,'-d','session.save_path='.$root.'/storage','-S','127.0.0.1:'.$port,'dev_router.php'],[['pipe','r'],['file',$logs[0],'a'],['file',$logs[1],'a']],$pipes,$root);if(!is_resource($process))throw new RuntimeException('server');fclose($pipes[0]);
    $request=static function(string $url,string $session,string $method='GET',array $data=[]):array{$header=$session!==''?'Cookie: rental_agency_session='.$session."\r\n":'';$options=['method'=>$method,'header'=>$header,'timeout'=>5,'ignore_errors'=>true,'max_redirects'=>0];if($method==='POST'){$options['header'].="Content-Type: application/x-www-form-urlencoded\r\n";$options['content']=http_build_query($data);} $body=(string)file_get_contents($url,false,stream_context_create(['http'=>$options]));return['body'=>$body,'status'=>implode(' ',$http_response_header??[])];};$url='http://127.0.0.1:'.$port.'/backoffice/inspections.php';$page=[];for($i=0;$i<30;$i++){try{$page=$request($url.'?lang=en',$manager);if(($page['body']??'')!=='')break;}catch(Throwable){}usleep(100000);}
    $assert(str_contains($page['body']??'','name="action" value="rental_checkin"'),'Eligible manager page lacks check-in form');$assert(str_contains($page['body']??'',t('validation.checkin_failed'))&&!str_contains($page['body']??'','P5B4_INTERNAL'),'Generic unexpected-error flash was not rendered safely');
    $anonymous=$request($url,'');$assert(str_contains($anonymous['status'],'302')||str_contains($anonymous['status'],'403'),'Anonymous request was not refused');$beforeAudit=(int)dbFetchOne("SELECT COUNT(*) n FROM audit_logs WHERE entity_id=:id AND action='rental.checkin'",['id'=>$ctx['reservation']])['n'];$get=$request($url,$manager);$assert((int)dbFetchOne("SELECT COUNT(*) n FROM audit_logs WHERE entity_id=:id AND action='rental.checkin'",['id'=>$ctx['reservation']])['n']===$beforeAudit,'GET mutated return');
    $post=['action'=>'rental_checkin','inspection_id'=>(string)$ctx['inspection'],'idempotency_key'=>phase5bToken(),'mileage'=>'150','fuel_level'=>'40.00','returned_at'=>(new DateTimeImmutable('now'))->format('Y-m-d H:i:s'),'vehicle_condition'=>'good','comment'=>'safe plain text'];$missing=$request($url,$manager,'POST',$post);$invalid=$request($url,$manager,'POST',$post+['_csrf'=>'invalid']);$assert((str_contains($missing['status'],'419')||str_contains($missing['body'],'expired'))&&str_contains($invalid['status'],'419'),'Missing or invalid CSRF was accepted');
    foreach([['array',['x']],['alphabetic','abc'],['zero','0'],['negative','-1'],['decimal','1.5'],['whitespace',' '.$ctx['inspection']]]as[$label,$id]){$response=$request($url,$manager,'POST',array_replace($post,['_csrf'=>$csrf,'inspection_id'=>$id,'idempotency_key'=>phase5bToken()]));$assert(str_contains($response['status'],'302')&&p5b4State($ctx)['reservation_status']==='active','Malformed '.$label.' inspection ID mutated return');}
    $safeDomain=$request($url,$manager,'POST',array_replace($post,['_csrf'=>$csrf,'idempotency_key'=>phase5bToken(),'mileage'=>'149']));$assert(str_contains($safeDomain['status'],'302')&&p5b4State($ctx)['reservation_status']==='active','Safe domain failure did not PRG or changed state');
    $accountantResult=$request($url,$accountant,'POST',$post+['_csrf'=>$accountantCsrf]);$fleetResult=$request($url,$fleet,'POST',$post+['_csrf'=>$fleetCsrf]);$customerResult=$request($url,$customer,'POST',$post+['_csrf'=>$customerCsrf]);$noAgencyResult=$request($url,$noAgency,'POST',$post+['_csrf'=>$noAgencyCsrf]);$assert(str_contains($accountantResult['status'],'403')&&str_contains($fleetResult['status'],'403')&&(str_contains($customerResult['status'],'403')||str_contains($customerResult['status'],'302'))&&str_contains($noAgencyResult['status'],'302'),'Unauthorized or no-agency actor was not refused');
    dbExecute("UPDATE users SET status='inactive' WHERE id IN(:manager,:agent)",['manager'=>$fixture['users'][ROLE_AGENCY_MANAGER],'agent'=>$fixture['users'][ROLE_RENTAL_AGENT]]);$inactiveM=$request($url,$inactiveManager,'POST',$post+['_csrf'=>$inactiveManagerCsrf]);$inactiveA=$request($url,$inactiveAgent,'POST',$post+['_csrf'=>$inactiveAgentCsrf]);$assert((str_contains($inactiveM['status'],'302')||str_contains($inactiveM['status'],'403'))&&(str_contains($inactiveA['status'],'302')||str_contains($inactiveA['status'],'403')),'Inactive actor was not refused');dbExecute("UPDATE users SET status='active' WHERE id IN(:manager,:agent)",['manager'=>$fixture['users'][ROLE_AGENCY_MANAGER],'agent'=>$fixture['users'][ROLE_RENTAL_AGENT]]);
    $foreignResult=$request($url,$manager,'POST',array_replace($post,['_csrf'=>$csrf,'inspection_id'=>(string)$foreignCtx['inspection'],'idempotency_key'=>phase5bToken()]));$assert(str_contains($foreignResult['status'],'302')&&p5b4State($foreignCtx)['reservation_status']==='active','Cross-agency inspection changed data');
    dbExecute("UPDATE inspection_photos SET archived_at=NOW(6),archived_by=:actor,archive_reason='ui guard' WHERE inspection_id=:inspection AND photo_slot='front'",['actor'=>$fixture['users'][ROLE_AGENCY_MANAGER],'inspection'=>$ctx['inspection']]);$incomplete=$request($url.'?lang=en',$manager);$assert(!str_contains($incomplete['body'],'name="action" value="rental_checkin"'),'Check-in form rendered with five active slots');dbExecute("UPDATE inspection_photos SET archived_at=NULL,archived_by=NULL,archive_reason=NULL WHERE inspection_id=:inspection AND photo_slot='front'",['inspection'=>$ctx['inspection']]);$restored=$request($url.'?lang=en',$manager);$assert(str_contains($restored['body'],'name="action" value="rental_checkin"'),'Exact six-slot form did not return');
    foreach([['reservation',"UPDATE reservations SET status='ready' WHERE id=:id","UPDATE reservations SET status='active' WHERE id=:id"],['vehicle',"UPDATE vehicles SET status='reserved' WHERE id=:id","UPDATE vehicles SET status='rented' WHERE id=:id"]]as[$label,$hideSql,$restoreSql]){dbExecute($hideSql,['id'=>$label==='reservation'?$ctx['reservation']:$ctx['vehicle']]);$hidden=$request($url.'?lang=en',$manager);$assert(!str_contains($hidden['body'],'name="action" value="rental_checkin"'),'Form rendered for ineligible '.$label);dbExecute($restoreSql,['id'=>$label==='reservation'?$ctx['reservation']:$ctx['vehicle']]);}
    dbExecute("UPDATE rental_contracts SET status='signed',activated_at=NULL WHERE id=:id",['id'=>$ctx['contract']]);$hiddenContract=$request($url.'?lang=en',$manager);$assert(!str_contains($hiddenContract['body'],'name="action" value="rental_checkin"'),'Form rendered for inactive contract');dbExecute("UPDATE rental_contracts SET status='active',activated_at=DATE_SUB(NOW(6),INTERVAL 4 MINUTE) WHERE id=:id",['id'=>$ctx['contract']]);
    $source=(string)file_get_contents($root.'/backoffice/inspections.php');foreach(inspectionPhotoSlots()as$slot)$assert(str_contains($source,"SUM(ip.photo_slot='$slot')=1"),'UI query lacks exact '.$slot.' proof');$assert(substr_count($source,'ip.agency_id=vi.agency_id')>=2,'UI photo subqueries are not agency scoped');$assert(!preg_match('/name="(?:reservation_id|contract_id|vehicle_id|customer_id)"/',$source),'Check-in form exposes authoritative IDs');
    foreach(['en'=>'Complete vehicle return','fr'=>'Finaliser le retour du véhicule','ar'=>'إتمام إرجاع المركبة']as$lang=>$label){$localized=$request($url.'?lang='.$lang,$manager);$assert(str_contains($localized['body'],$label)&&str_contains($localized['body'],'lang="'.$lang.'"'),'Missing rendered '.$lang.' check-in action');if($lang==='ar')$assert(str_contains($localized['body'],'dir="rtl"')&&str_contains($localized['body'],'<bdi class="bidi-value reference-value">')&&str_contains($localized['body'],'<bdi class="bidi-value registration-value">'),'Arabic RTL/bidi isolation missing');}
    $managerPost=$post+['_csrf'=>$csrf,'reservation_id'=>'999999','contract_id'=>'999999','vehicle_id'=>'999999','customer_id'=>'999999'];$managerResult=$request($url,$manager,'POST',$managerPost);$assert(str_contains($managerResult['status'],'302')&&p5b4State($ctx)['reservation_status']==='completed','Manager check-in or forged-ID ignoring failed');$replay=$request($url,$manager,'POST',$managerPost);$assert(str_contains($replay['status'],'302')&&(int)dbFetchOne("SELECT COUNT(*) n FROM audit_logs WHERE entity_id=:id AND action='rental.checkin'",['id'=>$ctx['reservation']])['n']===1,'HTTP replay duplicated mutation');
    $agentPost=['action'=>'rental_checkin','inspection_id'=>(string)$agentCtx['inspection'],'idempotency_key'=>phase5bToken(),'mileage'=>'150','fuel_level'=>'40.00','returned_at'=>(new DateTimeImmutable('now'))->format('Y-m-d H:i:s'),'vehicle_condition'=>'dirty','comment'=>'agent return','_csrf'=>$agentCsrf];$agentResult=$request($url,$agent,'POST',$agentPost);$assert(str_contains($agentResult['status'],'302')&&p5b4State($agentCtx)['reservation_status']==='completed','Rental-agent check-in failed');
    foreach(['page'=>$page,'anonymous'=>$anonymous,'missing_csrf'=>$missing,'invalid_csrf'=>$invalid,'safe_domain'=>$safeDomain,'accountant'=>$accountantResult,'fleet'=>$fleetResult,'customer'=>$customerResult,'no_agency'=>$noAgencyResult,'inactive_manager'=>$inactiveM,'inactive_agent'=>$inactiveA,'foreign'=>$foreignResult,'manager_success'=>$managerResult,'replay'=>$replay,'agent_success'=>$agentResult]as$case=>$response){$leak=preg_match('/SQLSTATE|PDOException|SELECT\s+.+\s+FROM|INSERT\s+INTO|UPDATE\s+.+\s+SET|stack trace|[A-Z]:\\\\|inspection-photo-private|session[_ ]?id|csrf token|idempotency key|payload_hash|key_hash|P5B4_INTERNAL/i',$response['body']??'',$match);$assert(!$leak,'HTTP response leaked sensitive data in '.$case.': '.($match[0]??''));}
}catch(Throwable$e){$fail[]='HTTP Phase 5B.4 failure at '.$e->getFile().':'.$e->getLine().': '.$e->getMessage();}
finally{if(is_resource($process)){proc_terminate($process);proc_close($process);}foreach($logs as$file)if($file&&is_file($file))unlink($file);p5b4RemoveFiles($files);foreach(array_reverse($fixtures)as$fixture){@rmdir(inspectionPhotoRoot().'/final/'.(int)$fixture['agency_id']);try{phase5bCleanup($fixture);}catch(Throwable$e){$fail[]='HTTP cleanup failed: '.$e->getMessage();}}}
$inventoryAfter=p5b4Inventory();$new=array_values(array_diff($inventoryAfter,$inventoryBefore));$residue=['agencies'=>(int)dbFetchOne("SELECT COUNT(*) n FROM agencies WHERE name LIKE 'P5B4HTTP%'",[])['n'],'reservations'=>(int)dbFetchOne("SELECT COUNT(*) n FROM reservations WHERE reference LIKE 'P5B4HTTP%'",[])['n'],'contracts'=>(int)dbFetchOne("SELECT COUNT(*) n FROM rental_contracts rc JOIN reservations r ON r.id=rc.reservation_id WHERE r.reference LIKE 'P5B4HTTP%'",[])['n'],'inspections'=>(int)dbFetchOne("SELECT COUNT(*) n FROM vehicle_inspections vi JOIN reservations r ON r.id=vi.reservation_id WHERE r.reference LIKE 'P5B4HTTP%'",[])['n'],'photos'=>(int)dbFetchOne("SELECT COUNT(*) n FROM inspection_photos ip JOIN vehicle_inspections vi ON vi.id=ip.inspection_id JOIN reservations r ON r.id=vi.reservation_id WHERE r.reference LIKE 'P5B4HTTP%'",[])['n'],'in_progress'=>(int)dbFetchOne("SELECT COUNT(*) n FROM rental_operation_idempotency_keys WHERE operation_type='rental_checkin' AND status='in_progress'",[])['n']];$assert(count($new)===0,'HTTP test introduced runtime entries: '.implode(',',$new));foreach($residue as$name=>$count)$assert($count===0,'HTTP residue '.$name.'='.$count);if($fail){foreach(array_unique($fail)as$message)fwrite(STDERR,"FAIL: $message\n");exit(1);}echo 'Phase 5B.4 HTTP cleanup counts: before='.count($inventoryBefore).', after='.count($inventoryAfter).', new='.count($new).', agencies='.$residue['agencies'].', reservations='.$residue['reservations'].', contracts='.$residue['contracts'].', inspections='.$residue['inspections'].', photos='.$residue['photos'].', in_progress='.$residue['in_progress'].".\n";echo "Phase 5B.4 HTTP/security tests passed: auth, CSRF, PRG, role/account scope, strict IDs, forged-input resistance, exact UI eligibility, EN/FR/AR RTL, replay, unexpected-error handling, and disclosure safety.\n";
