<?php
if(PHP_SAPI!=='cli')exit(1);
define('INSPECTION_PHOTO_TEST_HOOK',true);
require_once __DIR__.'/../app/application.php';
require_once __DIR__.'/helpers/phase5b_fixture.php';
require_once __DIR__.'/helpers/phase5b6_catalogue.php';
require_once __DIR__.'/helpers/vehicle_damage_phase5c1_fixture.php';

$failures=[];$assert=static function(bool $condition,string $message)use(&$failures):void{if(!$condition)$failures[]=$message;};$run='P5C1HTTP_'.strtoupper(bin2hex(random_bytes(4)));$fixtures=[];$temporaryFiles=[];$sessionFiles=[];$logs=[];$server=null;$responses=[];$tokens=[];$runtimeBefore=p5b6RuntimeInventory();$controllerLog='';

try{
    $main=phase5bFixture($run.'_MAIN');$fixtures[]=$main;$foreign=phase5bFixture($run.'_FOREIGN');$fixtures[]=$foreign;$stale=phase5bFixture($run.'_STALE');$fixtures[]=$stale;
    $context=p5c1Eligible($main,'MAIN',$temporaryFiles);$foreignContext=p5c1Eligible($foreign,'FOREIGN',$temporaryFiles);$staleContext=p5c1Eligible($stale,'STALE',$temporaryFiles);
    phase5bAs($foreign,ROLE_AGENCY_MANAGER);$foreignDamage=vehicleDamageCreate(p5c1Command($foreignContext));phase5bAs($main,ROLE_AGENCY_MANAGER);
    foreach([
        'manager'=>[$main['users'][ROLE_AGENCY_MANAGER],ROLE_AGENCY_MANAGER,[$main['agency_id']]],'fleet'=>[$main['users'][ROLE_FLEET_AGENT],ROLE_FLEET_AGENT,[$main['agency_id']]],'owner'=>[$main['users'][ROLE_OWNER],ROLE_OWNER,[]],
        'rental'=>[$main['users'][ROLE_RENTAL_AGENT],ROLE_RENTAL_AGENT,[$main['agency_id']]],'accountant'=>[$main['users'][ROLE_ACCOUNTANT],ROLE_ACCOUNTANT,[$main['agency_id']]],'customer'=>[$main['users'][ROLE_RENTAL_AGENT],ROLE_CUSTOMER,[$main['agency_id']]],'no_agency'=>[$main['users'][ROLE_AGENCY_MANAGER],ROLE_AGENCY_MANAGER,[]],
    ]as$name=>$identity){[$sessions[$name],$csrf[$name],$sessionFiles[]]=p5b6Session($identity[0],$identity[1],$identity[2],'p5c1');}
    [$inactiveSession,$inactiveCsrf,$sessionFiles[]]=p5b6Session($main['users'][ROLE_AGENCY_MANAGER],ROLE_AGENCY_MANAGER,[$main['agency_id']],'p5c1');

    $commandFile=tempnam(dirname(__DIR__).'/storage','p5c1-controller-');$logFile=tempnam(dirname(__DIR__).'/storage','p5c1-controller-log-');$outFile=tempnam(dirname(__DIR__).'/storage','p5c1-controller-out-');$tokens[]=phase5bToken();file_put_contents($commandFile,json_encode(['session'=>$sessions['manager'],'csrf'=>$csrf['manager'],'inspection_id'=>$context['return_inspection'],'idempotency_key'=>$tokens[array_key_last($tokens)]]));
    $controller=proc_open([PHP_BINARY,'-d','session.save_path='.dirname(__DIR__).'/storage',__DIR__.'/helpers/vehicle_damage_phase5c1_controller_error.php',$commandFile],[['pipe','r'],['file',$outFile,'a'],['file',$logFile,'a']],$pipes,dirname(__DIR__));if(is_resource($controller)){fclose($pipes[0]);proc_close($controller);}$controllerLog=(string)file_get_contents($logFile);foreach([$commandFile,$logFile,$outFile]as$file)if(is_file($file))unlink($file);
    $assert(str_contains($controllerLog,'RuntimeException')&&!preg_match('/P5C1_INTERNAL|SQLSTATE|PDOException|[A-Z]:\\\\|inspection-photo-private|payload_hash|key_hash|stack trace/i',$controllerLog),'Controller error log disclosed internal data');

    $socket=stream_socket_server('tcp://127.0.0.1:0',$errno,$error);if(!$socket)throw new RuntimeException($error);$name=(string)stream_socket_get_name($socket,false);fclose($socket);$port=(int)substr(strrchr($name,':'),1);$root=dirname(__DIR__);$logs=[tempnam($root.'/storage','p5c1-http-out-'),tempnam($root.'/storage','p5c1-http-err-')];
    $server=proc_open([PHP_BINARY,'-d','session.save_path='.$root.'/storage','-S','127.0.0.1:'.$port,'dev_router.php'],[['pipe','r'],['file',$logs[0],'a'],['file',$logs[1],'a']],$pipes,$root);if(!is_resource($server))throw new RuntimeException('Phase 5C.1 HTTP server did not start');fclose($pipes[0]);$base='http://127.0.0.1:'.$port;$url=$base.'/backoffice/incidents.php';$inspectionUrl=$base.'/backoffice/inspections.php';
    $ready=false;for($attempt=0;$attempt<30;$attempt++){$probe=p5b6HttpRequest($url.'?lang=en',$sessions['manager']);if($probe['body']!==''){$ready=true;break;}usleep(100000);}if(!$ready)throw new RuntimeException('Phase 5C.1 HTTP server did not become ready');
    $responses['manager_page']=$probe;$assert(p5b6Status($probe,200)&&str_contains($probe['body'],htmlspecialchars((string)translationCatalogue('en')['section.vehicle_damage_cases'],ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')),'Authorized damage page failed');$assert(str_contains($probe['body'],t('message.vehicle_damage_failed'))&&!str_contains($probe['body'],'P5C1_INTERNAL'),'Generic controller failure flash was not safe');
    $anonymous=p5b6HttpRequest($url);$responses['anonymous']=$anonymous;$assert(p5b6Status($anonymous,302)||p5b6Status($anonymous,403),'Anonymous damage page access was not denied');
    foreach(['manager','fleet','owner']as$role){$response=p5b6HttpRequest($url,$sessions[$role]);$responses['authorized_'.$role]=$response;$assert(p5b6Status($response,200),$role.' could not view damage page');}
    foreach(['rental','accountant','customer']as$role){$response=p5b6HttpRequest($url,$sessions[$role]);$responses['denied_'.$role]=$response;$assert(p5b6Status($response,403)||p5b6Status($response,302),$role.' viewed damage page');}
    dbExecute("UPDATE users SET status='inactive' WHERE id=:id",['id'=>$main['users'][ROLE_AGENCY_MANAGER]]);$inactive=p5b6HttpRequest($url,$inactiveSession);$responses['inactive']=$inactive;$assert(p5b6Status($inactive,302)||p5b6Status($inactive,403),'Inactive user was not denied');dbExecute("UPDATE users SET status='active' WHERE id=:id",['id'=>$main['users'][ROLE_AGENCY_MANAGER]]);
    $noAgency=p5b6HttpRequest($url,$sessions['no_agency']);$responses['no_agency']=$noAgency;$assert(p5b6Status($noAgency,200)&&!str_contains($noAgency['body'],$main['run'])&&!str_contains($noAgency['body'],$foreign['run']),'No-agency page disclosed damage data');
    $foreignGet=p5b6HttpRequest($url.'?vehicle_id='.$foreignContext['vehicle'],$sessions['manager']);$responses['foreign_get']=$foreignGet;$assert(p5b6Status($foreignGet,200)&&!str_contains($foreignGet['body'],$foreign['run']),'Foreign GET disclosed damage data');
    foreach(['abc','0','-1','1.5','%20'.$context['vehicle'].'%20','999999999999999999999999999999','%5Bx%5D']as$bad){$malformed=p5b6HttpRequest($url.'?vehicle_id='.$bad,$sessions['manager']);$responses['malformed_get_'.$bad]=$malformed;$assert(p5b6Status($malformed,404),'Malformed vehicle filter was accepted: '.$bad);}
    $beforeGet=(int)dbFetchOne('SELECT COUNT(*) n FROM vehicle_damages WHERE inspection_id=:id',['id'=>$context['return_inspection']])['n'];p5b6HttpRequest($url.'?action=vehicle_damage_create&inspection_id='.$context['return_inspection'],$sessions['manager']);$assert((int)dbFetchOne('SELECT COUNT(*) n FROM vehicle_damages WHERE inspection_id=:id',['id'=>$context['return_inspection']])['n']===$beforeGet,'GET mutated damage lifecycle');

    $tokens[]=phase5bToken();$post=['action'=>'vehicle_damage_create','inspection_id'=>(string)$context['return_inspection'],'zone'=>'right & rear','damage_type'=>'dent "scratch"','description'=>'Dent & "paint" damage','severity'=>'moderate','idempotency_key'=>$tokens[array_key_last($tokens)]];
    $missing=p5b6HttpRequest($url,$sessions['manager'],'POST',$post);$invalid=p5b6HttpRequest($url,$sessions['manager'],'POST',$post+['_csrf'=>'invalid']);$responses['missing_csrf']=$missing;$responses['invalid_csrf']=$invalid;$assert(p5b6Status($missing,419)&&p5b6Status($invalid,419),'Creation CSRF failures were accepted');
    foreach([['x'=>1],'abc','0','-1','1.5',' '.$context['return_inspection'].' ','999999999999999999999999999999']as$bad){$tokens[]=phase5bToken();$crafted=$post;$crafted['inspection_id']=$bad;$crafted['idempotency_key']=$tokens[array_key_last($tokens)];$crafted['_csrf']=$csrf['manager'];$response=p5b6HttpRequest($url,$sessions['manager'],'POST',$crafted);$responses[]=$response;$assert(p5b6Status($response,302)&&(int)dbFetchOne('SELECT COUNT(*) n FROM vehicle_damages WHERE inspection_id=:id',['id'=>$context['return_inspection']])['n']===0,'Malformed inspection POST mutated damage');}
    $tokens[]=phase5bToken();$foreignPost=$post;$foreignPost['inspection_id']=(string)$foreignContext['return_inspection'];$foreignPost['idempotency_key']=$tokens[array_key_last($tokens)];$foreignPost['_csrf']=$csrf['manager'];$response=p5b6HttpRequest($url,$sessions['manager'],'POST',$foreignPost);$responses['foreign_post']=$response;$assert(p5b6Status($response,302)&&(int)dbFetchOne('SELECT COUNT(*) n FROM vehicle_damages WHERE inspection_id=:id',['id'=>$foreignContext['return_inspection']])['n']===1,'Foreign POST changed damage data');
    $noAgencyPost=$post;$noAgencyPost['_csrf']=$csrf['no_agency'];$response=p5b6HttpRequest($url,$sessions['no_agency'],'POST',$noAgencyPost);$responses['no_agency_post']=$response;$assert(p5b6Status($response,302)&&(int)dbFetchOne('SELECT COUNT(*) n FROM vehicle_damages WHERE inspection_id=:id',['id'=>$context['return_inspection']])['n']===0,'No-agency POST created damage');
    $tokens[]=phase5bToken();$valid=$post;$valid['idempotency_key']=$tokens[array_key_last($tokens)];$valid+=['_csrf'=>$csrf['manager'],'agency_id'=>$foreign['agency_id'],'actor_id'=>999999,'role'=>ROLE_OWNER,'vehicle_id'=>$foreignContext['vehicle'],'reservation_id'=>$foreignContext['reservation'],'contract_id'=>$foreignContext['contract'],'customer_id'=>$foreignContext['customer'],'status'=>'resolved','discovered_at'=>'2999-01-01 00:00:00'];$validResponse=p5b6HttpRequest($url,$sessions['manager'],'POST',$valid);$responses['valid_create']=$validResponse;$assert(p5b6Status($validResponse,302),'Valid HTTP creation did not PRG');$damage=dbFetchOne('SELECT * FROM vehicle_damages WHERE inspection_id=:id',['id'=>$context['return_inspection']]);$assert($damage&&(int)$damage['vehicle_id']===$context['vehicle']&&(int)$damage['created_by']===$main['users'][ROLE_AGENCY_MANAGER]&&$damage['status']==='open','Forged authoritative creation fields were trusted');
    $replay=p5b6HttpRequest($url,$sessions['manager'],'POST',$valid);$responses['create_replay']=$replay;$assert(p5b6Status($replay,302)&&(int)dbFetchOne('SELECT COUNT(*) n FROM vehicle_damages WHERE inspection_id=:id',['id'=>$context['return_inspection']])['n']===1,'Creation replay duplicated damage');
    $tokens[]=phase5bToken();$duplicate=$post;$duplicate['idempotency_key']=$tokens[array_key_last($tokens)];$duplicate['_csrf']=$csrf['manager'];$duplicateResponse=p5b6HttpRequest($url,$sessions['manager'],'POST',$duplicate);$responses['duplicate_source']=$duplicateResponse;$assert(p5b6Status($duplicateResponse,302)&&(int)dbFetchOne('SELECT COUNT(*) n FROM vehicle_damages WHERE inspection_id=:id',['id'=>$context['return_inspection']])['n']===1,'Duplicate source created damage');
    dbExecute("UPDATE vehicles SET status='available' WHERE id=:id",['id'=>$staleContext['vehicle']]);$tokens[]=phase5bToken();$stalePost=$post;$stalePost['inspection_id']=(string)$staleContext['return_inspection'];$stalePost['idempotency_key']=$tokens[array_key_last($tokens)];$stalePost['_csrf']=$csrf['manager'];$staleResponse=p5b6HttpRequest($url,$sessions['manager'],'POST',$stalePost);$responses['stale_source']=$staleResponse;$assert(p5b6Status($staleResponse,302)&&(int)dbFetchOne('SELECT COUNT(*) n FROM vehicle_damages WHERE inspection_id=:id',['id'=>$staleContext['return_inspection']])['n']===0,'Stale source created damage');

    $page=p5b6HttpRequest($url.'?lang=en',$sessions['manager']);$responses['escaped_page']=$page;$assert(str_contains($page['body'],'right &amp; rear')&&str_contains($page['body'],'dent &quot;scratch&quot;')&&str_contains($page['body'],'Dent &amp; &quot;paint&quot; damage'),'Damage output was not escaped');$assert(!str_contains($page['body'],'inspection-photo-private'),'Damage page exposed protected storage');
    $inspectionPage=p5b6HttpRequest($inspectionUrl.'?lang=en',$sessions['manager']);$responses['inspection_ui']=$inspectionPage;$needle='name="inspection_id" value="'.$context['return_inspection'].'"';$assert(!str_contains($inspectionPage['body'],$needle)||!str_contains($inspectionPage['body'],'name="action" value="vehicle_damage_create"'),'Duplicate damage action remained eligible');
    foreach(['en'=>'ltr','fr'=>'ltr','ar'=>'rtl']as$language=>$direction){$localized=p5b6HttpRequest($url.'?lang='.$language,$sessions['manager']);$responses['language_'.$language]=$localized;$label=translationCatalogue($language)['section.vehicle_damage_cases'];$assert(p5b6Status($localized,200)&&preg_match('/<html[^>]+lang="'.$language.'"[^>]+dir="'.$direction.'"/i',$localized['body'])===1&&str_contains($localized['body'],htmlspecialchars($label,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8')),$language.' damage page localization failed');if($language==='ar')$assert(str_contains($localized['body'],'<bdi')&&str_contains($localized['body'],$main['run']),'Arabic damage page lacks isolated identifiers');}

    $tokens[]=phase5bToken();$resolve=['action'=>'vehicle_damage_resolve','damage_id'=>(string)$damage['id'],'reason'=>'Verified body repair','idempotency_key'=>$tokens[array_key_last($tokens)]];$missingResolve=p5b6HttpRequest($url,$sessions['manager'],'POST',$resolve);$invalidResolve=p5b6HttpRequest($url,$sessions['manager'],'POST',$resolve+['_csrf'=>'invalid']);$responses['resolve_missing_csrf']=$missingResolve;$responses['resolve_invalid_csrf']=$invalidResolve;$assert(p5b6Status($missingResolve,419)&&p5b6Status($invalidResolve,419),'Resolution CSRF failures were accepted');
    foreach([['x'=>1],'abc','0','-1','1.5',' '.$damage['id'].' ','999999999999999999999999999999']as$bad){$tokens[]=phase5bToken();$crafted=$resolve;$crafted['damage_id']=$bad;$crafted['idempotency_key']=$tokens[array_key_last($tokens)];$crafted['_csrf']=$csrf['manager'];$response=p5b6HttpRequest($url,$sessions['manager'],'POST',$crafted);$responses[]=$response;$assert(p5b6Status($response,302)&&dbFetchOne('SELECT status FROM vehicle_damages WHERE id=:id',['id'=>$damage['id']])['status']==='open','Malformed resolution ID mutated damage');}
    $tokens[]=phase5bToken();$foreignResolve=$resolve;$foreignResolve['damage_id']=(string)$foreignDamage;$foreignResolve['idempotency_key']=$tokens[array_key_last($tokens)];$foreignResolve['_csrf']=$csrf['manager'];$response=p5b6HttpRequest($url,$sessions['manager'],'POST',$foreignResolve);$responses['foreign_resolve']=$response;$assert(p5b6Status($response,302)&&dbFetchOne('SELECT status FROM vehicle_damages WHERE id=:id',['id'=>$foreignDamage])['status']==='open','Foreign damage was resolved');
    $validResolve=$resolve+['_csrf'=>$csrf['manager'],'actor_id'=>999999,'agency_id'=>$foreign['agency_id'],'vehicle_id'=>$foreignContext['vehicle'],'status'=>'open'];$resolveResponse=p5b6HttpRequest($url,$sessions['manager'],'POST',$validResolve);$responses['valid_resolve']=$resolveResponse;$assert(p5b6Status($resolveResponse,302)&&dbFetchOne('SELECT status FROM vehicle_damages WHERE id=:id',['id'=>$damage['id']])['status']==='resolved'&&dbFetchOne('SELECT status FROM vehicles WHERE id=:id',['id'=>$context['vehicle']])['status']==='damaged','Valid resolution or vehicle non-effect failed');$resolveReplay=p5b6HttpRequest($url,$sessions['manager'],'POST',$validResolve);$responses['resolve_replay']=$resolveReplay;$assert(p5b6Status($resolveReplay,302)&&(int)dbFetchOne("SELECT COUNT(*) n FROM audit_logs WHERE agency_id=:agency AND action='vehicle_damage.resolved' AND entity_id=:id",['agency'=>$main['agency_id'],'id'=>$damage['id']])['n']===1,'Resolution replay duplicated audit');

    $pattern='/SQLSTATE|PDOException|SELECT\s+.+\s+FROM|INSERT\s+INTO|UPDATE\s+.+\s+SET|stack trace|[A-Z]:\\\\[^\r\n<]+|\/(?:var|home|srv|tmp)\/[^\r\n<]+|inspection-photo-private|payload_hash|key_hash|P5C1_INTERNAL/i';foreach($responses as$case=>$response){$assert(!preg_match($pattern,$response['body']??''),'HTTP disclosure in '.(string)$case);foreach($tokens as$token)$assert(!str_contains($response['body']??'',$token),'HTTP response disclosed an idempotency key');if(!p5b6Status($response,200))$assert(!str_contains($response['body']??'',$csrf['manager']),'HTTP error response disclosed CSRF token');}
}catch(Throwable$exception){$failures[]='Unexpected HTTP '.get_class($exception).' at '.$exception->getFile().':'.$exception->getLine().': '.$exception->getMessage();}
finally{
    if(is_resource($server)){proc_terminate($server);proc_close($server);}foreach($logs as$file){if($file&&is_file($file)){if(preg_match('/SQLSTATE|PDOException|P5C1_INTERNAL|stack trace|payload_hash|key_hash|inspection-photo-private/i',(string)file_get_contents($file)))$failures[]='HTTP server log disclosed internal data';unlink($file);}}
    foreach($sessionFiles as$file)if(is_string($file)&&is_file($file))unlink($file);p5c1Cleanup($fixtures,$temporaryFiles);$runtimeAfter=p5b6RuntimeInventory();$residue=['agencies'=>(int)dbFetchOne('SELECT COUNT(*) n FROM agencies WHERE name LIKE :run',['run'=>$run.'%'])['n'],'damages'=>(int)dbFetchOne("SELECT COUNT(*) n FROM audit_logs WHERE action IN('vehicle_damage.created','vehicle_damage.resolved') AND after_json LIKE :run",['run'=>'%'.$run.'%'])['n'],'in_progress'=>(int)dbFetchOne("SELECT COUNT(*) n FROM rental_operation_idempotency_keys WHERE operation_type IN('vehicle_damage_create','vehicle_damage_resolve') AND status='in_progress'")['n']];$assert($runtimeAfter===$runtimeBefore,'HTTP suite left controlled runtime files');foreach($residue as$name=>$count)$assert($count===0,'HTTP cleanup residue '.$name.'='.$count);
}
if($failures){fwrite(STDERR,"Phase 5C.1 HTTP failures:\n- ".implode("\n- ",array_unique($failures))."\n");exit(1);}
echo 'Phase 5C.1 HTTP cleanup: runtime_before='.count($runtimeBefore).', runtime_after='.count($runtimeAfter).', sessions='.count($sessionFiles).', logs='.count($logs).', db='.json_encode($residue).".\n";
echo "Phase 5C.1 HTTP/security tests passed: authentication, RBAC, agency IDOR, strict IDs, CSRF, PRG, forged fields, stale/duplicate sources, creation/resolution replay, protected evidence, EN/FR/AR RTL, escaping, disclosure, logs, and cleanup.\n";
