<?php
if(PHP_SAPI!=='cli')exit(1);
define('INSPECTION_PHOTO_TEST_HOOK',true);
define('VEHICLE_DAMAGE_TEST_HOOK',true);
require_once __DIR__.'/../app/application.php';
require_once __DIR__.'/helpers/phase5b_fixture.php';
require_once __DIR__.'/helpers/phase5b6_catalogue.php';
require_once __DIR__.'/helpers/vehicle_damage_phase5c1_fixture.php';

$GLOBALS['p5c1_fault']=null;
function vehicleDamageCliTestHook(string $operation,string $stage,array $context=[]): void { if($GLOBALS['p5c1_fault']===[$operation,$stage])throw new RuntimeException('Injected Phase 5C.1 '.$operation.' failure at '.$stage); }

$failures=[];$assert=static function(bool $condition,string $message)use(&$failures):void{if(!$condition)$failures[]=$message;};
$rejects=static function(callable $callback,string $message)use($assert):void{$rejected=false;try{$callback();}catch(InvalidArgumentException|DomainException|AuthorizationException|RuntimeException){$rejected=true;}$assert($rejected,$message);};
$run='P5C1_'.strtoupper(bin2hex(random_bytes(4)));$fixtures=[];$temporaryFiles=[];$runtimeBefore=p5b6RuntimeInventory();$concurrency=[];$financeEvidence=[];$laterEvidence=[];

try{
    $columns=array_column(dbFetchAll("SELECT COLUMN_NAME FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=SCHEMA() AND TABLE_NAME='vehicle_damages' ORDER BY ORDINAL_POSITION"),'COLUMN_NAME');
    $assert($columns===['id','inspection_id','vehicle_id','zone','damage_type','description','severity','estimated_cost','final_cost','responsible_party','payment_status','status','created_at','created_by','resolved_at'],'Committed vehicle_damages schema changed');
    $assert(!dbFetchOne("SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=SCHEMA() AND TABLE_NAME='vehicle_damages' AND COLUMN_NAME IN('agency_id','reservation_id','contract_id','customer_id','discovered_at','resolution_reason')"),'Unsupported vehicle_damages columns appeared');
    $expectedRoles=[ROLE_OWNER,ROLE_AGENCY_MANAGER,ROLE_FLEET_AGENT];
    foreach([ROLE_OWNER,ROLE_AGENCY_MANAGER,ROLE_RENTAL_AGENT,ROLE_ACCOUNTANT,ROLE_FLEET_AGENT,ROLE_CUSTOMER]as$role){$_SESSION=['user_id'=>1,'role'=>$role,'agency_ids'=>[],'_authenticated_at'=>time()];foreach(['vehicle_damages.view','vehicle_damages.create','vehicle_damages.resolve']as$permission)$assert(can($permission)===in_array($role,$expectedRoles,true),$role.' permission mismatch for '.$permission);}

    $translationKeys=['section.vehicle_damage_cases','section.record_vehicle_damage','field.damage_source','field.resolution_reason','action.create_vehicle_damage','action.resolve_vehicle_damage','confirm.resolve_vehicle_damage','empty.no_vehicle_damage_cases','message.vehicle_damage_created','message.vehicle_damage_resolved','message.vehicle_damage_failed','message.vehicle_damage_source_help','validation.vehicle_damage_not_found','validation.vehicle_damage_source','validation.vehicle_damage_vehicle','validation.vehicle_damage_duplicate','validation.vehicle_damage_zone','validation.vehicle_damage_type','validation.vehicle_damage_description','validation.vehicle_damage_severity','validation.vehicle_damage_time','validation.vehicle_damage_resolution','validation.vehicle_damage_stale','audit.vehicle_damage.created','audit.vehicle_damage.resolved'];
    $translationEvidence=[];foreach(['en','fr','ar']as$language){$catalogue=translationCatalogue($language);foreach($translationKeys as$key){$value=$catalogue[$key]??'';$assert(is_string($value)&&trim($value)!=='',$language.' missing '.$key);$assert(mb_check_encoding($value,'UTF-8'),$language.' invalid UTF-8 for '.$key);$assert(p5b6Placeholders($value)===p5b6Placeholders((string)(translationCatalogue('en')[$key]??'')),$language.' placeholder mismatch for '.$key);}$translationEvidence[$language]=count($translationKeys);}

    $main=phase5bFixture($run.'_MAIN');$fixtures[]=$main;$context=p5c1Eligible($main,'MAIN',$temporaryFiles);phase5bAs($main,ROLE_AGENCY_MANAGER);
    $inspectionBefore=dbFetchOne('SELECT * FROM vehicle_inspections WHERE id=:id',['id'=>$context['return_inspection']]);$photosBefore=p5c1PhotoEvidence($context['return_inspection']);$financeEvidence['before']=p5c1FinanceCounters($main,$context);$laterEvidence['before']=p5c1LaterPhaseCounters($context);$key=phase5bToken();$command=p5c1Command($context,$key);
    $damageId=vehicleDamageCreate($command);$assert($damageId>0,'Eligible damage creation failed');$row=dbFetchOne('SELECT * FROM vehicle_damages WHERE id=:id',['id'=>$damageId]);
    $assert((int)$row['inspection_id']===$context['return_inspection']&&(int)$row['vehicle_id']===$context['vehicle'],'Damage did not use authoritative inspection/vehicle');
    $assert($row['zone']===$command['zone']&&$row['damage_type']===$command['damage_type']&&$row['description']===$command['description']&&$row['severity']==='moderate','Damage business fields mismatch');
    $assert($row['status']==='open'&&$row['payment_status']==='pending'&&$row['estimated_cost']==='0.00'&&$row['final_cost']===null&&$row['resolved_at']===null,'Damage creation defaults mismatch');
    $assert((int)$row['created_by']===$main['users'][ROLE_AGENCY_MANAGER],'Damage reporting actor was not authoritative');
    $assert(vehicleDamageCreate($command)===$damageId,'Same-key creation replay did not return same result');
    $changed=$command;$changed['description']='Changed replay payload';$rejects(fn()=>vehicleDamageCreate($changed),'Changed-payload replay was accepted');
    $duplicate=$command;$duplicate['idempotency_key']=phase5bToken();$rejects(fn()=>vehicleDamageCreate($duplicate),'Duplicate inspection source was accepted');
    $assert((int)dbFetchOne('SELECT COUNT(*) n FROM vehicle_damages WHERE inspection_id=:inspection',['inspection'=>$context['return_inspection']])['n']===1,'Duplicate damage row created');
    $assert((int)dbFetchOne("SELECT COUNT(*) n FROM audit_logs WHERE agency_id=:agency AND action='vehicle_damage.created' AND entity_id=:id",['agency'=>$main['agency_id'],'id'=>$damageId])['n']===1,'Creation audit count mismatch');
    $assert(dbFetchOne('SELECT * FROM vehicle_inspections WHERE id=:id',['id'=>$context['return_inspection']])===$inspectionBefore,'Source inspection was mutated');
    $assert(p5c1PhotoEvidence($context['return_inspection'])===$photosBefore,'Protected photo metadata was mutated');
    foreach($photosBefore as$photo){$path=inspectionPhotoPath($photo['storage_path']);$assert($path&&is_file($path)&&hash_equals($photo['sha256'],hash_file('sha256',$path)),'Protected photo evidence changed');}
    $assert(dbFetchOne('SELECT status FROM vehicles WHERE id=:id',['id'=>$context['vehicle']])['status']==='damaged','Vehicle did not remain damaged');

    $resolveKey=phase5bToken();$resolve=['damage_id'=>$damageId,'reason'=>'Body repair was verified outside this workflow.','idempotency_key'=>$resolveKey];$assert(vehicleDamageResolve($resolve)===$damageId,'Resolution failed');$assert(vehicleDamageResolve($resolve)===$damageId,'Resolution replay failed');
    $resolved=dbFetchOne('SELECT status,resolved_at FROM vehicle_damages WHERE id=:id',['id'=>$damageId]);$assert($resolved['status']==='resolved'&&$resolved['resolved_at']!==null,'Resolution state mismatch');
    $assert((int)dbFetchOne("SELECT COUNT(*) n FROM audit_logs WHERE agency_id=:agency AND action='vehicle_damage.resolved' AND entity_id=:id",['agency'=>$main['agency_id'],'id'=>$damageId])['n']===1,'Resolution audit count mismatch');
    $assert(dbFetchOne('SELECT status FROM vehicles WHERE id=:id',['id'=>$context['vehicle']])['status']==='damaged','Resolution changed vehicle state');
    $financeEvidence['after']=p5c1FinanceCounters($main,$context);$laterEvidence['after']=p5c1LaterPhaseCounters($context);$assert($financeEvidence['after']===$financeEvidence['before'],'Damage lifecycle changed finance tables');$assert($laterEvidence['after']===$laterEvidence['before'],'Damage lifecycle created a later-phase record');

    phase5bAs($main,ROLE_AGENCY_MANAGER);foreach([[], 'abc','0','-1','1.5',' '.$context['return_inspection'].' ','999999999999999999999999999999']as$bad){$candidate=p5c1Command($context);$candidate['inspection_id']=$bad;$rejects(fn()=>vehicleDamageCreate($candidate),'Malformed inspection ID accepted');$candidate=p5c1Command($context);$candidate['vehicle_id']=$bad;$rejects(fn()=>vehicleDamageCreate($candidate),'Malformed vehicle ID accepted');}
    foreach([null,'',[],"<script>alert(1)</script>",str_repeat('x',256)]as$bad){$candidate=p5c1Command($context);$candidate['description']=$bad;$rejects(fn()=>vehicleDamageCreate($candidate),'Invalid description accepted');}
    foreach([null,'',[],"<b>door</b>",str_repeat('x',61)]as$bad){foreach(['zone','damage_type']as$field){$candidate=p5c1Command($context);$candidate[$field]=$bad;$rejects(fn()=>vehicleDamageCreate($candidate),'Invalid '.$field.' accepted');}}
    foreach([null,'',[],'MINOR',' minor','minor ','medium','critical']as$bad){$candidate=p5c1Command($context);$candidate['severity']=$bad;$rejects(fn()=>vehicleDamageCreate($candidate),'Invalid severity accepted');}
    $candidate=p5c1Command($context);$candidate['discovered_at']='not-a-time';$rejects(fn()=>vehicleDamageCreate($candidate),'Submitted discovery timestamp accepted');

    $guard=phase5bFixture($run.'_GUARD');$fixtures[]=$guard;$guardContext=p5c1Eligible($guard,'GUARD',$temporaryFiles);phase5bAs($guard,ROLE_AGENCY_MANAGER);$guardCommand=p5c1Command($guardContext);$returnId=$guardContext['return_inspection'];$returnOriginal=dbFetchOne('SELECT * FROM vehicle_inspections WHERE id=:id',['id'=>$returnId]);
    dbExecute("UPDATE vehicle_inspections SET status='draft',completed_at=NULL,post_return_vehicle_state=NULL,damage_notes=NULL WHERE id=:id",['id'=>$returnId]);$rejects(fn()=>vehicleDamageCreate($guardCommand),'Draft inspection accepted');dbExecute("UPDATE vehicle_inspections SET status='completed',completed_at=:at,post_return_vehicle_state='damaged',damage_notes=:notes WHERE id=:id",['at'=>$returnOriginal['completed_at'],'notes'=>$returnOriginal['damage_notes'],'id'=>$returnId]);
    dbExecute("UPDATE vehicle_inspections SET status='archived',archived_at=NOW(6),archived_by=:actor,archive_reason='test' WHERE id=:id",['actor'=>$guard['users'][ROLE_AGENCY_MANAGER],'id'=>$returnId]);$rejects(fn()=>vehicleDamageCreate($guardCommand),'Archived inspection accepted');dbExecute("UPDATE vehicle_inspections SET status='completed',archived_at=NULL,archived_by=NULL,archive_reason=NULL WHERE id=:id",['id'=>$returnId]);
    $checkoutCommand=$guardCommand;$checkoutCommand['inspection_id']=$guardContext['checkout'];$rejects(fn()=>vehicleDamageCreate($checkoutCommand),'Checkout inspection accepted');
    dbExecute("UPDATE vehicle_inspections SET post_return_vehicle_state='available',damage_notes=NULL WHERE id=:id",['id'=>$returnId]);$rejects(fn()=>vehicleDamageCreate($guardCommand),'Non-damaged return accepted');dbExecute("UPDATE vehicle_inspections SET post_return_vehicle_state='damaged',damage_notes=:notes WHERE id=:id",['notes'=>$returnOriginal['damage_notes'],'id'=>$returnId]);
    foreach(['available','reserved','rented','maintenance']as$status){dbExecute('UPDATE vehicles SET status=:status WHERE id=:id',['status'=>$status,'id'=>$guardContext['vehicle']]);$rejects(fn()=>vehicleDamageCreate($guardCommand),'Vehicle state '.$status.' accepted');}dbExecute("UPDATE vehicles SET status='damaged' WHERE id=:id",['id'=>$guardContext['vehicle']]);
    dbExecute("INSERT INTO vehicles(agency_id,category_id,registration_number,brand,model,status,created_by,updated_by)VALUES(:agency,:category,:registration,'P5C1','Mismatch','damaged',:actor,:actor2)",['agency'=>$guard['agency_id'],'category'=>$guard['category_id'],'registration'=>substr($run.'_MISMATCH',0,40),'actor'=>$guard['users'][ROLE_AGENCY_MANAGER],'actor2'=>$guard['users'][ROLE_AGENCY_MANAGER]]);$mismatchVehicle=(int)db()->lastInsertId();dbExecute('UPDATE vehicle_inspections SET vehicle_id=:vehicle WHERE id=:id',['vehicle'=>$mismatchVehicle,'id'=>$returnId]);$rejects(fn()=>vehicleDamageCreate($guardCommand),'Wrong inspection vehicle accepted');dbExecute('UPDATE vehicle_inspections SET vehicle_id=:vehicle WHERE id=:id',['vehicle'=>$guardContext['vehicle'],'id'=>$returnId]);
    $otherReservation=phase5bCreateReservation($guard,'OTHER','completed');dbExecute('UPDATE vehicle_inspections SET reservation_id=:reservation WHERE id=:id',['reservation'=>$otherReservation,'id'=>$returnId]);$rejects(fn()=>vehicleDamageCreate($guardCommand),'Wrong reservation linkage accepted');dbExecute('UPDATE vehicle_inspections SET reservation_id=:reservation WHERE id=:id',['reservation'=>$guardContext['reservation'],'id'=>$returnId]);
    dbExecute("INSERT INTO rental_contracts(agency_id,reservation_id,contract_number,status,issued_at,signed_at,activated_at,completed_at,created_by,updated_by)VALUES(:agency,:reservation,:number,'completed',DATE_SUB(NOW(6),INTERVAL 4 HOUR),DATE_SUB(NOW(6),INTERVAL 3 HOUR),DATE_SUB(NOW(6),INTERVAL 2 HOUR),DATE_SUB(NOW(6),INTERVAL 1 HOUR),:actor,:actor2)",['agency'=>$guard['agency_id'],'reservation'=>$otherReservation,'number'=>substr($run.'_OTHER',0,50),'actor'=>$guard['users'][ROLE_AGENCY_MANAGER],'actor2'=>$guard['users'][ROLE_AGENCY_MANAGER]]);$otherContract=(int)db()->lastInsertId();dbExecute('UPDATE vehicle_inspections SET contract_id=:contract WHERE id=:id',['contract'=>$otherContract,'id'=>$returnId]);$rejects(fn()=>vehicleDamageCreate($guardCommand),'Wrong contract linkage accepted');dbExecute('UPDATE vehicle_inspections SET contract_id=:contract WHERE id=:id',['contract'=>$guardContext['contract'],'id'=>$returnId]);

    $foreign=phase5bFixture($run.'_FOREIGN');$fixtures[]=$foreign;$foreignContext=p5c1Eligible($foreign,'FOREIGN',$temporaryFiles);phase5bAs($main,ROLE_AGENCY_MANAGER);$rejects(fn()=>vehicleDamageCreate(p5c1Command($foreignContext)),'Foreign inspection accepted');$foreignVehicle=p5c1Command($guardContext);$foreignVehicle['vehicle_id']=$foreignContext['vehicle'];$rejects(fn()=>vehicleDamageCreate($foreignVehicle),'Foreign vehicle hint accepted');

    $rbac=phase5bFixture($run.'_RBAC');$fixtures[]=$rbac;$rbacContext=p5c1Eligible($rbac,'RBAC',$temporaryFiles);foreach([ROLE_RENTAL_AGENT,ROLE_ACCOUNTANT,ROLE_CUSTOMER]as$role){$_SESSION=['user_id'=>$rbac['users'][$role]??$rbac['users'][ROLE_RENTAL_AGENT],'role'=>$role,'agency_ids'=>[$rbac['agency_id']], '_authenticated_at'=>time()];$rejects(fn()=>vehicleDamageCreate(p5c1Command($rbacContext)),$role.' created damage');}
    $_SESSION=['user_id'=>$rbac['users'][ROLE_AGENCY_MANAGER],'role'=>ROLE_AGENCY_MANAGER,'agency_ids'=>[],'_authenticated_at'=>time()];$rejects(fn()=>vehicleDamageCreate(p5c1Command($rbacContext)),'No-agency manager created damage');
    dbExecute("UPDATE users SET status='inactive' WHERE id=:id",['id'=>$rbac['users'][ROLE_AGENCY_MANAGER]]);phase5bAs($rbac,ROLE_AGENCY_MANAGER);$rejects(fn()=>vehicleDamageCreate(p5c1Command($rbacContext)),'Inactive manager created damage');dbExecute("UPDATE users SET status='active' WHERE id=:id",['id'=>$rbac['users'][ROLE_AGENCY_MANAGER]]);
    phase5bAs($rbac,ROLE_FLEET_AGENT);$assert(vehicleDamageCreate(p5c1Command($rbacContext))>0,'Fleet agent could not create damage');
    $owner=phase5bFixture($run.'_OWNER');$fixtures[]=$owner;$ownerContext=p5c1Eligible($owner,'OWNER',$temporaryFiles);phase5bAs($owner,ROLE_OWNER);$assert(vehicleDamageCreate(p5c1Command($ownerContext))>0,'Owner could not create damage');

    $rollback=phase5bFixture($run.'_ROLLBACK');$fixtures[]=$rollback;$rollbackContext=p5c1Eligible($rollback,'ROLLBACK',$temporaryFiles);phase5bAs($rollback,ROLE_AGENCY_MANAGER);$rollbackInspection=dbFetchOne('SELECT * FROM vehicle_inspections WHERE id=:id',['id'=>$rollbackContext['return_inspection']]);$rollbackPhotos=p5c1PhotoEvidence($rollbackContext['return_inspection']);
    foreach(['after_idempotency','after_insert','before_audit','after_audit','before_idempotency_completion','before_commit']as$stage){$GLOBALS['p5c1_fault']=['create',$stage];$rejects(fn()=>vehicleDamageCreate(p5c1Command($rollbackContext)), 'Create rollback hook '.$stage.' did not fail');$GLOBALS['p5c1_fault']=null;$assert((int)dbFetchOne('SELECT COUNT(*) n FROM vehicle_damages WHERE inspection_id=:id',['id'=>$rollbackContext['return_inspection']])['n']===0,'Create rollback left damage at '.$stage);$assert((int)dbFetchOne("SELECT COUNT(*) n FROM audit_logs WHERE agency_id=:agency AND action='vehicle_damage.created'",['agency'=>$rollback['agency_id']])['n']===0,'Create rollback left audit at '.$stage);$assert((int)dbFetchOne("SELECT COUNT(*) n FROM rental_operation_idempotency_keys WHERE origin_agency_id=:agency AND operation_type='vehicle_damage_create'",['agency'=>$rollback['agency_id']])['n']===0,'Create rollback left idempotency at '.$stage);$assert(dbFetchOne('SELECT * FROM vehicle_inspections WHERE id=:id',['id'=>$rollbackContext['return_inspection']])===$rollbackInspection&&p5c1PhotoEvidence($rollbackContext['return_inspection'])===$rollbackPhotos,'Create rollback changed source evidence at '.$stage);}
    $rollbackDamage=vehicleDamageCreate(p5c1Command($rollbackContext));foreach(['after_idempotency','after_update','before_audit','after_audit','before_idempotency_completion','before_commit']as$stage){$GLOBALS['p5c1_fault']=['resolve',$stage];$rejects(fn()=>vehicleDamageResolve(['damage_id'=>$rollbackDamage,'reason'=>'Rollback resolution reason','idempotency_key'=>phase5bToken()]),'Resolve rollback hook '.$stage.' did not fail');$GLOBALS['p5c1_fault']=null;$assert(dbFetchOne('SELECT status,resolved_at FROM vehicle_damages WHERE id=:id',['id'=>$rollbackDamage])===['status'=>'open','resolved_at'=>null],'Resolve rollback changed damage at '.$stage);$assert((int)dbFetchOne("SELECT COUNT(*) n FROM audit_logs WHERE agency_id=:agency AND action='vehicle_damage.resolved'",['agency'=>$rollback['agency_id']])['n']===0,'Resolve rollback left audit at '.$stage);$assert((int)dbFetchOne("SELECT COUNT(*) n FROM rental_operation_idempotency_keys WHERE origin_agency_id=:agency AND operation_type='vehicle_damage_resolve'",['agency'=>$rollback['agency_id']])['n']===0,'Resolve rollback left idempotency at '.$stage);}

    foreach(['same_key','different_key','resolve']as$mode){$fixture=phase5bFixture($run.'_CONC_'.strtoupper($mode));$fixtures[]=$fixture;$ctx=p5c1Eligible($fixture,strtoupper($mode),$temporaryFiles);phase5bAs($fixture,ROLE_AGENCY_MANAGER);$base=['user_id'=>$fixture['users'][ROLE_AGENCY_MANAGER],'role'=>ROLE_AGENCY_MANAGER,'agency_ids'=>[$fixture['agency_id']]];
        if($mode==='resolve'){$id=vehicleDamageCreate(p5c1Command($ctx));$a=['damage_id'=>$id,'reason'=>'Concurrent resolution','idempotency_key'=>phase5bToken()];$b=$a;$b['idempotency_key']=phase5bToken();$results=p5c1Pair(['a'=>$base+['operation'=>'resolve','payload'=>$a],'b'=>$base+['operation'=>'resolve','payload'=>$b]]);$assert(count(array_filter($results,fn($r)=>$r['ok']??false))===1,'Resolution concurrency did not have one winner');$assert((int)dbFetchOne("SELECT COUNT(*) n FROM audit_logs WHERE agency_id=:agency AND action='vehicle_damage.resolved' AND entity_id=:id",['agency'=>$fixture['agency_id'],'id'=>$id])['n']===1,'Resolution concurrency audit mismatch');}
        else{$key=phase5bToken();$a=p5c1Command($ctx,$key);$b=$a;if($mode==='different_key')$b['idempotency_key']=phase5bToken();$results=p5c1Pair(['a'=>$base+['operation'=>'create','payload'=>$a],'b'=>$base+['operation'=>'create','payload'=>$b]]);$winners=count(array_filter($results,fn($r)=>$r['ok']??false));$assert($winners===($mode==='same_key'?2:1),$mode.' concurrency winner count mismatch');$assert((int)dbFetchOne('SELECT COUNT(*) n FROM vehicle_damages WHERE inspection_id=:id',['id'=>$ctx['return_inspection']])['n']===1,$mode.' concurrency created duplicate');$assert((int)dbFetchOne("SELECT COUNT(*) n FROM audit_logs WHERE agency_id=:agency AND action='vehicle_damage.created'",['agency'=>$fixture['agency_id']])['n']===1,$mode.' concurrency audit mismatch');}
        $concurrency[$mode]=$results;
    }
}catch(Throwable$exception){$failures[]='Unexpected '.get_class($exception).': '.$exception->getMessage();}
finally{$GLOBALS['p5c1_fault']=null;p5c1Cleanup($fixtures,$temporaryFiles);$runtimeAfter=p5b6RuntimeInventory();$residue=(int)dbFetchOne('SELECT COUNT(*) n FROM agencies WHERE name LIKE :run',['run'=>$run.'%'])['n'];$assert($runtimeAfter===$runtimeBefore,'Phase 5C.1 left runtime files');$assert($residue===0,'Phase 5C.1 left database fixtures');}

if($failures){fwrite(STDERR,"Phase 5C.1 failures:\n- ".implode("\n- ",$failures)."\n");exit(1);}
echo 'Phase 5C.1 schema: existing vehicle_damages columns='.json_encode($columns).", migration_required=false.\n";
echo 'Phase 5C.1 finance non-effect: '.json_encode($financeEvidence).".\n";
echo 'Phase 5C.1 later-phase non-effect: '.json_encode($laterEvidence).".\n";
echo 'Phase 5C.1 concurrency: '.json_encode($concurrency,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES).".\n";
echo 'Phase 5C.1 cleanup: runtime_before='.count($runtimeBefore).', runtime_after='.count($runtimeAfter).', database_residue='.$residue.".\n";
echo "Phase 5C.1 vehicle-damage tests passed: schema, RBAC, creation, resolution, validation, source guards, idempotency, rollback, true concurrency, protected evidence, non-effects, translations, and cleanup.\n";
