<?php

function createContractFromReservation($reservationId, $languageCode = 'fr')
{
    return withTransaction(function () use ($reservationId, $languageCode) {
        $reservation = dbFetchOne('SELECT r.*,c.first_name,c.last_name,c.identity_number,c.licence_number,v.registration_number,v.vin,v.brand,v.model FROM reservations r JOIN customers c ON c.id=r.customer_id LEFT JOIN vehicles v ON v.id=r.vehicle_id WHERE r.id=:id FOR UPDATE', ['id'=>$reservationId]);
        if(!$reservation||!in_array($reservation['status'],['confirmed','deposit_paid','ready'],true))throw new DomainException('Only a confirmed or ready reservation can generate a contract.');requireAgencyAccess($reservation['agency_id']);
        $existing=dbFetchOne('SELECT id FROM rental_contracts WHERE reservation_id=:id AND status<>\'cancelled\' LIMIT 1',['id'=>$reservationId]);if($existing)return(int)$existing['id'];
        $number=generateBusinessReference('CTR');$snapshot=['reservation_reference'=>$reservation['reference'],'customer'=>['name'=>$reservation['first_name'].' '.$reservation['last_name'],'identity_number'=>$reservation['identity_number'],'licence_number'=>$reservation['licence_number']],'vehicle'=>['registration_number'=>$reservation['registration_number'],'vin'=>$reservation['vin'],'description'=>$reservation['brand'].' '.$reservation['model']],'period'=>['pickup_at'=>$reservation['pickup_at'],'return_at'=>$reservation['return_at']],'pricing'=>json_decode($reservation['pricing_snapshot_json'],true),'deposit_amount'=>$reservation['deposit_amount'],'currency'=>$reservation['currency']];
        dbExecute('INSERT INTO rental_contracts(reservation_id,contract_number,status,current_version,created_by,updated_by)VALUES(:reservation,:number,\'generated\',1,:user,:user)',['reservation'=>$reservationId,'number'=>$number,'user'=>currentUserId()]);$id=(int)db()->lastInsertId();
        dbExecute('INSERT INTO contract_versions(contract_id,version_number,language_code,snapshot_json,terms_text,change_reason,created_by)VALUES(:contract,1,:language,:snapshot,:terms,\'Initial contract\',:user)',['contract'=>$id,'language'=>validateChoice($languageCode,supportedLanguages(),'fr'),'snapshot'=>json_encode($snapshot,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'terms'=>'The renter accepts the agreed rental period, vehicle condition, mileage, fuel, payment, deposit, and liability terms recorded in this contract.','user'=>currentUserId()]);auditLog('contract.generated','contract',$id,null,['contract_number'=>$number],$reservation['agency_id']);return$id;
    });
}

function amendContract($contractId, $reason, $languageCode = 'fr')
{
    return withTransaction(function()use($contractId,$reason,$languageCode){$contract=dbFetchOne('SELECT rc.*,r.agency_id FROM rental_contracts rc JOIN reservations r ON r.id=rc.reservation_id WHERE rc.id=:id FOR UPDATE',['id'=>$contractId]);if(!$contract)throw new InvalidArgumentException('Contract not found.');requireAgencyAccess($contract['agency_id']);if(trim($reason)==='')throw new InvalidArgumentException('An amendment reason is required.');$previous=dbFetchOne('SELECT snapshot_json,terms_text FROM contract_versions WHERE contract_id=:id ORDER BY version_number DESC LIMIT 1',['id'=>$contractId]);$version=(int)$contract['current_version']+1;dbExecute('INSERT INTO contract_versions(contract_id,version_number,language_code,snapshot_json,terms_text,change_reason,created_by)VALUES(:contract,:version,:language,:snapshot,:terms,:reason,:user)',['contract'=>$contractId,'version'=>$version,'language'=>validateChoice($languageCode,supportedLanguages(),'fr'),'snapshot'=>$previous['snapshot_json'],'terms'=>$previous['terms_text'],'reason'=>trim($reason),'user'=>currentUserId()]);dbExecute('UPDATE rental_contracts SET current_version=:version,status=\'amended\',updated_by=:user WHERE id=:id',['version'=>$version,'user'=>currentUserId(),'id'=>$contractId]);auditLog('contract.amended','contract',$contractId,['version'=>$contract['current_version']],['version'=>$version,'reason'=>$reason],$contract['agency_id']);return$version;});
}

function recordPayment(array $input)
{
    $paidAt=validDateTimeValue($input['paid_at']??'');
    if(!$paidAt)throw new InvalidArgumentException('A valid payment date and time are required.');
    $input['paid_at']=$paidAt->format('Y-m-d H:i:s');
    return withTransaction(function()use($input){$amount=positiveMoney($input['amount']??'');if($amount===null||(float)$amount<=0)throw new InvalidArgumentException('Enter a valid positive payment amount.');$reservation=dbFetchOne('SELECT * FROM reservations WHERE id=:id FOR UPDATE',['id'=>(int)$input['reservation_id']]);if(!$reservation)throw new InvalidArgumentException('Reservation not found.');requireAgencyAccess($reservation['agency_id']);$method=validateChoice($input['method']??'',['cash','card','bank_transfer','cheque','online','other'],null);if(!$method)throw new InvalidArgumentException('Select a valid payment method.');$number=generateBusinessReference('PAY');dbExecute('INSERT INTO payments(agency_id,reservation_id,contract_id,invoice_id,payment_number,amount,currency,paid_at,method,reference,status,notes,created_by)VALUES(:agency,:reservation,:contract,:invoice,:number,:amount,:currency,:paid_at,:method,:reference,\'paid\',:notes,:user)',['agency'=>$reservation['agency_id'],'reservation'=>$reservation['id'],'contract'=>$input['contract_id']?:null,'invoice'=>$input['invoice_id']?:null,'number'=>$number,'amount'=>$amount,'currency'=>$reservation['currency'],'paid_at'=>$input['paid_at'],'method'=>$method,'reference'=>trim((string)($input['reference']??'')),'notes'=>trim((string)($input['notes']??'')),'user'=>currentUserId()]);$id=(int)db()->lastInsertId();dbExecute('UPDATE reservations SET advance_amount=advance_amount+:amount,remaining_amount=GREATEST(0,total_amount-(advance_amount+:amount2)),updated_by=:user WHERE id=:id',['amount'=>$amount,'amount2'=>$amount,'user'=>currentUserId(),'id'=>$reservation['id']]);if(!empty($input['invoice_id']))dbExecute("UPDATE invoices SET paid_amount=paid_amount+:amount,status=CASE WHEN paid_amount+:amount2>=total_amount THEN 'paid' ELSE 'partially_paid' END WHERE id=:id",['amount'=>$amount,'amount2'=>$amount,'id'=>$input['invoice_id']]);auditLog('payment.recorded','payment',$id,null,['number'=>$number,'amount'=>$amount,'method'=>$method],$reservation['agency_id']);return$id;});
}

function createInvoiceFromReservation($reservationId)
{
    return withTransaction(function()use($reservationId){$reservation=dbFetchOne('SELECT * FROM reservations WHERE id=:id FOR UPDATE',['id'=>$reservationId]);if(!$reservation)throw new InvalidArgumentException('Reservation not found.');requireAgencyAccess($reservation['agency_id']);$number=generateBusinessReference('INV');dbExecute('INSERT INTO invoices(agency_id,customer_id,reservation_id,invoice_number,status,currency,subtotal,tax_amount,total_amount,paid_amount,issued_at,due_at,created_by)VALUES(:agency,:customer,:reservation,:number,\'unpaid\',:currency,:subtotal,:tax,:total,:paid,NOW(),DATE_ADD(NOW(),INTERVAL 7 DAY),:user)',['agency'=>$reservation['agency_id'],'customer'=>$reservation['customer_id'],'reservation'=>$reservation['id'],'number'=>$number,'currency'=>$reservation['currency'],'subtotal'=>$reservation['total_amount']-$reservation['tax_amount'],'tax'=>$reservation['tax_amount'],'total'=>$reservation['total_amount'],'paid'=>$reservation['advance_amount'],'user'=>currentUserId()]);$id=(int)db()->lastInsertId();dbExecute('INSERT INTO invoice_items(invoice_id,description,quantity,unit_price,tax_rate,line_total)VALUES(:invoice,:description,:quantity,:unit_price,0,:line_total)',['invoice'=>$id,'description'=>'Vehicle rental '.$reservation['reference'],'quantity'=>$reservation['rental_days'],'unit_price'=>$reservation['daily_price'],'line_total'=>$reservation['total_amount']]);auditLog('invoice.created','invoice',$id,null,['number'=>$number,'total'=>$reservation['total_amount']],$reservation['agency_id']);return$id;});
}

function updateDepositStatus($depositId,$newStatus,$retainedAmount='0.00',$reason=null)
{
    $allowed=['requested','received','held','partially_retained','returned','disputed'];$newStatus=validateChoice($newStatus,$allowed,null);if(!$newStatus)throw new InvalidArgumentException('Invalid deposit status.');return withTransaction(function()use($depositId,$newStatus,$retainedAmount,$reason){$deposit=dbFetchOne('SELECT d.*,r.agency_id FROM deposits d JOIN reservations r ON r.id=d.reservation_id WHERE d.id=:id FOR UPDATE',['id'=>$depositId]);if(!$deposit)throw new InvalidArgumentException('Deposit not found.');requireAgencyAccess($deposit['agency_id']);$retained=positiveMoney($retainedAmount)??'0.00';if((float)$retained>(float)$deposit['amount'])throw new InvalidArgumentException('Retained amount cannot exceed the deposit.');dbExecute('UPDATE deposits SET status=:status,retained_amount=:retained,retention_reason=:reason,received_at=IF(:status2=\'received\',COALESCE(received_at,NOW()),received_at),returned_at=IF(:status3=\'returned\',NOW(),returned_at),updated_by=:user WHERE id=:id',['status'=>$newStatus,'retained'=>$retained,'reason'=>$reason,'status2'=>$newStatus,'status3'=>$newStatus,'user'=>currentUserId(),'id'=>$depositId]);auditLog('deposit.status_changed','deposit',$depositId,['status'=>$deposit['status']],['status'=>$newStatus,'retained_amount'=>$retained,'reason'=>$reason],$deposit['agency_id']);return true;});
}

function createInspection(array $input)
{
    $inspectedAt=validDateTimeValue($input['inspected_at']??'');
    if(!$inspectedAt)throw new InvalidArgumentException('A valid inspection date and time are required.');
    $input['inspected_at']=$inspectedAt->format('Y-m-d H:i:s');
    return withTransaction(function()use($input){$contract=dbFetchOne('SELECT rc.*,r.agency_id,r.customer_id,r.vehicle_id FROM rental_contracts rc JOIN reservations r ON r.id=rc.reservation_id WHERE rc.id=:id FOR UPDATE',['id'=>(int)$input['contract_id']]);if(!$contract||!in_array($contract['status'],['generated','signed','active','amended'],true))throw new DomainException('Select an eligible contract.');requireAgencyAccess($contract['agency_id']);$type=validateChoice($input['inspection_type']??'',['checkout','return'],null);if(!$type)throw new InvalidArgumentException('Inspection type is invalid.');$fuel=(float)($input['fuel_level']??-1);if($fuel<0||$fuel>100)throw new InvalidArgumentException('Fuel level must be between 0 and 100 percent.');dbExecute('INSERT INTO vehicle_inspections(contract_id,vehicle_id,customer_id,inspection_type,inspected_at,mileage,fuel_level,cleanliness,accessories_json,notes,customer_signature_status,employee_signature_status,status,created_by)VALUES(:contract,:vehicle,:customer,:type,:at,:mileage,:fuel,:cleanliness,:accessories,:notes,:customer_signature,:employee_signature,\'validated\',:user)',['contract'=>$contract['id'],'vehicle'=>$contract['vehicle_id'],'customer'=>$contract['customer_id'],'type'=>$type,'at'=>$input['inspected_at'],'mileage'=>max(0,(int)$input['mileage']),'fuel'=>$fuel,'cleanliness'=>validateChoice($input['cleanliness']??'',['clean','acceptable','dirty'],'acceptable'),'accessories'=>json_encode(array_values(array_filter(array_map('trim',explode(',',(string)($input['accessories']??''))))),JSON_UNESCAPED_UNICODE),'notes'=>trim((string)($input['notes']??'')),'customer_signature'=>validateChoice($input['customer_signature_status']??'',['pending','signed','refused'],'pending'),'employee_signature'=>'signed','user'=>currentUserId()]);$id=(int)db()->lastInsertId();dbExecute('UPDATE vehicles SET current_mileage=GREATEST(current_mileage,:mileage),status=:status,updated_by=:user WHERE id=:vehicle',['mileage'=>max(0,(int)$input['mileage']),'status'=>$type==='checkout'?'rented':'cleaning','user'=>currentUserId(),'vehicle'=>$contract['vehicle_id']]);if($type==='checkout')dbExecute("UPDATE rental_contracts SET status='active',activated_at=NOW(),updated_by=:user WHERE id=:id",['user'=>currentUserId(),'id'=>$contract['id']]);auditLog('inspection.validated','inspection',$id,null,['type'=>$type,'mileage'=>$input['mileage'],'fuel'=>$fuel],$contract['agency_id']);return$id;});
}
