<?php

/** Phase 5B.3 is the sole authority permitted to activate a rental. */
final class RentalCheckoutReplay extends RuntimeException { private int $result; public function __construct(int $result){$this->result=$result;} public function result():int{return $this->result;} }
function rentalCheckoutHook(string $stage,array $context=[]): void { if(PHP_SAPI==='cli'&&defined('RENTAL_CHECKOUT_TEST_HOOK')&&RENTAL_CHECKOUT_TEST_HOOK===true&&function_exists('rentalCheckoutCliTestHook'))rentalCheckoutCliTestHook($stage,$context); }
function rentalCheckoutInteger($value,string $key): int { if(!is_int($value)&&(!is_string($value)||!preg_match('/^\d+$/',$value)))throw new InvalidArgumentException(t($key));$value=(int)$value;if($value<0)throw new InvalidArgumentException(t($key));return$value; }
function rentalCheckoutFuel($value): string { $value=trim((string)$value);if(!preg_match('/^\d{1,3}(?:\.\d{1,2})?$/',$value)||(float)$value<0||(float)$value>100)throw new InvalidArgumentException(t('validation.checkout_fuel'));return number_format((float)$value,2,'.',''); }
function rentalCheckoutTime($value): DateTimeImmutable { $time=validDateTimeValue($value);if(!$time||$time>(new DateTimeImmutable('now'))->modify('+5 minutes'))throw new InvalidArgumentException(t('validation.checkout_handover'));return$time; }
function rentalCheckoutCompleteIdempotency(int $id,int $reservationId): void {$changed=dbExecute("UPDATE rental_operation_idempotency_keys SET status='completed',result_entity_type='rental_checkout',result_entity_id=:result,completed_at=NOW(6) WHERE id=:id AND status='in_progress'",['result'=>$reservationId,'id'=>$id]);if($changed->rowCount()!==1)throw new DomainException(t('validation.contract_stale'));}
function rentalCheckout(array $command): int {
    contractRequireCutover();enforcePermission('rental.checkout');
    $reservationId=rentalCheckoutInteger($command['reservation_id']??null,'validation.checkout_not_found');$contractId=rentalCheckoutInteger($command['contract_id']??null,'validation.checkout_not_found');$inspectionId=rentalCheckoutInteger($command['inspection_id']??null,'validation.checkout_not_found');$mileage=rentalCheckoutInteger($command['mileage']??null,'validation.checkout_mileage');$fuel=rentalCheckoutFuel($command['fuel_level']??null);$handover=rentalCheckoutTime($command['handed_over_at']??null);$comment=trim((string)($command['comment']??''));if(mb_strlen($comment)>1000)throw new InvalidArgumentException(t('validation.checkout_comment'));
    $visible=contractScopedReservation($reservationId);if(!$visible)throw new InvalidArgumentException(t('validation.checkout_not_found'));$agency=(int)$visible['agency_id'];$expectedVehicle=(int)$visible['vehicle_id'];$expectedCustomer=(int)$visible['customer_id'];$actor=contractAcknowledgementActor($agency);
    try{return contractWithRetry(function()use($command,$reservationId,$contractId,$inspectionId,$mileage,$fuel,$handover,$comment,$agency,$expectedVehicle,$expectedCustomer,$actor){
        $payload=['reservation_id'=>$reservationId,'contract_id'=>$contractId,'inspection_id'=>$inspectionId,'vehicle_id'=>$expectedVehicle,'customer_id'=>$expectedCustomer,'agency_id'=>$agency,'mileage'=>$mileage,'fuel_level'=>$fuel,'handed_over_at'=>$handover->format('Y-m-d H:i:s'),'actor_id'=>(int)$actor['id']];$idem=contractAcquireIdempotency($agency,'rental_checkout',$command['idempotency_key']??'',$payload);
        /* The first acquisition binds public command values; lock and re-bind authoritative IDs below. */
        if($idem['completed'])throw new RentalCheckoutReplay($idem['result_id']); rentalCheckoutHook('after_idempotency');
        $reservation=contractScopedReservation($reservationId,true);if(!$reservation||$reservation['status']!=='ready'||empty($reservation['vehicle_id'])||(int)$reservation['customer_id']<=0||(int)$reservation['vehicle_id']!==$expectedVehicle||(int)$reservation['customer_id']!==$expectedCustomer)throw new DomainException(t('validation.checkout_reservation'));$customer=dbFetchOne("SELECT id FROM customers WHERE id=:id AND agency_id=:agency AND archived_at IS NULL AND status NOT IN('blocked','archived') FOR UPDATE",['id'=>$expectedCustomer,'agency'=>$agency]);if(!$customer)throw new DomainException(t('validation.checkout_reservation'));
        $contract=contractScopedRecord($contractId,true);if(!$contract||(int)$contract['reservation_id']!==$reservationId||(int)$contract['agency_id']!==$agency||$contract['status']!=='signed'||empty($contract['current_version_id']))throw new DomainException(t('validation.checkout_contract'));
        $vehicle=dbFetchOne('SELECT * FROM vehicles WHERE id=:id AND agency_id=:agency AND archived_at IS NULL FOR UPDATE',['id'=>$reservation['vehicle_id'],'agency'=>$agency]);if(!$vehicle||$vehicle['status']!=='reserved')throw new DomainException(t('validation.checkout_vehicle'));
        $inspection=dbFetchOne('SELECT * FROM vehicle_inspections WHERE id=:id AND agency_id=:agency FOR UPDATE',['id'=>$inspectionId,'agency'=>$agency]);if(!$inspection||$inspection['inspection_type']!=='checkout'||$inspection['status']!=='draft'||$inspection['archived_at']!==null||(int)$inspection['reservation_id']!==$reservationId||(int)$inspection['contract_id']!==$contractId||(int)$inspection['vehicle_id']!==(int)$vehicle['id']||(int)$inspection['customer_id']!==(int)$reservation['customer_id'])throw new DomainException(t('validation.checkout_inspection'));
        if((int)$inspection['mileage']!==$mileage||number_format((float)$inspection['fuel_level'],2,'.','')!==$fuel||$mileage<(int)$vehicle['current_mileage'])throw new DomainException(t('validation.checkout_values'));
        $photos=inspectionPhotoVerifyActiveBundle($inspectionId,$agency);
        $version=dbFetchOne('SELECT id FROM contract_versions WHERE id=:id AND contract_id=:contract AND agency_id=:agency FOR UPDATE',['id'=>$contract['current_version_id'],'contract'=>$contractId,'agency'=>$agency]);$acks=dbFetchAll('SELECT acknowledgement_type,contract_version_id FROM contract_acknowledgements WHERE contract_id=:contract AND agency_id=:agency ORDER BY acknowledgement_type,id FOR UPDATE',['contract'=>$contractId,'agency'=>$agency]);if(!$version||count($acks)!==2||!contractRequiredAcknowledgementsComplete($acks)||array_filter($acks,static fn($ack)=>(int)$ack['contract_version_id']!==(int)$version['id']))throw new DomainException(t('validation.checkout_contract'));
        $pickup=new DateTimeImmutable($reservation['pickup_at']);$return=new DateTimeImmutable($reservation['return_at']);if($return<=$pickup||$handover<$pickup->modify('-1 day')||$handover>$return)throw new DomainException(t('validation.checkout_handover'));
        if(dbFetchOne("SELECT id FROM reservations WHERE vehicle_id=:vehicle AND id<>:reservation AND status IN('active') FOR UPDATE",['vehicle'=>$vehicle['id'],'reservation'=>$reservationId]))throw new DomainException(t('validation.checkout_vehicle'));
        $updates=[['reservation_update',"UPDATE reservations SET status='active',updated_by=:actor WHERE id=:id AND agency_id=:agency AND status='ready'",['actor'=>$actor['id'],'id'=>$reservationId,'agency'=>$agency]],['contract_update',"UPDATE rental_contracts SET status='active',activated_at=:at,updated_by=:actor WHERE id=:id AND agency_id=:agency AND status='signed'",['at'=>$handover->format('Y-m-d H:i:s.u'),'actor'=>$actor['id'],'id'=>$contractId,'agency'=>$agency]],['vehicle_update',"UPDATE vehicles SET status='rented',current_mileage=:mileage,updated_by=:actor WHERE id=:id AND agency_id=:agency AND status='reserved'",['mileage'=>$mileage,'actor'=>$actor['id'],'id'=>$vehicle['id'],'agency'=>$agency]],['inspection_update',"UPDATE vehicle_inspections SET status='completed',completed_at=:at,notes=CASE WHEN :comment='' THEN notes ELSE :comment2 END WHERE id=:id AND agency_id=:agency AND status='draft'",['at'=>$handover->format('Y-m-d H:i:s.u'),'comment'=>$comment,'comment2'=>$comment,'id'=>$inspectionId,'agency'=>$agency]]];
        foreach($updates as[$stage,$sql,$params]){$changed=dbExecute($sql,$params);if($changed->rowCount()!==1)throw new DomainException(t('validation.contract_stale'));rentalCheckoutHook('after_'.$stage);}
        rentalCheckoutHook('before_reservation_history');
        dbExecute('INSERT INTO reservation_status_history(reservation_id,from_status,to_status,reason,metadata_json,changed_by)VALUES(:reservation,\'ready\',\'active\',NULL,:meta,:actor)',['reservation'=>$reservationId,'meta'=>json_encode(['source'=>'rental_checkout','contract_id'=>$contractId,'inspection_id'=>$inspectionId,'mileage'=>$mileage,'fuel_level'=>$fuel,'handed_over_at'=>$handover->format('Y-m-d H:i:s')],JSON_UNESCAPED_SLASHES),'actor'=>$actor['id']]);
        rentalCheckoutHook('after_reservation_history');
        dbExecute('INSERT INTO contract_status_history(agency_id,contract_id,reservation_id,from_status,to_status,changed_by,occurred_at,metadata_json)VALUES(:agency,:contract,:reservation,\'signed\',\'active\',:actor,:at,:meta)',['agency'=>$agency,'contract'=>$contractId,'reservation'=>$reservationId,'actor'=>$actor['id'],'at'=>$handover->format('Y-m-d H:i:s.u'),'meta'=>json_encode(['source'=>'rental_checkout','inspection_id'=>$inspectionId,'mileage'=>$mileage,'fuel_level'=>$fuel,'comment'=>$comment?:null],JSON_UNESCAPED_SLASHES)]);
        rentalCheckoutHook('after_contract_history');
        auditLog('rental.checkout','reservation',$reservationId,['reservation_status'=>'ready','contract_status'=>'signed','vehicle_status'=>'reserved','inspection_status'=>'draft'],['reservation_status'=>'active','contract_status'=>'active','vehicle_status'=>'rented','inspection_status'=>'completed','contract_id'=>$contractId,'inspection_id'=>$inspectionId,'mileage'=>$mileage,'fuel_level'=>$fuel,'handed_over_at'=>$handover->format('Y-m-d H:i:s')],$agency);rentalCheckoutHook('after_audit');rentalCheckoutHook('before_idempotency_completion');rentalCheckoutCompleteIdempotency($idem['id'],$reservationId);rentalCheckoutHook('before_commit');return$reservationId;
    });}catch(RentalCheckoutReplay$replay){return$replay->result();}
}
