-- Rental Agency Manager authoritative schema
-- Additive migration: it does not drop or rename legacy tables.
-- Back up the database before applying any migration.

CREATE TABLE IF NOT EXISTS schema_migrations (
    version VARCHAR(100) PRIMARY KEY,
    applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agencies (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    code VARCHAR(30) NOT NULL UNIQUE,
    email VARCHAR(190) NULL,
    phone VARCHAR(40) NULL,
    address VARCHAR(255) NULL,
    city VARCHAR(100) NULL,
    country_code CHAR(2) NOT NULL DEFAULT 'MA',
    currency CHAR(3) NOT NULL DEFAULT 'MAD',
    timezone VARCHAR(64) NOT NULL DEFAULT 'Africa/Casablanca',
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    archived_at DATETIME NULL,
    INDEX idx_agencies_status (status, archived_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    legacy_id INT NULL UNIQUE,
    fullname VARCHAR(150) NOT NULL,
    email VARCHAR(190) NOT NULL,
    email_normalized VARCHAR(190) NOT NULL UNIQUE,
    phone VARCHAR(40) NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(40) NOT NULL DEFAULT 'CUSTOMER',
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    failed_login_attempts INT UNSIGNED NOT NULL DEFAULT 0,
    locked_until DATETIME NULL,
    password_reset_token_hash CHAR(64) NULL,
    password_reset_expires_at DATETIME NULL,
    password_changed_at DATETIME NULL,
    sessions_invalid_before DATETIME NULL,
    last_login_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    archived_at DATETIME NULL,
    INDEX idx_users_role_status (role, status),
    INDEX idx_users_reset_hash (password_reset_token_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_agencies (
    user_id BIGINT UNSIGNED NOT NULL,
    agency_id BIGINT UNSIGNED NOT NULL,
    is_primary TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    PRIMARY KEY (user_id, agency_id),
    CONSTRAINT fk_user_agencies_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_agencies_agency FOREIGN KEY (agency_id) REFERENCES agencies(id),
    CONSTRAINT fk_user_agencies_creator FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS customers (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    legacy_id INT NULL UNIQUE,
    agency_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NULL,
    customer_type VARCHAR(20) NOT NULL DEFAULT 'individual',
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    identity_number VARCHAR(100) NULL,
    nationality CHAR(2) NULL,
    date_of_birth DATE NULL,
    address VARCHAR(255) NULL,
    phone VARCHAR(40) NULL,
    phone_normalized VARCHAR(40) NULL,
    whatsapp VARCHAR(40) NULL,
    email VARCHAR(190) NULL,
    email_normalized VARCHAR(190) NULL,
    licence_number VARCHAR(100) NULL,
    licence_issue_date DATE NULL,
    licence_expires_at DATE NULL,
    licence_country CHAR(2) NULL,
    company_name VARCHAR(190) NULL,
    ice VARCHAR(50) NULL,
    tax_identifier VARCHAR(80) NULL,
    company_registration_number VARCHAR(80) NULL,
    billing_address VARCHAR(255) NULL,
    notes TEXT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'new',
    blocking_reason VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    archived_at DATETIME NULL,
    CONSTRAINT fk_customers_agency FOREIGN KEY (agency_id) REFERENCES agencies(id),
    CONSTRAINT fk_customers_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_customers_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_customers_updated_by FOREIGN KEY (updated_by) REFERENCES users(id),
    INDEX idx_customers_search (agency_id, status, last_name, first_name),
    INDEX idx_customers_email (email_normalized),
    INDEX idx_customers_phone (phone_normalized),
    INDEX idx_customers_identity (identity_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS customer_documents (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    customer_id BIGINT UNSIGNED NOT NULL,
    document_type VARCHAR(50) NOT NULL,
    document_number VARCHAR(100) NULL,
    issuing_country CHAR(2) NULL,
    issued_at DATE NULL,
    expires_at DATE NULL,
    storage_path VARCHAR(255) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    file_size BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    archived_at DATETIME NULL,
    CONSTRAINT fk_customer_documents_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_customer_documents_creator FOREIGN KEY (created_by) REFERENCES users(id),
    INDEX idx_customer_documents_expiry (expires_at, archived_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS additional_drivers (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    customer_id BIGINT UNSIGNED NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    identity_number VARCHAR(100) NULL,
    date_of_birth DATE NULL,
    licence_number VARCHAR(100) NOT NULL,
    licence_issue_date DATE NULL,
    licence_expires_at DATE NOT NULL,
    licence_country CHAR(2) NULL,
    phone VARCHAR(40) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    archived_at DATETIME NULL,
    CONSTRAINT fk_additional_drivers_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_additional_drivers_creator FOREIGN KEY (created_by) REFERENCES users(id),
    INDEX idx_additional_drivers_customer (customer_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vehicle_categories (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    agency_id BIGINT UNSIGNED NULL,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(30) NOT NULL,
    base_daily_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    recommended_deposit DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    archived_at DATETIME NULL,
    CONSTRAINT fk_vehicle_categories_agency FOREIGN KEY (agency_id) REFERENCES agencies(id),
    UNIQUE KEY uq_vehicle_category_agency_code (agency_id, code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vehicles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    legacy_id INT NULL UNIQUE,
    agency_id BIGINT UNSIGNED NOT NULL,
    category_id BIGINT UNSIGNED NOT NULL,
    registration_number VARCHAR(40) NOT NULL UNIQUE,
    vin VARCHAR(80) NULL UNIQUE,
    brand VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    version VARCHAR(100) NULL,
    model_year SMALLINT UNSIGNED NULL,
    colour VARCHAR(60) NULL,
    fuel VARCHAR(30) NULL,
    transmission VARCHAR(30) NOT NULL DEFAULT 'manual',
    seats TINYINT UNSIGNED NULL,
    doors TINYINT UNSIGNED NULL,
    luggage_capacity TINYINT UNSIGNED NULL,
    current_mileage INT UNSIGNED NOT NULL DEFAULT 0,
    purchase_date DATE NULL,
    purchase_price DECIMAL(12,2) NULL,
    financing_type VARCHAR(40) NULL,
    monthly_finance_amount DECIMAL(12,2) NULL,
    base_daily_price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    recommended_deposit DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    mileage_allowance INT UNSIGNED NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'available',
    primary_image_path VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    archived_at DATETIME NULL,
    CONSTRAINT fk_vehicles_agency FOREIGN KEY (agency_id) REFERENCES agencies(id),
    CONSTRAINT fk_vehicles_category FOREIGN KEY (category_id) REFERENCES vehicle_categories(id),
    CONSTRAINT fk_vehicles_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_vehicles_updated_by FOREIGN KEY (updated_by) REFERENCES users(id),
    INDEX idx_vehicles_availability (agency_id, status, category_id, archived_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vehicle_documents (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    vehicle_id BIGINT UNSIGNED NOT NULL,
    document_type VARCHAR(50) NOT NULL,
    document_number VARCHAR(100) NULL,
    issued_at DATE NULL,
    expires_at DATE NULL,
    storage_path VARCHAR(255) NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    file_size BIGINT UNSIGNED NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    archived_at DATETIME NULL,
    CONSTRAINT fk_vehicle_documents_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_vehicle_documents_creator FOREIGN KEY (created_by) REFERENCES users(id),
    INDEX idx_vehicle_documents_expiry (expires_at, archived_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vehicle_status_history (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    vehicle_id BIGINT UNSIGNED NOT NULL,
    from_status VARCHAR(30) NULL,
    to_status VARCHAR(30) NOT NULL,
    reason VARCHAR(255) NULL,
    changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed_by BIGINT UNSIGNED NULL,
    CONSTRAINT fk_vehicle_status_history_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_vehicle_status_history_user FOREIGN KEY (changed_by) REFERENCES users(id),
    INDEX idx_vehicle_status_history_vehicle (vehicle_id, changed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reservations (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    legacy_id INT NULL UNIQUE,
    reference VARCHAR(40) NOT NULL UNIQUE,
    agency_id BIGINT UNSIGNED NOT NULL,
    return_agency_id BIGINT UNSIGNED NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    vehicle_id BIGINT UNSIGNED NULL,
    category_id BIGINT UNSIGNED NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    source VARCHAR(30) NOT NULL DEFAULT 'agency',
    pickup_at DATETIME NOT NULL,
    return_at DATETIME NOT NULL,
    pickup_location VARCHAR(255) NULL,
    return_location VARCHAR(255) NULL,
    delivery_location VARCHAR(255) NULL,
    pending_expires_at DATETIME NULL,
    currency CHAR(3) NOT NULL DEFAULT 'MAD',
    daily_price DECIMAL(12,2) NOT NULL,
    rental_days INT UNSIGNED NOT NULL,
    options_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    fees_total DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    discount_percent DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    discount_reason VARCHAR(255) NULL,
    tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total_amount DECIMAL(12,2) NOT NULL,
    advance_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    remaining_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    deposit_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    pricing_snapshot_json LONGTEXT NOT NULL,
    internal_notes TEXT NULL,
    cancellation_reason VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    archived_at DATETIME NULL,
    CONSTRAINT fk_reservations_agency FOREIGN KEY (agency_id) REFERENCES agencies(id),
    CONSTRAINT fk_reservations_return_agency FOREIGN KEY (return_agency_id) REFERENCES agencies(id),
    CONSTRAINT fk_reservations_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_reservations_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_reservations_category FOREIGN KEY (category_id) REFERENCES vehicle_categories(id),
    CONSTRAINT fk_reservations_created_by FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_reservations_updated_by FOREIGN KEY (updated_by) REFERENCES users(id),
    INDEX idx_reservation_conflict (vehicle_id, status, pickup_at, return_at),
    INDEX idx_reservation_agency_period (agency_id, pickup_at, return_at),
    INDEX idx_reservation_customer (customer_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reservation_status_history (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    reservation_id BIGINT UNSIGNED NOT NULL,
    from_status VARCHAR(30) NULL,
    to_status VARCHAR(30) NOT NULL,
    reason VARCHAR(255) NULL,
    metadata_json LONGTEXT NULL,
    changed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    changed_by BIGINT UNSIGNED NULL,
    CONSTRAINT fk_reservation_history_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id),
    CONSTRAINT fk_reservation_history_user FOREIGN KEY (changed_by) REFERENCES users(id),
    INDEX idx_reservation_history_reservation (reservation_id, changed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rental_options (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    agency_id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(120) NOT NULL,
    code VARCHAR(40) NOT NULL,
    pricing_type VARCHAR(30) NOT NULL DEFAULT 'per_day',
    unit_price DECIMAL(12,2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    archived_at DATETIME NULL,
    CONSTRAINT fk_rental_options_agency FOREIGN KEY (agency_id) REFERENCES agencies(id),
    UNIQUE KEY uq_rental_option_agency_code (agency_id, code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reservation_options (
    reservation_id BIGINT UNSIGNED NOT NULL,
    rental_option_id BIGINT UNSIGNED NOT NULL,
    quantity DECIMAL(10,2) NOT NULL DEFAULT 1.00,
    unit_price DECIMAL(12,2) NOT NULL,
    total_price DECIMAL(12,2) NOT NULL,
    PRIMARY KEY (reservation_id, rental_option_id),
    CONSTRAINT fk_reservation_options_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id),
    CONSTRAINT fk_reservation_options_option FOREIGN KEY (rental_option_id) REFERENCES rental_options(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS pricing_rules (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    agency_id BIGINT UNSIGNED NOT NULL,
    category_id BIGINT UNSIGNED NULL,
    name VARCHAR(150) NOT NULL,
    rule_type VARCHAR(40) NOT NULL,
    priority INT NOT NULL DEFAULT 100,
    starts_at DATETIME NULL,
    ends_at DATETIME NULL,
    conditions_json LONGTEXT NULL,
    adjustment_type VARCHAR(20) NOT NULL,
    adjustment_value DECIMAL(12,2) NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    archived_at DATETIME NULL,
    CONSTRAINT fk_pricing_rules_agency FOREIGN KEY (agency_id) REFERENCES agencies(id),
    CONSTRAINT fk_pricing_rules_category FOREIGN KEY (category_id) REFERENCES vehicle_categories(id),
    CONSTRAINT fk_pricing_rules_creator FOREIGN KEY (created_by) REFERENCES users(id),
    INDEX idx_pricing_rules_active (agency_id, status, starts_at, ends_at, priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS rental_contracts (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    reservation_id BIGINT UNSIGNED NOT NULL,
    contract_number VARCHAR(50) NOT NULL UNIQUE,
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    current_version INT UNSIGNED NOT NULL DEFAULT 1,
    signed_at DATETIME NULL,
    activated_at DATETIME NULL,
    completed_at DATETIME NULL,
    cancelled_at DATETIME NULL,
    cancellation_reason VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    CONSTRAINT fk_contracts_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id),
    CONSTRAINT fk_contracts_creator FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_contracts_updater FOREIGN KEY (updated_by) REFERENCES users(id),
    INDEX idx_contracts_status (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS contract_versions (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    contract_id BIGINT UNSIGNED NOT NULL,
    version_number INT UNSIGNED NOT NULL,
    language_code CHAR(2) NOT NULL DEFAULT 'fr',
    snapshot_json LONGTEXT NOT NULL,
    terms_text LONGTEXT NOT NULL,
    document_path VARCHAR(255) NULL,
    change_reason VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    CONSTRAINT fk_contract_versions_contract FOREIGN KEY (contract_id) REFERENCES rental_contracts(id),
    CONSTRAINT fk_contract_versions_creator FOREIGN KEY (created_by) REFERENCES users(id),
    UNIQUE KEY uq_contract_version (contract_id, version_number, language_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    agency_id BIGINT UNSIGNED NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    reservation_id BIGINT UNSIGNED NULL,
    contract_id BIGINT UNSIGNED NULL,
    invoice_number VARCHAR(50) NOT NULL UNIQUE,
    invoice_type VARCHAR(30) NOT NULL DEFAULT 'invoice',
    status VARCHAR(30) NOT NULL DEFAULT 'unpaid',
    currency CHAR(3) NOT NULL DEFAULT 'MAD',
    subtotal DECIMAL(12,2) NOT NULL,
    tax_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    total_amount DECIMAL(12,2) NOT NULL,
    paid_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    issued_at DATETIME NOT NULL,
    due_at DATETIME NULL,
    document_path VARCHAR(255) NULL,
    notes TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    cancelled_at DATETIME NULL,
    cancellation_reason VARCHAR(255) NULL,
    CONSTRAINT fk_invoices_agency FOREIGN KEY (agency_id) REFERENCES agencies(id),
    CONSTRAINT fk_invoices_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_invoices_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id),
    CONSTRAINT fk_invoices_contract FOREIGN KEY (contract_id) REFERENCES rental_contracts(id),
    CONSTRAINT fk_invoices_creator FOREIGN KEY (created_by) REFERENCES users(id),
    INDEX idx_invoices_status_due (agency_id, status, due_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invoice_items (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    invoice_id BIGINT UNSIGNED NOT NULL,
    description VARCHAR(255) NOT NULL,
    quantity DECIMAL(10,2) NOT NULL DEFAULT 1.00,
    unit_price DECIMAL(12,2) NOT NULL,
    tax_rate DECIMAL(5,2) NOT NULL DEFAULT 0.00,
    line_total DECIMAL(12,2) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    CONSTRAINT fk_invoice_items_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id),
    INDEX idx_invoice_items_invoice (invoice_id, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payments (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    agency_id BIGINT UNSIGNED NOT NULL,
    reservation_id BIGINT UNSIGNED NULL,
    contract_id BIGINT UNSIGNED NULL,
    invoice_id BIGINT UNSIGNED NULL,
    payment_number VARCHAR(50) NOT NULL UNIQUE,
    amount DECIMAL(12,2) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'MAD',
    paid_at DATETIME NOT NULL,
    method VARCHAR(30) NOT NULL,
    reference VARCHAR(100) NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'paid',
    proof_path VARCHAR(255) NULL,
    notes TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    cancelled_at DATETIME NULL,
    cancelled_by BIGINT UNSIGNED NULL,
    cancellation_reason VARCHAR(255) NULL,
    CONSTRAINT fk_payments_agency FOREIGN KEY (agency_id) REFERENCES agencies(id),
    CONSTRAINT fk_payments_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id),
    CONSTRAINT fk_payments_contract FOREIGN KEY (contract_id) REFERENCES rental_contracts(id),
    CONSTRAINT fk_payments_invoice FOREIGN KEY (invoice_id) REFERENCES invoices(id),
    CONSTRAINT fk_payments_creator FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_payments_canceller FOREIGN KEY (cancelled_by) REFERENCES users(id),
    INDEX idx_payments_agency_date (agency_id, paid_at, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS deposits (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    reservation_id BIGINT UNSIGNED NOT NULL,
    contract_id BIGINT UNSIGNED NULL,
    amount DECIMAL(12,2) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'MAD',
    status VARCHAR(30) NOT NULL DEFAULT 'requested',
    received_at DATETIME NULL,
    returned_at DATETIME NULL,
    retained_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    retention_reason VARCHAR(255) NULL,
    notes TEXT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    CONSTRAINT fk_deposits_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id),
    CONSTRAINT fk_deposits_contract FOREIGN KEY (contract_id) REFERENCES rental_contracts(id),
    CONSTRAINT fk_deposits_creator FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_deposits_updater FOREIGN KEY (updated_by) REFERENCES users(id),
    INDEX idx_deposits_status (status, returned_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    agency_id BIGINT UNSIGNED NOT NULL,
    vehicle_id BIGINT UNSIGNED NULL,
    contract_id BIGINT UNSIGNED NULL,
    category VARCHAR(40) NOT NULL,
    supplier VARCHAR(190) NULL,
    description VARCHAR(255) NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    currency CHAR(3) NOT NULL DEFAULT 'MAD',
    expense_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    receipt_path VARCHAR(255) NULL,
    approved_at DATETIME NULL,
    approved_by BIGINT UNSIGNED NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    archived_at DATETIME NULL,
    CONSTRAINT fk_expenses_agency FOREIGN KEY (agency_id) REFERENCES agencies(id),
    CONSTRAINT fk_expenses_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_expenses_contract FOREIGN KEY (contract_id) REFERENCES rental_contracts(id),
    CONSTRAINT fk_expenses_approver FOREIGN KEY (approved_by) REFERENCES users(id),
    CONSTRAINT fk_expenses_creator FOREIGN KEY (created_by) REFERENCES users(id),
    INDEX idx_expenses_reporting (agency_id, expense_date, status, category),
    INDEX idx_expenses_vehicle (vehicle_id, expense_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS maintenance_records (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    vehicle_id BIGINT UNSIGNED NOT NULL,
    maintenance_type VARCHAR(50) NOT NULL,
    description TEXT NULL,
    garage VARCHAR(190) NULL,
    supplier VARCHAR(190) NULL,
    current_mileage INT UNSIGNED NULL,
    scheduled_mileage INT UNSIGNED NULL,
    scheduled_date DATE NULL,
    entry_at DATETIME NULL,
    estimated_exit_at DATETIME NULL,
    actual_exit_at DATETIME NULL,
    cost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    replaced_parts TEXT NULL,
    invoice_path VARCHAR(255) NULL,
    next_maintenance_date DATE NULL,
    next_maintenance_mileage INT UNSIGNED NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'scheduled',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    archived_at DATETIME NULL,
    CONSTRAINT fk_maintenance_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_maintenance_creator FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_maintenance_updater FOREIGN KEY (updated_by) REFERENCES users(id),
    INDEX idx_maintenance_alerts (status, scheduled_date, next_maintenance_date),
    INDEX idx_maintenance_vehicle (vehicle_id, entry_at, actual_exit_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vehicle_inspections (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    contract_id BIGINT UNSIGNED NOT NULL,
    vehicle_id BIGINT UNSIGNED NOT NULL,
    customer_id BIGINT UNSIGNED NOT NULL,
    inspection_type VARCHAR(20) NOT NULL,
    inspected_at DATETIME NOT NULL,
    mileage INT UNSIGNED NOT NULL,
    fuel_level DECIMAL(5,2) NOT NULL,
    cleanliness VARCHAR(30) NULL,
    accessories_json LONGTEXT NULL,
    notes TEXT NULL,
    customer_signature_status VARCHAR(30) NOT NULL DEFAULT 'pending',
    employee_signature_status VARCHAR(30) NOT NULL DEFAULT 'pending',
    status VARCHAR(30) NOT NULL DEFAULT 'draft',
    validated_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NOT NULL,
    CONSTRAINT fk_inspections_contract FOREIGN KEY (contract_id) REFERENCES rental_contracts(id),
    CONSTRAINT fk_inspections_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_inspections_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_inspections_creator FOREIGN KEY (created_by) REFERENCES users(id),
    UNIQUE KEY uq_contract_inspection_type (contract_id, inspection_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inspection_photos (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    inspection_id BIGINT UNSIGNED NOT NULL,
    photo_type VARCHAR(30) NOT NULL,
    storage_path VARCHAR(255) NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    file_size BIGINT UNSIGNED NOT NULL,
    captured_at DATETIME NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    CONSTRAINT fk_inspection_photos_inspection FOREIGN KEY (inspection_id) REFERENCES vehicle_inspections(id),
    CONSTRAINT fk_inspection_photos_creator FOREIGN KEY (created_by) REFERENCES users(id),
    INDEX idx_inspection_photos_inspection (inspection_id, photo_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vehicle_damages (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    inspection_id BIGINT UNSIGNED NOT NULL,
    vehicle_id BIGINT UNSIGNED NOT NULL,
    zone VARCHAR(60) NOT NULL,
    damage_type VARCHAR(60) NOT NULL,
    description VARCHAR(255) NOT NULL,
    severity VARCHAR(30) NOT NULL,
    estimated_cost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    final_cost DECIMAL(12,2) NULL,
    responsible_party VARCHAR(30) NULL,
    payment_status VARCHAR(30) NOT NULL DEFAULT 'pending',
    status VARCHAR(30) NOT NULL DEFAULT 'open',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    resolved_at DATETIME NULL,
    CONSTRAINT fk_vehicle_damages_inspection FOREIGN KEY (inspection_id) REFERENCES vehicle_inspections(id),
    CONSTRAINT fk_vehicle_damages_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_vehicle_damages_creator FOREIGN KEY (created_by) REFERENCES users(id),
    INDEX idx_vehicle_damages_vehicle (vehicle_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS fines (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    vehicle_id BIGINT UNSIGNED NOT NULL,
    contract_id BIGINT UNSIGNED NULL,
    customer_id BIGINT UNSIGNED NULL,
    driver_name VARCHAR(190) NULL,
    occurred_at DATETIME NOT NULL,
    fine_type VARCHAR(60) NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    administrative_fee DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    document_path VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    CONSTRAINT fk_fines_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_fines_contract FOREIGN KEY (contract_id) REFERENCES rental_contracts(id),
    CONSTRAINT fk_fines_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_fines_creator FOREIGN KEY (created_by) REFERENCES users(id),
    INDEX idx_fines_vehicle_date (vehicle_id, occurred_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS accidents (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    vehicle_id BIGINT UNSIGNED NOT NULL,
    contract_id BIGINT UNSIGNED NULL,
    customer_id BIGINT UNSIGNED NULL,
    occurred_at DATETIME NOT NULL,
    location VARCHAR(255) NULL,
    description TEXT NOT NULL,
    driver_name VARCHAR(190) NULL,
    accident_report_path VARCHAR(255) NULL,
    police_report_path VARCHAR(255) NULL,
    insurance_claim_number VARCHAR(100) NULL,
    insurance_excess DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    estimated_cost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    final_cost DECIMAL(12,2) NULL,
    customer_charge DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    replacement_vehicle_id BIGINT UNSIGNED NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'reported',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    CONSTRAINT fk_accidents_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_accidents_replacement FOREIGN KEY (replacement_vehicle_id) REFERENCES vehicles(id),
    CONSTRAINT fk_accidents_contract FOREIGN KEY (contract_id) REFERENCES rental_contracts(id),
    CONSTRAINT fk_accidents_customer FOREIGN KEY (customer_id) REFERENCES customers(id),
    CONSTRAINT fk_accidents_creator FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    agency_id BIGINT UNSIGNED NOT NULL,
    reservation_id BIGINT UNSIGNED NULL,
    contract_id BIGINT UNSIGNED NULL,
    notification_type VARCHAR(50) NOT NULL,
    channel VARCHAR(30) NOT NULL DEFAULT 'internal',
    recipient VARCHAR(190) NOT NULL,
    language_code CHAR(2) NOT NULL DEFAULT 'fr',
    subject VARCHAR(255) NULL,
    message TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    sent_at DATETIME NULL,
    error_message VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT UNSIGNED NULL,
    CONSTRAINT fk_notifications_agency FOREIGN KEY (agency_id) REFERENCES agencies(id),
    CONSTRAINT fk_notifications_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id),
    CONSTRAINT fk_notifications_contract FOREIGN KEY (contract_id) REFERENCES rental_contracts(id),
    CONSTRAINT fk_notifications_creator FOREIGN KEY (created_by) REFERENCES users(id),
    INDEX idx_notifications_queue (status, channel, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS audit_logs (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    agency_id BIGINT UNSIGNED NULL,
    user_id BIGINT UNSIGNED NULL,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_id VARCHAR(80) NULL,
    before_json LONGTEXT NULL,
    after_json LONGTEXT NULL,
    ip_address VARCHAR(45) NULL,
    user_agent VARCHAR(255) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_logs_agency FOREIGN KEY (agency_id) REFERENCES agencies(id),
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users(id),
    INDEX idx_audit_logs_entity (entity_type, entity_id, created_at),
    INDEX idx_audit_logs_user (user_id, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT IGNORE INTO schema_migrations (version) VALUES ('001_authoritative_schema');
