<?php
require_once __DIR__.'/_components.php';
require_once __DIR__.'/../app/application.php';
requirePermission('contract.view');
$rawId=$_GET['id']??null;$id=is_string($rawId)&&preg_match('/^[1-9]\d*$/',$rawId)?(int)$rawId:0;$lang=validateChoice($_GET['lang']??'',supportedLanguages(),'en');
$detail=null;try{$detail=contractScopedDetail($id);}catch(Throwable$exception){}
if(!$detail||$detail['contract']['status']==='draft'){printNotFound(t('validation.contract_not_found'));}
$contract=$detail['contract'];
$version=dbFetchOne(
    'SELECT * FROM contract_versions WHERE contract_id=:contract AND agency_id=:agency AND version_number=:version AND language_code=:language',
    ['contract'=>$id,'agency'=>$contract['agency_id'],'version'=>$contract['current_version'],'language'=>$lang]
);
if(!$version){printNotFound(t('validation.contract_version_not_found'));}
$data=json_decode($version['snapshot_json'],true)?:[];
?><!doctype html><html lang="<?=e($lang)?>" dir="<?=$lang==='ar'?'rtl':'ltr'?>"><head><meta charset="utf-8"><title><?=e($contract['contract_number'])?></title><style>body{font:14px Arial;max-width:900px;margin:30px auto;color:#172536}header{display:flex;justify-content:space-between;border-bottom:3px solid #143b61;padding-bottom:20px}h1{color:#143b61}section{margin:25px 0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.box{border:1px solid #ccd7e0;padding:15px}.signatures{display:grid;grid-template-columns:1fr 1fr;gap:50px;margin-top:70px}.signature{border-top:1px solid #333;padding-top:8px}bdi{unicode-bidi:isolate;direction:ltr}@media print{button{display:none}body{margin:0}}</style></head><body><button onclick="window.print()"><?=e(translateInLanguage('common.print_pdf',$lang))?></button><header><div><h1><?=e(translateInLanguage('print.rental_contract',$lang))?></h1><strong><?=e(appConfig('name'))?></strong></div><div><strong><bdi><?=e($contract['contract_number'])?></bdi></strong><br><?=e(translateInLanguage('field.version',$lang))?> <bdi><?=e($version['version_number'])?></bdi><br><?=e(translateInLanguage('status.'.$contract['status'],$lang))?></div></header><section class="grid"><div class="box"><h2><?=e(translateInLanguage('field.customer',$lang))?></h2><p><?=e($data['customer']['name']??'')?></p><p><?=e(translateInLanguage('field.identity',$lang))?>: <bdi><?=e($data['customer']['identity_number']??'')?></bdi></p><p><?=e(translateInLanguage('field.licence',$lang))?>: <bdi><?=e($data['customer']['licence_number']??'')?></bdi></p></div><div class="box"><h2><?=e(translateInLanguage('field.vehicle',$lang))?></h2><p><?=e($data['vehicle']['description']??'')?></p><p><?=e(translateInLanguage('field.registration',$lang))?>: <bdi><?=e($data['vehicle']['registration_number']??'')?></bdi></p><p>VIN: <bdi><?=e($data['vehicle']['vin']??'')?></bdi></p></div></section><section class="box"><h2><?=e(translateInLanguage('section.rental_summary',$lang))?></h2><p><?=e(translateInLanguage('field.pickup',$lang))?>: <bdi><?=e($data['period']['pickup_at']??'')?></bdi></p><p><?=e(translateInLanguage('field.return',$lang))?>: <bdi><?=e($data['period']['return_at']??'')?></bdi></p><p><?=e(translateInLanguage('field.total',$lang))?>: <bdi><?=localizedMoney($data['pricing']['total']??0,$data['currency']??'MAD',$lang)?></bdi></p><p><?=e(translateInLanguage('field.deposit',$lang))?>: <bdi><?=localizedMoney($data['deposit_amount']??0,$data['currency']??'MAD',$lang)?></bdi></p></section><section><h2><?=e(translateInLanguage('print.terms',$lang))?></h2><p><?=nl2br(e($version['terms_text']))?></p></section><div class="signatures"><div class="signature"><?=e(translateInLanguage('print.customer_signature',$lang))?></div><div class="signature"><?=e(translateInLanguage('print.agency_signature',$lang))?></div></div></body></html>
