<?php
require_once __DIR__ . '/_layout.php';requirePermission('customers.manage');
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;$customer=$id?scopedCustomerRecord($id,false,false):null;if($id&&!$customer){http_response_code(404);exit(t('validation.customer_not_found'));}
$agencyIds=currentAgencyIds();if(!$agencyIds)$agencyIds=[0];$agencies=dbFetchAll("SELECT id,name FROM agencies WHERE archived_at IS NULL AND status='active' ORDER BY name");$agencyId=$customer?(int)$customer['agency_id']:(int)($_GET['agency_id']??$agencyIds[0]);requireAgencyAccess($agencyId);
if(requestMethod()==='POST'){requireCsrfPost();try{$action=$_POST['action']??'';if($action==='create'){$newId=createCustomerProfile((int)$_POST['agency_id'],$_POST);flash('success',t('message.customer_created'));safeRedirect('customer_detail.php?id='.$newId);}if($action==='update'&&$customer){updateCustomerProfile($customer['id'],$_POST,$_POST['updated_at']??'');flash('success',t('message.customer_updated'));safeRedirect('customer_detail.php?id='.$customer['id']);}throw new InvalidArgumentException(t('validation.invalid_action'));}catch(AuthorizationException$e){http_response_code(403);exit(t('validation.not_authorized'));}catch(InvalidArgumentException|DomainException$e){flash('danger',$e->getMessage());}catch(Throwable$e){reportDatabaseError($e,'Customer form failed');flash('danger',t('message.customer_failed'));}}
$values=array_merge(['customer_type'=>'individual','first_name'=>'','last_name'=>'','identity_number'=>'','nationality'=>'','date_of_birth'=>'','address'=>'','phone'=>'','whatsapp'=>'','email'=>'','licence_number'=>'','licence_issue_date'=>'','licence_expires_at'=>'','licence_country'=>'MA','company_name'=>'','ice'=>'','tax_identifier'=>'','company_registration_number'=>'','billing_address'=>'','notes'=>''],$_POST?:($customer??[]));
backofficeHeader(t($customer?'page.customer_edit.title':'page.customer_create.title'),'customer_form.php');pageHeader($customer?'page.customer_edit.title':'page.customer_create.title',$customer?'page.customer_edit.description':'page.customer_create.description',['breadcrumbs'=>[['label'=>'nav.customers','href'=>'customers.php'],['label'=>$customer?'page.customer_edit.title':'page.customer_create.title']],'secondary'=>['label'=>'common.cancel','href'=>$customer?'customer_detail.php?id='.$customer['id']:'customers.php']]);?>
<section class="card form-card"><form method="post"><?=csrfField()?><input type="hidden" name="action" value="<?=$customer?'update':'create'?>"><?php if($customer):?><input type="hidden" name="updated_at" value="<?=e($customer['updated_at'])?>"><?php endif;?><div class="grid">
<label><?=e(t('field.agency'))?><select name="agency_id" required <?=$customer?'disabled':''?>><?php foreach($agencies as$a):if(currentUserRole()!==ROLE_OWNER&&!in_array((int)$a['id'],$agencyIds,true))continue;?><option value="<?=e($a['id'])?>" <?=$agencyId===(int)$a['id']?'selected':''?>><?=e($a['name'])?></option><?php endforeach;?></select></label>
<label><?=e(t('field.type'))?><select name="customer_type"><option value="individual" <?=$values['customer_type']==='individual'?'selected':''?>><?=e(t('option.individual'))?></option><option value="company" <?=$values['customer_type']==='company'?'selected':''?>><?=e(t('option.company'))?></option></select></label>
<?php foreach(['first_name','last_name','identity_number','nationality','phone','whatsapp','email','licence_number','licence_country','company_name','ice','tax_identifier','company_registration_number']as$f):?><label><?=e(t('field.'.$f))?><input <?=$f==='email'?'type="email"':''?> name="<?=$f?>" value="<?=e($values[$f]??'')?>" <?=in_array($f,['first_name','last_name'],true)?'required':''?>></label><?php endforeach;?>
<?php foreach(['date_of_birth','licence_issue_date','licence_expires_at']as$f):?><label><?=e(t('field.'.$f))?><input type="date" name="<?=$f?>" value="<?=e($values[$f]??'')?>"></label><?php endforeach;?>
<label class="full"><?=e(t('field.address'))?><input name="address" value="<?=e($values['address'])?>"></label><label class="full"><?=e(t('field.billing_address'))?><input name="billing_address" value="<?=e($values['billing_address'])?>"></label><label class="full"><?=e(t('field.notes'))?><textarea name="notes"><?=e($values['notes'])?></textarea></label></div><div class="form-actions"><button class="btn primary"><?=e($customer?t('common.update'):t('common.create'))?></button><a class="btn secondary" href="<?=$customer?'customer_detail.php?id='.e($customer['id']):'customers.php'?>"><?=e(t('common.cancel'))?></a></div></form></section><?php backofficeFooter();
