<?php
require_once __DIR__ . '/_layout.php';
requirePermission('customers.manage');
$agencyIds = currentAgencyIds();

if (requestMethod() === 'POST') {
    requireCsrfPost();
    $action = $_POST['action'] ?? '';
    try {
        if ($action === 'create') {
            $agencyId = (int) ($_POST['agency_id'] ?? 0); requireAgencyAccess($agencyId);
            $firstName = trim((string) ($_POST['first_name'] ?? '')); $lastName = trim((string) ($_POST['last_name'] ?? ''));
            $email = normalizedEmail($_POST['email'] ?? ''); $phone = normalizedPhone($_POST['phone'] ?? '');
            $identity = trim((string) ($_POST['identity_number'] ?? ''));
            if ($firstName === '' || $lastName === '') throw new InvalidArgumentException('First and last name are required.');
            if ($email !== '' && !filter_var($email, FILTER_VALIDATE_EMAIL)) throw new InvalidArgumentException('A valid email is required.');
            $birthDate = ($_POST['date_of_birth'] ?? '') !== '' ? validDateValue($_POST['date_of_birth']) : null;
            if (($_POST['date_of_birth'] ?? '') !== '' && !$birthDate) throw new InvalidArgumentException('Date of birth is invalid.');
            if ($birthDate && $birthDate->diff(new DateTimeImmutable('today'))->y < appConfig('minimum_driver_age')) throw new InvalidArgumentException('Customer does not meet the configured minimum age.');
            $duplicate = dbFetchOne('SELECT id FROM customers WHERE agency_id=:agency AND archived_at IS NULL AND ((email_normalized<>\'\' AND email_normalized=:email) OR (phone_normalized<>\'\' AND phone_normalized=:phone) OR (identity_number<>\'\' AND identity_number=:identity)) LIMIT 1', ['agency'=>$agencyId,'email'=>$email,'phone'=>$phone,'identity'=>$identity]);
            if ($duplicate) throw new InvalidArgumentException('A possible duplicate customer already exists.');
            dbExecute('INSERT INTO customers (agency_id,customer_type,first_name,last_name,identity_number,nationality,date_of_birth,address,phone,phone_normalized,whatsapp,email,email_normalized,licence_number,licence_issue_date,licence_expires_at,licence_country,company_name,ice,tax_identifier,company_registration_number,billing_address,notes,status,created_by,updated_by) VALUES (:agency,:type,:first,:last,:identity,:nationality,:birth,:address,:phone_raw,:phone,:whatsapp,:email_raw,:email,:licence,:licence_issue,:licence_expiry,:licence_country,:company,:ice,:tax_id,:registration,:billing,:notes,:status,:user_id,:user_id)', [
                'agency'=>$agencyId,'type'=>validateChoice($_POST['customer_type']??'', ['individual','company'],'individual'),'first'=>$firstName,'last'=>$lastName,'identity'=>$identity,'nationality'=>strtoupper(substr(trim((string)($_POST['nationality']??'')),0,2))?:null,'birth'=>$birthDate?$birthDate->format('Y-m-d'):null,'address'=>trim((string)($_POST['address']??'')),'phone_raw'=>trim((string)($_POST['phone']??'')),'phone'=>$phone,'whatsapp'=>trim((string)($_POST['whatsapp']??'')),'email_raw'=>$email,'email'=>$email,'licence'=>trim((string)($_POST['licence_number']??'')),'licence_issue'=>($_POST['licence_issue_date']??'')?:null,'licence_expiry'=>($_POST['licence_expires_at']??'')?:null,'licence_country'=>strtoupper(substr(trim((string)($_POST['licence_country']??'')),0,2))?:null,'company'=>trim((string)($_POST['company_name']??'')),'ice'=>trim((string)($_POST['ice']??'')),'tax_id'=>trim((string)($_POST['tax_identifier']??'')),'registration'=>trim((string)($_POST['company_registration_number']??'')),'billing'=>trim((string)($_POST['billing_address']??'')),'notes'=>trim((string)($_POST['notes']??'')),'status'=>validateChoice($_POST['status']??'', ['new','regular','VIP','watchlist','blocked'],'new'),'user_id'=>currentUserId()
            ]);
            $id=(int)db()->lastInsertId(); auditLog('customer.created','customer',$id,null,['name'=>$firstName.' '.$lastName],$agencyId); flash('success','Customer created.');
        } elseif ($action === 'archive') {
            $id=(int)($_POST['id']??0); $customer=dbFetchOne('SELECT * FROM customers WHERE id=:id',['id'=>$id]); if(!$customer) throw new InvalidArgumentException('Customer not found.'); requireAgencyAccess($customer['agency_id']);
            dbExecute('UPDATE customers SET archived_at=NOW(),status=\'archived\',updated_by=:user WHERE id=:id',['user'=>currentUserId(),'id'=>$id]); auditLog('customer.archived','customer',$id,$customer,['status'=>'archived'],$customer['agency_id']); flash('success','Customer archived.');
        } elseif ($action === 'status') {
            $id=(int)($_POST['id']??0); $customer=dbFetchOne('SELECT * FROM customers WHERE id=:id',['id'=>$id]); if(!$customer) throw new InvalidArgumentException('Customer not found.'); requireAgencyAccess($customer['agency_id']); $status=validateChoice($_POST['status']??'', ['new','regular','VIP','watchlist','blocked'], null); if(!$status) throw new InvalidArgumentException('Invalid status.');
            dbExecute('UPDATE customers SET status=:status,blocking_reason=:reason,updated_by=:user WHERE id=:id',['status'=>$status,'reason'=>$status==='blocked'?trim((string)($_POST['reason']??'')):null,'user'=>currentUserId(),'id'=>$id]); auditLog('customer.status_changed','customer',$id,['status'=>$customer['status']],['status'=>$status],$customer['agency_id']); flash('success','Customer status updated.');
        }
    } catch (InvalidArgumentException|DomainException $exception) { flash('danger',$exception->getMessage()); }
    catch (Throwable $exception) { reportDatabaseError($exception,'Customer operation failed'); flash('danger','The customer operation could not be completed.'); }
    safeRedirect('customers.php');
}

[$page,$size,$offset]=paginationParameters(); $search=trim((string)($_GET['q']??'')); $agencyId=(int)($_GET['agency_id']??($agencyIds[0]??0)); requireAgencyAccess($agencyId);
$params=['agency'=>$agencyId,'search1'=>'%'.$search.'%','search2'=>'%'.$search.'%','search3'=>'%'.$search.'%','search4'=>'%'.$search.'%','search5'=>'%'.$search.'%'];
$customers=dbFetchAll("SELECT * FROM customers WHERE agency_id=:agency AND archived_at IS NULL AND (first_name LIKE :search1 OR last_name LIKE :search2 OR email LIKE :search3 OR phone LIKE :search4 OR identity_number LIKE :search5) ORDER BY updated_at DESC LIMIT $size OFFSET $offset",$params);
$agencies=dbFetchAll('SELECT id,name FROM agencies WHERE archived_at IS NULL ORDER BY name');
backofficeHeader(t('customers'),'customers.php'); ?>
<div class="page-head"><h1><?=e(t('customers'))?></h1></div>
<form class="filters" method="get"><label><?=e(t('search'))?><input name="q" value="<?=e($search)?>"></label><label>Agency<select name="agency_id"><?php foreach($agencies as $agency):if(!in_array((int)$agency['id'],$agencyIds,true)&&currentUserRole()!==ROLE_OWNER)continue;?><option value="<?=e($agency['id'])?>" <?=$agencyId==(int)$agency['id']?'selected':''?>><?=e($agency['name'])?></option><?php endforeach;?></select></label><button class="btn secondary">Filter</button></form>
<div class="grid"><section class="card"><h2>New customer</h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="create"><div class="grid"><label>Agency<select name="agency_id" required><?php foreach($agencies as $agency):if(!in_array((int)$agency['id'],$agencyIds,true)&&currentUserRole()!==ROLE_OWNER)continue;?><option value="<?=e($agency['id'])?>"><?=e($agency['name'])?></option><?php endforeach;?></select></label><label>Type<select name="customer_type"><option value="individual">Individual</option><option value="company">Company</option></select></label><label>First name<input name="first_name" required></label><label>Last name<input name="last_name" required></label><label>Identity / passport<input name="identity_number"></label><label>Nationality<input name="nationality" maxlength="2"></label><label>Date of birth<input type="date" name="date_of_birth"></label><label>Phone<input name="phone"></label><label>WhatsApp<input name="whatsapp"></label><label>Email<input type="email" name="email"></label><label>Licence number<input name="licence_number"></label><label>Licence issue date<input type="date" name="licence_issue_date"></label><label>Licence expiry<input type="date" name="licence_expires_at"></label><label>Licence country<input name="licence_country" maxlength="2"></label><label>Company name<input name="company_name"></label><label>ICE<input name="ice"></label><label class="full">Address<input name="address"></label><label class="full">Notes<textarea name="notes"></textarea></label></div><button class="btn primary" type="submit"><?=e(t('save'))?></button></form></section>
<section class="card"><h2>Customer records</h2><div class="table-wrap"><table><tr><th>Name</th><th>Contact</th><th>Identity</th><th>Status</th><th><?=e(t('actions'))?></th></tr><?php foreach($customers as $customer):?><tr><td><?=e($customer['first_name'].' '.$customer['last_name'])?></td><td><?=e($customer['email'])?><br><?=e($customer['phone'])?></td><td><?=e($customer['identity_number'])?></td><td><?=statusBadge($customer['status'])?></td><td><form method="post" style="display:inline"><?=csrfField()?><input type="hidden" name="action" value="status"><input type="hidden" name="id" value="<?=e($customer['id'])?>"><select name="status" onchange="this.form.submit()"><?php foreach(['new','regular','VIP','watchlist','blocked'] as $status):?><option <?=$status===$customer['status']?'selected':''?>><?=e($status)?></option><?php endforeach;?></select></form><form method="post" style="display:inline" onsubmit="return confirm('Archive this customer?')"><?=csrfField()?><input type="hidden" name="action" value="archive"><input type="hidden" name="id" value="<?=e($customer['id'])?>"><button class="btn danger">Archive</button></form></td></tr><?php endforeach;?></table><?php if(!$customers):?><p class="empty"><?=e(t('no_results'))?></p><?php endif;?></div></section></div>
<?php backofficeFooter();
