<?php
require_once __DIR__ . '/_layout.php';
requirePermission('contracts.manage');
$ids = currentAgencyIds(); if (!$ids) $ids = [0];
$ph = implode(',', array_fill(0, count($ids), '?'));
$quotes = dbFetchAll("SELECT r.reference,r.id,r.created_at,c.first_name,c.last_name,r.total_amount,r.currency FROM reservations r JOIN customers c ON c.id=r.customer_id WHERE r.agency_id IN ($ph) AND r.status='quote' ORDER BY r.created_at DESC", $ids);
$contracts = dbFetchAll("SELECT rc.id,rc.contract_number,rc.status,rc.current_version,c.first_name,c.last_name FROM rental_contracts rc JOIN reservations r ON r.id=rc.reservation_id JOIN customers c ON c.id=r.customer_id WHERE r.agency_id IN ($ph) ORDER BY rc.created_at DESC", $ids);
$invoices = canViewInvoiceSections() ? dbFetchAll("SELECT i.id,i.invoice_number,i.status,i.total_amount,i.currency,c.first_name,c.last_name FROM invoices i JOIN customers c ON c.id=i.customer_id WHERE i.agency_id IN ($ph) ORDER BY i.issued_at DESC", $ids) : [];
backofficeHeader('Documents', 'documents.php');
pageHeader('Quotes and contract documents', 'Open printable commercial documents for your assigned agencies.', [
    'breadcrumbs'=>[['label'=>'Commercial'],['label'=>'Quotes / documents']],
]);
?>
<div class="grid"><section class="card"><h2>Quotes</h2><div class="table-wrap" role="region" aria-label="Quotes" tabindex="0"><table><thead><tr><th scope="col">Reference</th><th scope="col">Customer</th><th scope="col">Total</th><th scope="col">Document</th></tr></thead><tbody><?php foreach($quotes as $q):?><tr><td><?=e($q['reference'])?></td><td><?=e($q['first_name'].' '.$q['last_name'])?></td><td class="money"><?=money($q['total_amount'],$q['currency'])?></td><td><a class="btn secondary" target="_blank" rel="noopener" href="quote_print.php?id=<?=e($q['id'])?>">Print / PDF</a></td></tr><?php endforeach;?></tbody></table><?php if(!$quotes) echo emptyState('No quotes found'); ?></div></section>
<section class="card"><h2>Contracts</h2><div class="table-wrap" role="region" aria-label="Contracts" tabindex="0"><table><thead><tr><th scope="col">Number</th><th scope="col">Customer</th><th scope="col">Status</th><th scope="col">Version</th><th scope="col">Document</th></tr></thead><tbody><?php foreach($contracts as $c):?><tr><td><?=e($c['contract_number'])?></td><td><?=e($c['first_name'].' '.$c['last_name'])?></td><td><?=statusBadge($c['status'])?></td><td><?=e($c['current_version'])?></td><td><a class="btn secondary" target="_blank" rel="noopener" href="contract_print.php?id=<?=e($c['id'])?>&lang=<?=e(language())?>">Print / PDF</a></td></tr><?php endforeach;?></tbody></table><?php if(!$contracts) echo emptyState('No contracts found'); ?></div></section></div>
<?php if(canViewInvoiceSections()): ?><section class="card" style="margin-block-start:1rem"><h2>Invoices</h2><div class="table-wrap" role="region" aria-label="Invoices" tabindex="0"><table><thead><tr><th scope="col">Number</th><th scope="col">Customer</th><th scope="col">Total</th><th scope="col">Status</th><th scope="col">Document</th></tr></thead><tbody><?php foreach($invoices as $i):?><tr><td><?=e($i['invoice_number'])?></td><td><?=e($i['first_name'].' '.$i['last_name'])?></td><td class="money"><?=money($i['total_amount'],$i['currency'])?></td><td><?=statusBadge($i['status'])?></td><td><a class="btn secondary" target="_blank" rel="noopener" href="invoice_print.php?id=<?=e($i['id'])?>">Print / PDF</a></td></tr><?php endforeach;?></tbody></table><?php if(!$invoices) echo emptyState('No invoices found'); ?></div></section><?php endif; ?>
<?php backofficeFooter();
