<?php
require_once __DIR__ . '/_layout.php';
requirePermission('contracts.manage');
$ids = currentAgencyIds(); if (!$ids) $ids = [0];
$ph = implode(',', array_fill(0, count($ids), '?'));
$quotes = dbFetchAll("SELECT r.reference,r.id,r.created_at,c.first_name,c.last_name,r.total_amount,r.currency FROM reservations r JOIN customers c ON c.id=r.customer_id WHERE r.agency_id IN ($ph) AND r.status='quote' ORDER BY r.created_at DESC", $ids);
$contracts = dbFetchAll("SELECT rc.id,rc.contract_number,rc.status,rc.current_version,c.first_name,c.last_name FROM rental_contracts rc JOIN reservations r ON r.id=rc.reservation_id JOIN customers c ON c.id=r.customer_id WHERE r.agency_id IN ($ph) ORDER BY rc.created_at DESC", $ids);
$invoices = canViewInvoiceSections() ? dbFetchAll("SELECT i.id,i.invoice_number,i.status,i.total_amount,i.currency,c.first_name,c.last_name FROM invoices i JOIN customers c ON c.id=i.customer_id WHERE i.agency_id IN ($ph) ORDER BY i.issued_at DESC", $ids) : [];
backofficeHeader(t('page.documents.title'), 'documents.php');
pageHeader('page.documents.title', 'page.documents.description', [
    'breadcrumbs'=>[['label'=>'nav.commercial'],['label'=>'nav.documents']],
]);
?>
<div class="grid"><section class="card"><h2><?=e(t('section.quote_register'))?></h2><div class="table-wrap" role="region" aria-label="<?=e(t('section.quote_register'))?>" tabindex="0"><table><thead><tr><th scope="col"><?=e(t('field.reference'))?></th><th scope="col"><?=e(t('field.customer'))?></th><th scope="col"><?=e(t('field.total'))?></th><th scope="col"><?=e(t('field.documents'))?></th></tr></thead><tbody><?php foreach($quotes as $q):?><tr><td><?=isolatedValue($q['reference'],'reference-value')?></td><td><?=e($q['first_name'].' '.$q['last_name'])?></td><td class="money"><?=money($q['total_amount'],$q['currency'])?></td><td><a class="btn secondary" target="_blank" rel="noopener" href="quote_print.php?id=<?=e($q['id'])?>"><?=e(t('common.print_pdf'))?></a></td></tr><?php endforeach;?></tbody></table><?php if(!$quotes) echo emptyState('empty.no_records'); ?></div></section>
<section class="card"><h2><?=e(t('section.contract_register'))?></h2><div class="table-wrap" role="region" aria-label="<?=e(t('section.contract_register'))?>" tabindex="0"><table><thead><tr><th scope="col"><?=e(t('field.number'))?></th><th scope="col"><?=e(t('field.customer'))?></th><th scope="col"><?=e(t('common.status'))?></th><th scope="col"><?=e(t('field.version'))?></th><th scope="col"><?=e(t('field.documents'))?></th></tr></thead><tbody><?php foreach($contracts as $c):?><tr><td><?=isolatedValue($c['contract_number'],'reference-value')?></td><td><?=e($c['first_name'].' '.$c['last_name'])?></td><td><?=statusBadge($c['status'])?></td><td><?=e($c['current_version'])?></td><td><a class="btn secondary" target="_blank" rel="noopener" href="contract_print.php?id=<?=e($c['id'])?>&lang=<?=e(language())?>"><?=e(t('common.print_pdf'))?></a></td></tr><?php endforeach;?></tbody></table><?php if(!$contracts) echo emptyState('empty.no_records'); ?></div></section></div>
<?php if(canViewInvoiceSections()): ?><section class="card" style="margin-block-start:1rem"><h2><?=e(t('section.invoices'))?></h2><div class="table-wrap" role="region" aria-label="<?=e(t('section.invoices'))?>" tabindex="0"><table><thead><tr><th scope="col"><?=e(t('field.number'))?></th><th scope="col"><?=e(t('field.customer'))?></th><th scope="col"><?=e(t('field.total'))?></th><th scope="col"><?=e(t('common.status'))?></th><th scope="col"><?=e(t('field.documents'))?></th></tr></thead><tbody><?php foreach($invoices as $i):?><tr><td><?=isolatedValue($i['invoice_number'],'reference-value')?></td><td><?=e($i['first_name'].' '.$i['last_name'])?></td><td class="money"><?=money($i['total_amount'],$i['currency'])?></td><td><?=statusBadge($i['status'])?></td><td><a class="btn secondary" target="_blank" rel="noopener" href="invoice_print.php?id=<?=e($i['id'])?>"><?=e(t('common.print_pdf'))?></a></td></tr><?php endforeach;?></tbody></table><?php if(!$invoices) echo emptyState('empty.no_invoices'); ?></div></section><?php endif; ?>
<?php backofficeFooter();
