<?php
require_once __DIR__ . '/_layout.php';
requirePermission('payments.create');
$canManageFinance=canViewFinanceHistory();

if(requestMethod()==='POST'){
    requireCsrfPost();$storedProof=null;
    try{
        $action=$_POST['action']??'';
        if($action==='payment'||$action==='excess_payment'){
            if(isset($_FILES['proof'])&&($_FILES['proof']['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE)$storedProof=storeValidatedDocument($_FILES['proof'],'payment_proofs');
            $command=['reservation_id'=>(int)($_POST['reservation_id']??0),'contract_id'=>$_POST['contract_id']??null,'invoice_id'=>$_POST['invoice_id']??null,'amount'=>$_POST['amount']??'','paid_at'=>$_POST['paid_at']??'','method'=>$_POST['method']??'','reference'=>$_POST['reference']??'','notes'=>$_POST['notes']??'','reason'=>$_POST['reason']??'','idempotency_key'=>$_POST['idempotency_key']??''];
            if($storedProof)$command+=['proof_path'=>$storedProof['path'],'proof_original_name'=>$storedProof['original_name'],'proof_mime_type'=>$storedProof['mime_type'],'proof_file_size'=>$storedProof['size']];
            $id=$action==='excess_payment'?createExcessPayment($command):recordSettledPayment($command);flash('success',t($action==='excess_payment'?'message.finance_excess_created':'message.finance_payment_created',['id'=>$id]));
        }elseif($action==='invoice_draft'){
            financeAssertPermission('invoices.manage');$id=createInvoiceDraftFromReservation(['reservation_id'=>(int)($_POST['reservation_id']??0),'language_code'=>$_POST['language_code']??language(),'idempotency_key'=>$_POST['idempotency_key']??'']);safeRedirect('invoice_detail.php?id='.$id);
        }elseif($action==='deposit_create'){
            financeAssertPermission('deposits.manage');$id=createDeposit(['reservation_id'=>(int)($_POST['reservation_id']??0),'contract_id'=>$_POST['contract_id']??null,'amount'=>$_POST['amount']??'','reason'=>$_POST['reason']??'','idempotency_key'=>$_POST['idempotency_key']??'']);flash('success',t('message.deposit_request_created'));
        }else throw new InvalidArgumentException(t('validation.invalid_action'));
    }catch(AuthorizationException $exception){if($storedProof)removeNewStoredUpload($storedProof['path']);http_response_code(403);exit(t('validation.not_authorized'));}
    catch(InvalidArgumentException|DomainException $exception){if($storedProof)removeNewStoredUpload($storedProof['path']);flash('danger',$exception->getMessage());}
    catch(Throwable $exception){if($storedProof)removeNewStoredUpload($storedProof['path']);reportDatabaseError($exception,'Finance operation failed');flash('danger',t('message.finance_failed'));}
    safeRedirect('finance.php');
}

[$agencyIds,$ph]=financeScopedPlaceholders(currentAgencyIds());
$reservations=dbFetchAll("SELECT r.id,r.reference,r.total_amount,r.advance_amount,r.remaining_amount,r.currency,c.first_name,c.last_name,rc.id contract_id,i.id invoice_id FROM reservations r JOIN customers c ON c.id=r.customer_id LEFT JOIN rental_contracts rc ON rc.reservation_id=r.id AND rc.status<>'cancelled' LEFT JOIN invoices i ON i.reservation_id=r.id AND i.invoice_type='invoice' AND i.status NOT IN('cancelled','credited') WHERE r.agency_id IN ($ph) AND r.status NOT IN('cancelled','expired') ORDER BY r.created_at DESC LIMIT 200",$agencyIds);
$payments=$canManageFinance?dbFetchAll("SELECT p.id,p.payment_number,p.amount,p.currency,p.method,p.status,p.paid_at,r.reference reservation_reference FROM payments p JOIN reservations r ON r.id=p.reservation_id WHERE p.agency_id IN ($ph) ORDER BY p.paid_at DESC,p.id DESC LIMIT 100",$agencyIds):[];
$deposits=$canManageFinance&&can('deposits.manage')?dbFetchAll("SELECT d.id,d.amount,d.received_amount,d.retained_amount,d.returned_amount,d.currency,d.status,r.reference FROM deposits d JOIN reservations r ON r.id=d.reservation_id WHERE d.agency_id IN ($ph) ORDER BY d.created_at DESC,d.id DESC LIMIT 100",$agencyIds):[];
backofficeHeader(t('page.finance.title'),'finance.php');pageHeader('page.finance.title','page.finance.description',['breadcrumbs'=>[['label'=>'nav.finance'],['label'=>'nav.payments']],'primary'=>['label'=>'action.record_payment','href'=>'#record-payment'],'secondary'=>can('invoices.manage')?['label'=>'page.invoices.title','href'=>'invoices.php']:null]);
?>
<div class="grid"><section class="card" id="record-payment"><div class="section-card-header"><h2><?=navigationIcon('finance')?><?=e(t('section.record_payment'))?></h2></div>
<form method="post" enctype="multipart/form-data"><?=csrfField()?><?=financeIdempotencyField('payment.create')?><input type="hidden" name="action" value="payment">
<label><?=e(t('field.reservation'))?><select name="reservation_id" required><?php foreach($reservations as$r):?><option value="<?=e($r['id'])?>"><?=e($r['reference'].' — '.$r['first_name'].' '.$r['last_name'].' — '.localizedMoney($r['remaining_amount'],$r['currency']))?></option><?php endforeach;?></select></label>
<label><?=e(t('field.amount'))?><input name="amount" type="number" step="0.01" inputmode="decimal" required></label><label><?=e(t('field.date_time'))?><input type="datetime-local" name="paid_at" value="<?=e(date('Y-m-d\TH:i'))?>" required></label>
<label><?=e(t('field.method'))?><select name="method"><?php foreach(financePaymentMethods()as$m):?><option value="<?=e($m)?>"><?=e(t('option.'.$m))?></option><?php endforeach;?></select></label><label><?=e(t('field.reference'))?><input name="reference"></label><label><?=e(t('field.document'))?><input type="file" name="proof" accept="application/pdf,image/jpeg,image/png,image/webp"></label><label><?=e(t('field.notes'))?><textarea name="notes"></textarea></label><button class="btn primary"><?=e(t('action.record_payment'))?></button></form>
<?php if(can('payments.excess')):?><hr><div class="section-card-header"><h2><?=navigationIcon('finance')?><?=e(t('action.allocate_excess'))?></h2></div><form method="post" enctype="multipart/form-data"><?=csrfField()?><?=financeIdempotencyField('payment.excess')?><input type="hidden" name="action" value="excess_payment"><label><?=e(t('field.reservation'))?><select name="reservation_id"><?php foreach($reservations as$r):?><option value="<?=e($r['id'])?>"><?=e($r['reference'].' — '.localizedMoney($r['remaining_amount'],$r['currency']))?></option><?php endforeach;?></select></label><label><?=e(t('field.amount'))?><input name="amount" required type="number" step="0.01" inputmode="decimal"></label><label><?=e(t('field.method'))?><select name="method"><?php foreach(financePaymentMethods()as$m):?><option value="<?=e($m)?>"><?=e(t('option.'.$m))?></option><?php endforeach;?></select></label><label><?=e(t('field.reason'))?><input name="reason" required maxlength="255"></label><label><?=e(t('field.document'))?><input type="file" name="proof" accept="application/pdf,image/jpeg,image/png,image/webp"></label><input type="hidden" name="paid_at" value="<?=e(date('Y-m-d\TH:i'))?>"><button class="btn secondary"><?=e(t('action.allocate_excess'))?></button></form><?php endif;?>
<?php if(can('invoices.manage')):?><hr><div class="section-card-header"><h2><?=navigationIcon('finance')?><?=e(t('action.create_invoice'))?></h2></div><form method="post"><?=csrfField()?><?=financeIdempotencyField('invoice.draft')?><input type="hidden" name="action" value="invoice_draft"><label><?=e(t('field.reservation'))?><select name="reservation_id"><?php foreach($reservations as$r):?><option value="<?=e($r['id'])?>"><?=e($r['reference'])?></option><?php endforeach;?></select></label><label><?=e(t('field.language'))?><select name="language_code"><?php foreach(supportedLanguages()as$lang):?><option value="<?=e($lang)?>"><?=e(strtoupper($lang))?></option><?php endforeach;?></select></label><button class="btn secondary"><?=e(t('action.create_invoice_draft'))?></button></form><?php endif;?>
<?php if(can('deposits.manage')):?><hr><div class="section-card-header"><h2><?=navigationIcon('finance')?><?=e(t('action.request_deposit'))?></h2></div><form method="post"><?=csrfField()?><?=financeIdempotencyField('deposit.create')?><input type="hidden" name="action" value="deposit_create"><label><?=e(t('field.reservation'))?><select name="reservation_id"><?php foreach($reservations as$r):?><option value="<?=e($r['id'])?>"><?=e($r['reference'])?></option><?php endforeach;?></select></label><label><?=e(t('field.amount'))?><input name="amount" type="number" step="0.01" inputmode="decimal" required></label><label><?=e(t('field.reason'))?><input name="reason" maxlength="255"></label><button class="btn secondary"><?=e(t('action.request_deposit'))?></button></form><?php endif;?></section>
<section class="card"><?php if($canManageFinance):?><div class="section-card-header"><h2><?=navigationIcon('finance')?><?=e(t('section.recent_payments'))?></h2></div><div class="table-wrap"><table><thead><tr><th><?=e(t('field.number'))?></th><th><?=e(t('field.reservation'))?></th><th><?=e(t('field.amount'))?></th><th><?=e(t('field.method'))?></th><th><?=e(t('common.status'))?></th></tr></thead><tbody><?php foreach($payments as$p):?><tr><td><a href="payment_detail.php?id=<?=e($p['id'])?>"><?=isolatedValue($p['payment_number'],'reference-value')?></a></td><td><?=isolatedValue($p['reservation_reference'],'reference-value')?></td><td><?=money($p['amount'],$p['currency'])?></td><td><?=e(t('option.'.$p['method']))?></td><td><?=statusBadge($p['status'])?></td></tr><?php endforeach;?></tbody></table></div><?php if(!$payments)echo emptyState('empty.no_payments');?>
<?php if(can('deposits.manage')):?><div id="deposits" class="section-card-header stacked"><h2><?=navigationIcon('finance')?><?=e(t('section.deposits'))?></h2></div><div class="table-wrap"><table><thead><tr><th><?=e(t('field.reservation'))?></th><th><?=e(t('field.received'))?></th><th><?=e(t('field.retained'))?></th><th><?=e(t('field.returned'))?></th><th><?=e(t('common.status'))?></th></tr></thead><tbody><?php foreach($deposits as$d):?><tr><td><a href="deposit_detail.php?id=<?=e($d['id'])?>"><?=isolatedValue($d['reference'],'reference-value')?></a></td><td><?=money($d['received_amount']??0,$d['currency'])?></td><td><?=money($d['retained_amount'],$d['currency'])?></td><td><?=money($d['returned_amount']??0,$d['currency'])?></td><td><?=statusBadge($d['status'])?></td></tr><?php endforeach;?></tbody></table><?php if(!$deposits)echo emptyState('empty.no_records');?></div><?php endif;?>
<?php else:?><div class="section-card-header"><h2><?=navigationIcon('finance')?><?=e(t('section.payment_access'))?></h2></div><p><?=e(t('message.payment_access'))?></p><?php endif;?></section></div>
<?php backofficeFooter();
