<?php
require_once __DIR__ . '/_layout.php'; requirePermission('vehicle_damages.view');
if(requestMethod()==='POST'&&($_POST['action']??'')==='vehicle_damage_resolve'){
    requireCsrfPost();
    try{
        enforcePermission('vehicle_damages.resolve');$raw=$_POST['damage_id']??null;if(!is_string($raw)||!preg_match('/^[1-9]\d*$/',$raw))throw new InvalidArgumentException(t('validation.vehicle_damage_not_found'));
        vehicleDamageResolve(['damage_id'=>$raw,'reason'=>$_POST['reason']??null,'idempotency_key'=>$_POST['idempotency_key']??null]);
        flash('success',t('message.vehicle_damage_resolved'));
    }catch(AuthorizationException){flash('danger',t('validation.not_authorized'));}
    catch(InvalidArgumentException|DomainException$exception){flash('danger',$exception->getMessage());}
    catch(Throwable$exception){error_log('Phase 5C.1 vehicle-damage/controller failure: '.get_class($exception));flash('danger',t('message.vehicle_damage_failed'));}
    safeRedirect('incidents.php');
}
$damageVehicleRaw=$_GET['vehicle_id']??null;try{$damageVehicleFilter=$damageVehicleRaw===null?null:vehicleDamagePositiveId($damageVehicleRaw,'validation.vehicle_damage_not_found');}catch(InvalidArgumentException){http_response_code(404);exit(t('validation.vehicle_damage_not_found'));}$damageRows=vehicleDamageScopedList($damageVehicleFilter);
$ids=currentAgencyIds();if(!$ids)$ids=[0];$ph=implode(',',array_fill(0,count($ids),'?'));$vehicleFilter=(int)($_GET['vehicle_id']??0);if($vehicleFilter&&!dbFetchOne("SELECT id FROM vehicles WHERE id=? AND agency_id IN ($ph) AND archived_at IS NULL",array_merge([$vehicleFilter],$ids)))$vehicleFilter=0;$fineSql="SELECT f.*,v.registration_number,rc.contract_number FROM fines f JOIN vehicles v ON v.id=f.vehicle_id LEFT JOIN rental_contracts rc ON rc.id=f.contract_id WHERE v.agency_id IN ($ph)";$fineParams=$ids;$accidentSql="SELECT a.*,v.registration_number,rc.contract_number FROM accidents a JOIN vehicles v ON v.id=a.vehicle_id LEFT JOIN rental_contracts rc ON rc.id=a.contract_id WHERE v.agency_id IN ($ph)";$accidentParams=$ids;if($vehicleFilter){$fineSql.=' AND f.vehicle_id=?';$fineParams[]=$vehicleFilter;$accidentSql.=' AND a.vehicle_id=?';$accidentParams[]=$vehicleFilter;}$fines=dbFetchAll($fineSql.' ORDER BY f.occurred_at DESC',$fineParams);$accidents=dbFetchAll($accidentSql.' ORDER BY a.occurred_at DESC',$accidentParams);
backofficeHeader(t('nav.incidents'),'incidents.php');?><?php pageHeader('page.incidents.title', 'page.incidents.description', ['breadcrumbs'=>[['label'=>'nav.fleet'],['label'=>'nav.incidents']]]); ?>
<div class="grid"><section class="card full"><div class="section-card-header"><h2><?=navigationIcon('fleet')?><?=e(t('section.vehicle_damage_cases'))?></h2><?php if(can('vehicle_damages.create')):?><?=primaryAction('action.create_vehicle_damage','vehicle_damage_form.php',['class'=>'compact'])?><?php endif;?></div><div class="table-wrap"><table><tr><th><?=e(t('field.date'))?></th><th><?=e(t('field.vehicle'))?></th><th><?=e(t('field.reservation'))?></th><th><?=e(t('field.contract'))?></th><th><?=e(t('field.zone'))?></th><th><?=e(t('field.damage_type'))?></th><th><?=e(t('field.description'))?></th><th><?=e(t('field.severity'))?></th><th><?=e(t('common.status'))?></th><th><?=e(t('field.action'))?></th></tr><?php foreach($damageRows as$damage):?><tr><td><?=formattedDateTime($damage['created_at'])?></td><td><?=isolatedValue($damage['registration_number'],'registration-value')?></td><td><?=isolatedValue($damage['reservation_reference'],'reference-value')?></td><td><?=isolatedValue($damage['contract_number'],'reference-value')?></td><td><?=e($damage['zone'])?></td><td><?=e($damage['damage_type'])?></td><td><?=e($damage['description'])?></td><td><?=e(t('option.'.$damage['severity']))?></td><td><?=statusBadge($damage['status'])?></td><td><?php
    $damageMenuItems = [['label'=>'nav.inspections','href'=>'inspections.php']];
    if ($damage['status']==='open'&&can('vehicle_damages.resolve')) {
        $damageMenuItems[] = ['label'=>'action.resolve_vehicle_damage','drawer'=>'#resolve-damage-'.$damage['id'],'drawer_title'=>'action.resolve_vehicle_damage'];
    }
    echo actionMenu($damageMenuItems);
?><?php if($damage['status']==='open'&&can('vehicle_damages.resolve')):?><template id="resolve-damage-<?=e($damage['id'])?>"><form method="post"><?=csrfField()?><input type="hidden" name="action" value="vehicle_damage_resolve"><input type="hidden" name="damage_id" value="<?=e($damage['id'])?>"><input type="hidden" name="idempotency_key" value="<?=e(contractIdempotencyToken())?>"><label><?=e(t('field.resolution_reason'))?><input name="reason" maxlength="255" required></label><button class="btn secondary" data-confirm="<?=e(t('confirm.resolve_vehicle_damage'))?>"><?=e(t('action.resolve_vehicle_damage'))?></button></form></template><?php endif;?></td></tr><?php endforeach;?></table><?php if(!$damageRows)echo emptyState('empty.no_vehicle_damage_cases');?></div></section></div>
<div class="grid"><section class="card"><div class="section-card-header"><h2><?=navigationIcon('finance')?><?=e(t('section.fines'))?></h2><?=primaryAction('action.record_fine','fine_form.php',['class'=>'compact'])?></div><div class="table-wrap"><table><tr><th><?=e(t('field.date'))?></th><th><?=e(t('field.vehicle'))?></th><th><?=e(t('field.contract'))?></th><th><?=e(t('field.type'))?></th><th><?=e(t('field.amount'))?></th><th><?=e(t('common.status'))?></th></tr><?php foreach($fines as $f):?><tr><td><?=formattedDateTime($f['occurred_at'])?></td><td><bdi><?=e($f['registration_number'])?></bdi></td><td><bdi><?=e($f['contract_number'])?></bdi></td><td><?=e($f['fine_type'])?></td><td><?=money($f['amount']+$f['administrative_fee'])?></td><td><?=statusBadge($f['status'])?></td></tr><?php endforeach;?></table><?php if(!$fines)echo emptyState('empty.no_records');?></div></section><section class="card"><div class="section-card-header"><h2><?=navigationIcon('admin')?><?=e(t('section.accidents_claims'))?></h2><?=primaryAction('action.record_accident','accident_form.php',['class'=>'compact'])?></div><div class="table-wrap"><table><tr><th><?=e(t('field.date'))?></th><th><?=e(t('field.vehicle'))?></th><th><?=e(t('field.contract'))?></th><th><?=e(t('field.location'))?></th><th><?=e(t('field.estimated_cost'))?></th><th><?=e(t('common.status'))?></th></tr><?php foreach($accidents as $a):?><tr><td><?=formattedDateTime($a['occurred_at'])?></td><td><bdi><?=e($a['registration_number'])?></bdi></td><td><bdi><?=e($a['contract_number'])?></bdi></td><td><?=e($a['location'])?></td><td><?=money($a['estimated_cost'])?></td><td><?=statusBadge($a['status'])?></td></tr><?php endforeach;?></table><?php if(!$accidents)echo emptyState('empty.no_records');?></div></section></div><?php backofficeFooter();
