<?php
require_once __DIR__ . '/_layout.php';requirePermission('payments.manage');
$id=filter_input(INPUT_GET,'id',FILTER_VALIDATE_INT,['options'=>['min_range'=>1]])?:0;
[$ids,$ph]=financeScopedPlaceholders(currentAgencyIds());
$payment=dbFetchOne("SELECT p.*,r.reference reservation_reference,c.first_name,c.last_name FROM payments p JOIN reservations r ON r.id=p.reservation_id JOIN customers c ON c.id=r.customer_id WHERE p.id=? AND p.agency_id IN ($ph)",array_merge([$id],$ids));if(!$payment){http_response_code(404);exit(t('validation.finance_not_found'));}
if(requestMethod()==='POST'){requireCsrfPost();try{financeAssertPermission('payments.adjust');appendPaymentAdjustment(['payment_id'=>$id,'adjustment_type'=>$_POST['adjustment_type']??'','amount'=>$_POST['amount']??'','method'=>$_POST['method']??'','reference'=>$_POST['reference']??'','reason'=>$_POST['reason']??'','idempotency_key'=>$_POST['idempotency_key']??'']);flash('success',t('message.payment_adjusted'));}catch(AuthorizationException$e){http_response_code(403);exit(t('validation.not_authorized'));}catch(InvalidArgumentException|DomainException$e){flash('danger',$e->getMessage());}catch(Throwable$e){reportDatabaseError($e,'Payment adjustment failed');flash('danger',t('message.finance_failed'));}safeRedirect('payment_detail.php?id='.$id);}
$adjustments=dbFetchAll('SELECT * FROM payment_adjustments WHERE payment_id=:id ORDER BY occurred_at,id',['id'=>$id]);$adjusted=0;foreach($adjustments as$a)$adjusted+=moneyToCents($a['amount'])??0;$adjustable=max(0,(moneyToCents($payment['amount'])??0)-$adjusted);
backofficeHeader(t('page.payment_detail.title'),'finance.php');pageHeader('page.payment_detail.title','page.payment_detail.description',['breadcrumbs'=>[['label'=>'nav.finance','href'=>'finance.php'],['label'=>$payment['payment_number']]]]);?>
<div class="grid"><section class="card"><div class="section-card-header"><h2><?=navigationIcon('finance')?><?=isolatedValue($payment['payment_number'],'reference-value')?></h2></div><dl class="detail-list"><dt><?=e(t('field.reservation'))?></dt><dd><?=isolatedValue($payment['reservation_reference'],'reference-value')?></dd><dt><?=e(t('field.customer'))?></dt><dd><?=e($payment['first_name'].' '.$payment['last_name'])?></dd><dt><?=e(t('field.amount'))?></dt><dd><?=money($payment['amount'],$payment['currency'])?></dd><dt><?=e(t('field.adjustable'))?></dt><dd><?=money(centsToMoney($adjustable),$payment['currency'])?></dd><dt><?=e(t('field.method'))?></dt><dd><?=e(t('option.'.$payment['method']))?></dd><dt><?=e(t('common.status'))?></dt><dd><?=statusBadge($payment['status'])?></dd></dl><?php if($payment['proof_path']):?><a class="btn secondary" href="financial_document.php?kind=payment_proof&id=<?=e($id)?>"><?=e(t('action.download_proof'))?></a><?php endif;?></section>
<section class="card"><div class="section-card-header"><h2><?=navigationIcon('finance')?><?=e(t('section.payment_adjustments'))?></h2></div><div class="table-wrap"><table><thead><tr><th><?=e(t('field.number'))?></th><th><?=e(t('field.type'))?></th><th><?=e(t('field.amount'))?></th><th><?=e(t('field.reason'))?></th><th><?=e(t('field.date'))?></th></tr></thead><tbody><?php foreach($adjustments as$a):?><tr><td><?=isolatedValue($a['adjustment_number'],'reference-value')?></td><td><?=e(t('adjustment.'.$a['adjustment_type']))?></td><td><?=money($a['amount'],$a['currency'])?></td><td><?=e($a['reason'])?></td><td><?=formattedDateTime($a['occurred_at'])?></td></tr><?php endforeach;?></tbody></table></div><?php if(!$adjustments)echo emptyState('empty.no_adjustments');?></section></div>
<?php if($adjustable>0&&can('payments.adjust')):?><section class="card"><div class="section-card-header"><h2><?=navigationIcon('finance')?><?=e(t('action.adjust_payment'))?></h2></div><form method="post"><?=csrfField()?><?=financeIdempotencyField('payment.adjust')?><label><?=e(t('field.type'))?><select name="adjustment_type"><?php foreach(['partial_refund','full_refund','full_reversal']as$type):?><option value="<?=e($type)?>"><?=e(t('adjustment.'.$type))?></option><?php endforeach;?></select></label><label><?=e(t('field.amount'))?><input name="amount" inputmode="decimal" placeholder="<?=e(centsToMoney($adjustable))?>"></label><label><?=e(t('field.method'))?><select name="method"><?php foreach(financePaymentMethods()as$m):?><option value="<?=e($m)?>" <?=$m===$payment['method']?'selected':''?>><?=e(t('option.'.$m))?></option><?php endforeach;?></select></label><label><?=e(t('field.reference'))?><input name="reference"></label><label><?=e(t('field.reason'))?><input name="reason" required maxlength="255"></label><button class="btn primary"><?=e(t('action.adjust_payment'))?></button></form></section><?php endif;?>
<?php backofficeFooter();
