<?php
require_once __DIR__ . '/_layout.php';
requirePermission('reservations.manage');
$agencyIds=currentAgencyIds();
if(requestMethod()==='POST'){
    requireCsrfPost();$action=$_POST['action']??'';
    try{
        if($action==='create'){
            $agencyId=(int)($_POST['agency_id']??0);requireAgencyAccess($agencyId);$discountInput=(string)($_POST['discount_percent']??'0');$discountPoints=percentageToBasisPoints($discountInput);if($discountPoints===null)throw new InvalidArgumentException(t('validation.discount_percentage'));if($discountPoints>(appConfig('manager_discount_threshold')*100)&&!in_array(currentUserRole(),[ROLE_OWNER,ROLE_AGENCY_MANAGER],true))throw new DomainException(t('validation.discount_authorization'));$discount=centsToMoney($discountPoints);
            $customer=dbFetchOne('SELECT id,status FROM customers WHERE id=:id AND agency_id=:agency AND archived_at IS NULL',['id'=>(int)($_POST['customer_id']??0),'agency'=>$agencyId]);if(!$customer||in_array($customer['status'],['blocked','archived'],true))throw new DomainException(t('validation.eligible_customer'));
            $id=createReservation(['agency_id'=>$agencyId,'return_agency_id'=>(int)($_POST['return_agency_id']??$agencyId),'customer_id'=>$customer['id'],'vehicle_id'=>(int)($_POST['vehicle_id']??0),'status'=>$_POST['status']??'pending','source'=>$_POST['source']??'agency','pickup_at'=>$_POST['pickup_at']??'','return_at'=>$_POST['return_at']??'','pickup_location'=>$_POST['pickup_location']??'','return_location'=>$_POST['return_location']??'','delivery_location'=>$_POST['delivery_location']??'','options_total'=>$_POST['options_total']??0,'fees_total'=>$_POST['fees_total']??0,'discount_percent'=>$discount,'discount_reason'=>$_POST['discount_reason']??'','tax_rate'=>$_POST['tax_rate']??0,'deposit_amount'=>$_POST['deposit_amount']??0,'internal_notes'=>$_POST['internal_notes']??'']);flash('success',t('message.reservation_created',['id'=>$id]));
        }elseif($action==='transition'){
            transitionReservation((int)($_POST['id']??0),(string)($_POST['status']??''),trim((string)($_POST['reason']??'')));flash('success',t('message.reservation_status_updated'));
        }
    }catch(InvalidArgumentException|DomainException $exception){flash('danger',$exception->getMessage());}catch(Throwable $exception){reportDatabaseError($exception,'Reservation operation failed');flash('danger',t('message.reservation_failed'));}safeRedirect('reservations.php');
}
$agencyId=(int)($_GET['agency_id']??($agencyIds[0]??0));requireAgencyAccess($agencyId);$status=trim((string)($_GET['status']??''));$where='r.agency_id=:agency AND r.archived_at IS NULL';$params=['agency'=>$agencyId];if(in_array($status,reservationStatuses(),true)){$where.=' AND r.status=:status';$params['status']=$status;}
$reservations=dbFetchAll("SELECT r.*,c.first_name,c.last_name,v.registration_number,v.brand,v.model FROM reservations r JOIN customers c ON c.id=r.customer_id LEFT JOIN vehicles v ON v.id=r.vehicle_id WHERE $where ORDER BY r.pickup_at DESC LIMIT 100",$params);$agencies=dbFetchAll('SELECT id,name FROM agencies WHERE archived_at IS NULL ORDER BY name');$customers=dbFetchAll("SELECT id,first_name,last_name FROM customers WHERE agency_id=:agency AND status NOT IN ('blocked','archived') AND archived_at IS NULL ORDER BY last_name",['agency'=>$agencyId]);$vehicles=dbFetchAll("SELECT id,registration_number,brand,model,status FROM vehicles WHERE agency_id=:agency AND status NOT IN ('sold','retired','blocked','damaged') AND archived_at IS NULL ORDER BY registration_number",['agency'=>$agencyId]);
$calendar=dbFetchAll("SELECT v.registration_number,v.brand,v.model,r.reference,r.pickup_at,r.return_at,r.status FROM vehicles v LEFT JOIN reservations r ON r.vehicle_id=v.id AND r.status IN ('pending','confirmed','deposit_paid','ready','active') AND r.return_at>=NOW() WHERE v.agency_id=:agency AND v.archived_at IS NULL ORDER BY v.registration_number,r.pickup_at",['agency'=>$agencyId]);
backofficeHeader(t('page.reservations.title'),'reservations.php');?><?php pageHeader('page.reservations.title', 'page.reservations.description', ['breadcrumbs'=>[['label'=>'nav.rentals'],['label'=>'nav.reservations']],'primary'=>['label'=>'common.create','href'=>'#new-reservation'],'secondary'=>['label'=>'section.allocation_editor','href'=>'reservation_edit.php']]); ?><form class="filters"><label><?=e(t('field.agency'))?><select name="agency_id" onchange="this.form.submit()"><?php foreach($agencies as $agency):if(currentUserRole()!==ROLE_OWNER&&!in_array((int)$agency['id'],$agencyIds,true))continue;?><option value="<?=e($agency['id'])?>" <?=$agencyId==(int)$agency['id']?'selected':''?>><?=e($agency['name'])?></option><?php endforeach;?></select></label><label><?=e(t('common.status'))?><select name="status"><option value=""><?=e(t('common.all'))?></option><?php foreach(reservationStatuses() as $item):?><option value="<?=e($item)?>" <?=$status===$item?'selected':''?>><?=e(translatedStatus($item))?></option><?php endforeach;?></select></label><button class="btn secondary"><?=e(t('common.filter'))?></button></form>
<div class="grid"><section class="card" id="new-reservation"><h2><?=e(t('section.create_reservation'))?></h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="create"><input type="hidden" name="agency_id" value="<?=e($agencyId)?>"><div class="grid"><label><?=e(t('field.customer'))?><select name="customer_id" required><?php foreach($customers as $customer):?><option value="<?=e($customer['id'])?>"><?=e($customer['last_name'].' '.$customer['first_name'])?></option><?php endforeach;?></select></label><label><?=e(t('field.vehicle'))?><select name="vehicle_id" required><?php foreach($vehicles as $vehicle):?><option value="<?=e($vehicle['id'])?>"><?=e($vehicle['registration_number'].' — '.$vehicle['brand'].' '.$vehicle['model'].' ('.$vehicle['status'].')')?></option><?php endforeach;?></select></label><label><?=e(t('field.initial_status'))?><select name="status"><option value="quote"><?=e(translatedStatus('quote'))?></option><option value="pending" selected><?=e(translatedStatus('pending'))?></option><option value="confirmed"><?=e(translatedStatus('confirmed'))?></option></select></label><label><?=e(t('field.source'))?><select name="source"><?php foreach(['phone','WhatsApp','website','Instagram','Facebook','agency','hotel','partner','marketplace','other'] as $source):?><option value="<?=e($source)?>"><?=e(t('option.'.strtolower($source)))?></option><?php endforeach;?></select></label><label><?=e(t('field.pickup_date_time'))?><input type="datetime-local" name="pickup_at" required></label><label><?=e(t('field.return_date_time'))?><input type="datetime-local" name="return_at" required></label><label><?=e(t('field.pickup_location'))?><input name="pickup_location"></label><label><?=e(t('field.return_location'))?><input name="return_location"></label><label><?=e(t('field.return_agency'))?><select name="return_agency_id"><?php foreach($agencies as $agency):?><option value="<?=e($agency['id'])?>"><?=e($agency['name'])?></option><?php endforeach;?></select></label><label><?=e(t('field.delivery_location'))?><input name="delivery_location"></label><label><?=e(t('field.options_total'))?><input name="options_total" value="0.00" inputmode="decimal"></label><label><?=e(t('field.other_fees'))?><input name="fees_total" value="0.00" inputmode="decimal"></label><label><?=e(t('field.discount_percent'))?><input type="number" name="discount_percent" value="0" min="0" max="100" step="0.01"></label><label><?=e(t('field.discount_reason'))?><input name="discount_reason"></label><label><?=e(t('field.tax_percent'))?><input type="number" name="tax_rate" value="0" min="0" max="100" step="0.01"></label><label><?=e(t('field.deposit'))?><input name="deposit_amount" value="0.00" inputmode="decimal"></label><label class="full"><?=e(t('field.internal_notes'))?><textarea name="internal_notes"></textarea></label></div><p><small><?=e(t('message.authoritative_totals'))?></small></p><button class="btn primary"><?=e(t('common.create'))?></button></form></section>
<section class="card"><h2><?=e(t('section.reservation_register'))?></h2><div class="table-wrap"><table><tr><th><?=e(t('field.reference'))?></th><th><?=e(t('field.customer'))?></th><th><?=e(t('field.vehicle'))?></th><th><?=e(t('field.period'))?></th><th><?=e(t('field.total'))?></th><th><?=e(t('common.status'))?></th><th><?=e(t('field.workflow'))?></th></tr><?php foreach($reservations as $reservation):?><tr><td><bdi><?=e($reservation['reference'])?></bdi></td><td><?=e($reservation['first_name'].' '.$reservation['last_name'])?></td><td><bdi><?=e($reservation['registration_number'])?></bdi></td><td><?=formattedDateTime($reservation['pickup_at'])?><br><?=formattedDateTime($reservation['return_at'])?></td><td><?=money($reservation['total_amount'],$reservation['currency'])?></td><td><?=statusBadge($reservation['status'])?></td><td><?php $next=reservationTransitions()[$reservation['status']]??[];if($next):?><form method="post"><?=csrfField()?><input type="hidden" name="action" value="transition"><input type="hidden" name="id" value="<?=e($reservation['id'])?>"><select name="status"><?php foreach($next as $item):?><option value="<?=e($item)?>"><?=e(translatedStatus($item))?></option><?php endforeach;?></select><input name="reason" placeholder="<?=e(t('field.reason'))?>"><button class="btn secondary"><?=e(t('action.apply'))?></button></form><?php endif;?></td></tr><?php endforeach;?></table><?php if(!$reservations):?><p class="empty"><?=e(t('no_results'))?></p><?php endif;?></div></section></div>
<section class="card" id="availability-planning" style="margin-top:1rem"><h2><?=e(t('section.availability_upcoming'))?></h2><div class="table-wrap"><table><tr><th><?=e(t('field.vehicle'))?></th><th><?=e(t('field.reference'))?></th><th><?=e(t('field.date_from'))?></th><th><?=e(t('field.date_to'))?></th><th><?=e(t('common.status'))?></th></tr><?php foreach($calendar as $row):?><tr><td><?=e($row['registration_number'].' '.$row['brand'].' '.$row['model'])?></td><td><bdi><?=e($row['reference']?:t('common.available'))?></bdi></td><td><?=formattedDateTime($row['pickup_at'])?></td><td><?=formattedDateTime($row['return_at'])?></td><td><?=statusBadge($row['status']?:'available')?></td></tr><?php endforeach;?></table></div></section><?php backofficeFooter();
