<?php
require_once __DIR__ . '/_layout.php';
requirePermission('users.manage');
$allowedRoles=[ROLE_AGENCY_MANAGER,ROLE_RENTAL_AGENT,ROLE_ACCOUNTANT,ROLE_FLEET_AGENT];if(currentUserRole()===ROLE_OWNER)array_unshift($allowedRoles,ROLE_OWNER);
if(requestMethod()==='POST'){
    requireCsrfPost();$action=$_POST['action']??'';
    if($action==='status'&&currentUserRole()!==ROLE_OWNER){
        $targetId=(int)($_POST['id']??0);$scopedIds=currentAgencyIds();
        if(!$scopedIds)throw new DomainException(t('validation.no_agency_assignment'));
        $scopePlaceholders=implode(',',array_fill(0,count($scopedIds),'?'));
        $scopeParameters=array_merge([$targetId],$scopedIds);
        if(!dbFetchOne("SELECT ua.user_id FROM user_agencies ua WHERE ua.user_id=? AND ua.agency_id IN ($scopePlaceholders) LIMIT 1",$scopeParameters))throw new DomainException(t('validation.user_scope'));
    }
    try{
        if($action==='create'){
            $name=trim((string)($_POST['fullname']??''));$email=normalizedEmail($_POST['email']??'');$phone=trim((string)($_POST['phone']??''));$role=validateChoice($_POST['role']??'',$allowedRoles,null);$password=(string)($_POST['password']??'');$agencyIds=array_values(array_unique(array_map('intval',$_POST['agency_ids']??[])));
            if($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||!$role)throw new InvalidArgumentException(t('validation.user_required_fields'));$passwordErrors=passwordValidationErrors($password);if($passwordErrors)throw new InvalidArgumentException(implode(' ',$passwordErrors));if(!$agencyIds&&$role!==ROLE_OWNER)throw new InvalidArgumentException(t('validation.assign_agency'));foreach($agencyIds as $agencyId)requireAgencyAccess($agencyId);
            $id=withTransaction(function()use($name,$email,$phone,$role,$password,$agencyIds){dbExecute('INSERT INTO users(fullname,email,email_normalized,phone,password_hash,role,status,password_changed_at)VALUES(:name,:email,:normalized,:phone,:hash,:role,\'active\',NOW())',['name'=>$name,'email'=>$email,'normalized'=>$email,'phone'=>$phone,'hash'=>password_hash($password,PASSWORD_DEFAULT),'role'=>$role]);$id=(int)db()->lastInsertId();foreach($agencyIds as $index=>$agencyId)dbExecute('INSERT INTO user_agencies(user_id,agency_id,is_primary,created_by)VALUES(:user,:agency,:primary,:creator)',['user'=>$id,'agency'=>$agencyId,'primary'=>$index===0?1:0,'creator'=>currentUserId()]);return $id;});auditLog('user.created','user',$id,null,['email'=>$email,'role'=>$role]);flash('success',t('message.employee_created'));
        }elseif($action==='status'){
            $id=(int)($_POST['id']??0);$status=validateChoice($_POST['status']??'',['active','inactive'],null);$user=dbFetchOne('SELECT * FROM users WHERE id=:id',['id'=>$id]);if(!$user||!$status)throw new InvalidArgumentException(t('validation.invalid_user_status'));if($user['role']===ROLE_OWNER&&currentUserRole()!==ROLE_OWNER)throw new DomainException(t('validation.owner_change'));if($id===currentUserId()&&$status==='inactive')throw new DomainException(t('validation.self_deactivation'));dbExecute('UPDATE users SET status=:status,sessions_invalid_before=IF(:status2=\'inactive\',NOW(),sessions_invalid_before) WHERE id=:id',['status'=>$status,'status2'=>$status,'id'=>$id]);auditLog('user.status_changed','user',$id,['status'=>$user['status']],['status'=>$status]);flash('success',t('message.user_status_updated'));
        }
    }catch(InvalidArgumentException|DomainException $exception){flash('danger',$exception->getMessage());}catch(Throwable $exception){reportDatabaseError($exception,'User management failed');flash('danger',t('message.user_failed'));}safeRedirect('users.php');
}
$scopedIds=currentAgencyIds();
if(currentUserRole()===ROLE_OWNER){$users=dbFetchAll('SELECT u.*,GROUP_CONCAT(a.name ORDER BY a.name SEPARATOR ", ") agency_names FROM users u LEFT JOIN user_agencies ua ON ua.user_id=u.id LEFT JOIN agencies a ON a.id=ua.agency_id WHERE u.archived_at IS NULL GROUP BY u.id ORDER BY u.fullname');}
else{$scopePlaceholders=implode(',',array_fill(0,count($scopedIds),'?'));$users=$scopedIds?dbFetchAll("SELECT u.*,GROUP_CONCAT(DISTINCT a.name ORDER BY a.name SEPARATOR ', ') agency_names FROM users u JOIN user_agencies access_scope ON access_scope.user_id=u.id AND access_scope.agency_id IN ($scopePlaceholders) LEFT JOIN user_agencies ua ON ua.user_id=u.id LEFT JOIN agencies a ON a.id=ua.agency_id WHERE u.archived_at IS NULL GROUP BY u.id ORDER BY u.fullname",$scopedIds):[];}
$agencies=dbFetchAll('SELECT id,name FROM agencies WHERE archived_at IS NULL ORDER BY name');
backofficeHeader(t('page.users.title'),'users.php');?><?php pageHeader('page.users.title', 'page.users.description', ['breadcrumbs'=>[['label'=>'nav.administration'],['label'=>'nav.users']],'primary'=>['label'=>'action.add_user','href'=>'#new-user']]); ?><div class="grid"><section class="card" id="new-user"><h2><?=e(t('section.new_employee'))?></h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="create"><label><?=e(t('field.full_name'))?><input name="fullname" required></label><label><?=e(t('field.email'))?><input type="email" name="email" required></label><label><?=e(t('field.phone'))?><input name="phone"></label><label><?=e(t('field.role'))?><select name="role"><?php foreach($allowedRoles as $role):?><option value="<?=e($role)?>"><?=e(translatedRole($role))?></option><?php endforeach;?></select></label><fieldset><legend><?=e(t('field.assigned_agencies'))?></legend><?php foreach($agencies as $agency):if(currentUserRole()!==ROLE_OWNER&&!in_array((int)$agency['id'],currentAgencyIds(),true))continue;?><label style="display:flex"><input style="width:auto" type="checkbox" name="agency_ids[]" value="<?=e($agency['id'])?>"> <?=e($agency['name'])?></label><?php endforeach;?></fieldset><label><?=e(t('field.temporary_password'))?><input type="password" name="password" required autocomplete="new-password"></label><small><?=e(t('message.password_policy'))?></small><br><button class="btn primary"><?=e(t('action.add_user'))?></button></form></section><section class="card"><h2><?=e(t('section.users'))?></h2><div class="table-wrap"><table><tr><th><?=e(t('field.name'))?></th><th><?=e(t('field.role'))?></th><th><?=e(t('nav.agencies'))?></th><th><?=e(t('common.status'))?></th><th><?=e(t('field.last_login'))?></th></tr><?php foreach($users as $user):?><tr><td><?=e($user['fullname'])?><br><small><?=isolatedValue($user['email'],'email-value')?></small></td><td><?=roleBadge($user['role'])?></td><td><?=e($user['agency_names'])?></td><td><form method="post"><?=csrfField()?><input type="hidden" name="action" value="status"><input type="hidden" name="id" value="<?=e($user['id'])?>"><select name="status" onchange="this.form.submit()"><?php foreach(['active','inactive'] as $status):?><option value="<?=e($status)?>" <?=$user['status']===$status?'selected':''?>><?=e(translatedStatus($status))?></option><?php endforeach;?></select></form></td><td><?=formattedDateTime($user['last_login_at'])?></td></tr><?php endforeach;?></table></div></section></div><?php backofficeFooter();
