<?php
require_once __DIR__ . '/_layout.php';
requirePermission('users.manage');
$allowedRoles=[ROLE_AGENCY_MANAGER,ROLE_RENTAL_AGENT,ROLE_ACCOUNTANT,ROLE_FLEET_AGENT];if(currentUserRole()===ROLE_OWNER)array_unshift($allowedRoles,ROLE_OWNER);
if(requestMethod()==='POST'){
    requireCsrfPost();$action=$_POST['action']??'';
    if($action==='status'&&currentUserRole()!==ROLE_OWNER){
        $targetId=(int)($_POST['id']??0);$scopedIds=currentAgencyIds();
        if(!$scopedIds)throw new DomainException('No agency assignment is available.');
        $scopePlaceholders=implode(',',array_fill(0,count($scopedIds),'?'));
        $scopeParameters=array_merge([$targetId],$scopedIds);
        if(!dbFetchOne("SELECT ua.user_id FROM user_agencies ua WHERE ua.user_id=? AND ua.agency_id IN ($scopePlaceholders) LIMIT 1",$scopeParameters))throw new DomainException('You cannot manage a user outside your assigned agencies.');
    }
    try{
        if($action==='create'){
            $name=trim((string)($_POST['fullname']??''));$email=normalizedEmail($_POST['email']??'');$phone=trim((string)($_POST['phone']??''));$role=validateChoice($_POST['role']??'',$allowedRoles,null);$password=(string)($_POST['password']??'');$agencyIds=array_values(array_unique(array_map('intval',$_POST['agency_ids']??[])));
            if($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||!$role)throw new InvalidArgumentException('Name, valid email, and role are required.');$passwordErrors=passwordValidationErrors($password);if($passwordErrors)throw new InvalidArgumentException(implode(' ',$passwordErrors));if(!$agencyIds&&$role!==ROLE_OWNER)throw new InvalidArgumentException('Assign at least one agency.');foreach($agencyIds as $agencyId)requireAgencyAccess($agencyId);
            $id=withTransaction(function()use($name,$email,$phone,$role,$password,$agencyIds){dbExecute('INSERT INTO users(fullname,email,email_normalized,phone,password_hash,role,status,password_changed_at)VALUES(:name,:email,:normalized,:phone,:hash,:role,\'active\',NOW())',['name'=>$name,'email'=>$email,'normalized'=>$email,'phone'=>$phone,'hash'=>password_hash($password,PASSWORD_DEFAULT),'role'=>$role]);$id=(int)db()->lastInsertId();foreach($agencyIds as $index=>$agencyId)dbExecute('INSERT INTO user_agencies(user_id,agency_id,is_primary,created_by)VALUES(:user,:agency,:primary,:creator)',['user'=>$id,'agency'=>$agencyId,'primary'=>$index===0?1:0,'creator'=>currentUserId()]);return $id;});auditLog('user.created','user',$id,null,['email'=>$email,'role'=>$role]);flash('success','Employee account created.');
        }elseif($action==='status'){
            $id=(int)($_POST['id']??0);$status=validateChoice($_POST['status']??'',['active','inactive'],null);$user=dbFetchOne('SELECT * FROM users WHERE id=:id',['id'=>$id]);if(!$user||!$status)throw new InvalidArgumentException('Invalid user or status.');if($user['role']===ROLE_OWNER&&currentUserRole()!==ROLE_OWNER)throw new DomainException('Only an owner can change another owner account.');if($id===currentUserId()&&$status==='inactive')throw new DomainException('You cannot deactivate your own account.');dbExecute('UPDATE users SET status=:status,sessions_invalid_before=IF(:status2=\'inactive\',NOW(),sessions_invalid_before) WHERE id=:id',['status'=>$status,'status2'=>$status,'id'=>$id]);auditLog('user.status_changed','user',$id,['status'=>$user['status']],['status'=>$status]);flash('success','User status updated.');
        }
    }catch(InvalidArgumentException|DomainException $exception){flash('danger',$exception->getMessage());}catch(Throwable $exception){reportDatabaseError($exception,'User management failed');flash('danger','The user operation could not be completed.');}safeRedirect('users.php');
}
$scopedIds=currentAgencyIds();
if(currentUserRole()===ROLE_OWNER){$users=dbFetchAll('SELECT u.*,GROUP_CONCAT(a.name ORDER BY a.name SEPARATOR ", ") agency_names FROM users u LEFT JOIN user_agencies ua ON ua.user_id=u.id LEFT JOIN agencies a ON a.id=ua.agency_id WHERE u.archived_at IS NULL GROUP BY u.id ORDER BY u.fullname');}
else{$scopePlaceholders=implode(',',array_fill(0,count($scopedIds),'?'));$users=$scopedIds?dbFetchAll("SELECT u.*,GROUP_CONCAT(DISTINCT a.name ORDER BY a.name SEPARATOR ', ') agency_names FROM users u JOIN user_agencies access_scope ON access_scope.user_id=u.id AND access_scope.agency_id IN ($scopePlaceholders) LEFT JOIN user_agencies ua ON ua.user_id=u.id LEFT JOIN agencies a ON a.id=ua.agency_id WHERE u.archived_at IS NULL GROUP BY u.id ORDER BY u.fullname",$scopedIds):[];}
$agencies=dbFetchAll('SELECT id,name FROM agencies WHERE archived_at IS NULL ORDER BY name');
backofficeHeader('Users','users.php');?><?php pageHeader('Employees and roles', 'Manage staff access, agency assignments, and account status.', ['breadcrumbs'=>[['label'=>'Administration'],['label'=>'Users']],'primary'=>['label'=>'Add user','href'=>'#new-user']]); ?><div class="grid"><section class="card" id="new-user"><h2>New employee</h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="create"><label>Full name<input name="fullname" required></label><label>Email<input type="email" name="email" required></label><label>Phone<input name="phone"></label><label>Role<select name="role"><?php foreach($allowedRoles as $role):?><option value="<?=e($role)?>"><?=e($role)?></option><?php endforeach;?></select></label><fieldset><legend>Assigned agencies</legend><?php foreach($agencies as $agency):if(currentUserRole()!==ROLE_OWNER&&!in_array((int)$agency['id'],currentAgencyIds(),true))continue;?><label style="display:flex"><input style="width:auto" type="checkbox" name="agency_ids[]" value="<?=e($agency['id'])?>"> <?=e($agency['name'])?></label><?php endforeach;?></fieldset><label>Temporary password<input type="password" name="password" required autocomplete="new-password"></label><small>At least 12 characters with upper/lowercase, a number, and a symbol.</small><br><button class="btn primary">Create user</button></form></section><section class="card"><h2>Users</h2><div class="table-wrap"><table><tr><th>Name</th><th>Role</th><th>Agencies</th><th>Status</th><th>Last login</th></tr><?php foreach($users as $user):?><tr><td><?=e($user['fullname'])?><br><small><?=e($user['email'])?></small></td><td><?=roleBadge($user['role'])?></td><td><?=e($user['agency_names'])?></td><td><form method="post"><?=csrfField()?><input type="hidden" name="action" value="status"><input type="hidden" name="id" value="<?=e($user['id'])?>"><select name="status" onchange="this.form.submit()"><option <?=$user['status']==='active'?'selected':''?>>active</option><option <?=$user['status']==='inactive'?'selected':''?>>inactive</option></select></form></td><td><?=e($user['last_login_at'])?></td></tr><?php endforeach;?></table></div></section></div><?php backofficeFooter();
