<?php
require_once __DIR__ . '/../app/application.php';
require_once __DIR__ . '/../backoffice/_components.php';
requireAuthentication('../account/login.php');
if(currentUserRole()!==ROLE_CUSTOMER)safeRedirect('../backoffice/');
$customer=dbFetchOne('SELECT * FROM customers WHERE user_id=:user AND archived_at IS NULL',['user'=>currentUserId()]);
if(!$customer){http_response_code(403);exit('Customer profile not found.');}
if(isset($_GET['lang'])&&in_array($_GET['lang'],supportedLanguages(),true))$_SESSION['lang']=$_GET['lang'];
if(requestMethod()==='POST'){
    requireCsrfPost();$action=$_POST['action']??'';
    try{
        if($action==='profile'){
            dbExecute('UPDATE customers SET address=:address,phone=:phone_raw,phone_normalized=:phone,whatsapp=:whatsapp,updated_by=NULL WHERE id=:id',['address'=>trim((string)($_POST['address']??'')),'phone_raw'=>trim((string)($_POST['phone']??'')),'phone'=>normalizedPhone($_POST['phone']??''),'whatsapp'=>trim((string)($_POST['whatsapp']??'')),'id'=>$customer['id']]);
            auditLog('customer.profile_updated','customer',$customer['id']);flash('success','Profile updated.');
        }elseif($action==='document'){
            $stored=storeValidatedDocument($_FILES['document'],'customer_documents');
            dbExecute('INSERT INTO customer_documents(customer_id,document_type,document_number,issued_at,expires_at,storage_path,original_name,mime_type,file_size) VALUES(:customer,:type,:number,:issued,:expires,:path,:original,:mime,:size)',['customer'=>$customer['id'],'type'=>validateChoice($_POST['document_type']??'',['identity','passport','driving_licence','company','other'],'other'),'number'=>trim((string)($_POST['document_number']??'')),'issued'=>($_POST['issued_at']??'')?:null,'expires'=>($_POST['expires_at']??'')?:null,'path'=>$stored['path'],'original'=>$stored['original_name'],'mime'=>$stored['mime_type'],'size'=>$stored['size']]);
            auditLog('customer.document_uploaded','customer_document',db()->lastInsertId(),null,['customer_id'=>$customer['id']],$customer['agency_id']);flash('success','Document uploaded securely.');
        }elseif(in_array($action,['cancellation_request','modification_request','booking_request'],true)){
            $reservationId=($_POST['reservation_id']??'')?:null;if($reservationId&&!dbFetchOne('SELECT id FROM reservations WHERE id=:id AND customer_id=:customer',['id'=>$reservationId,'customer'=>$customer['id']]))throw new DomainException('Reservation not found.');
            $message=trim((string)($_POST['message']??''));if($message==='')throw new InvalidArgumentException('A request message is required.');
            dbExecute("INSERT INTO customer_requests(customer_id,reservation_id,request_type,message,status) VALUES(:customer,:reservation,:type,:message,'pending')",['customer'=>$customer['id'],'reservation'=>$reservationId,'type'=>$action,'message'=>$message]);
            auditLog('customer.request_created','customer_request',db()->lastInsertId(),null,['type'=>$action],$customer['agency_id']);flash('success','Your request was submitted to the agency.');
        }
    }catch(InvalidArgumentException|DomainException$e){flash('danger',$e->getMessage());}
    catch(Throwable$e){reportDatabaseError($e,'Portal operation failed');flash('danger','The request could not be completed.');}
    safeRedirect('index.php');
}
$pickup=validDateTimeValue($_GET['pickup_at']??'');$return=validDateTimeValue($_GET['return_at']??'');$available=[];
if($pickup&&$return&&$return>$pickup){$candidates=dbFetchAll("SELECT v.*,vc.name category_name FROM vehicles v JOIN vehicle_categories vc ON vc.id=v.category_id WHERE v.agency_id=:agency AND v.status='available' AND v.archived_at IS NULL",['agency'=>$customer['agency_id']]);foreach($candidates as$v)if(!vehicleHasConflict($v['id'],$pickup,$return))$available[]=$v;}
$reservations=dbFetchAll("SELECT r.*,v.registration_number,v.brand,v.model,rc.id contract_id FROM reservations r LEFT JOIN vehicles v ON v.id=r.vehicle_id LEFT JOIN rental_contracts rc ON rc.reservation_id=r.id AND rc.status<>'cancelled' WHERE r.customer_id=:customer ORDER BY r.created_at DESC",['customer'=>$customer['id']]);
$documents=dbFetchAll('SELECT * FROM customer_documents WHERE customer_id=:customer AND archived_at IS NULL ORDER BY expires_at',['customer'=>$customer['id']]);$flashes=consumeFlashes();
?>
<!doctype html><html lang="<?=e(language())?>" dir="<?=language()==='ar'?'rtl':'ltr'?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Customer portal</title><link rel="icon" href="../backoffice/assets/img/aurevo-mark.png"><link rel="stylesheet" href="../backoffice/assets/app.css?v=<?= e(assetVersion('backoffice/assets/app.css')) ?>"></head><body>
<header class="topbar"><strong><?=e(appConfig('name'))?> — Customer portal</strong><div><a href="?lang=en">EN</a> · <a href="?lang=fr">FR</a> · <a href="?lang=ar">AR</a> <form action="../account/logout.php" method="post" style="display:inline"><?=csrfField()?><button class="btn secondary">Sign out</button></form></div></header>
<main class="page"><?php foreach($flashes as$type=>$messages):foreach($messages as$message):?><div class="alert <?=e($type)?>"><?=e($message)?></div><?php endforeach;endforeach;?><div class="page-head"><h1>Welcome, <?=e($customer['first_name'])?></h1><a href="../<?=e(language())?>/">Public website</a></div>
<div class="grid"><section class="card"><h2>Search available vehicles</h2><form method="get"><label>Pickup<input type="datetime-local" name="pickup_at" value="<?=e($_GET['pickup_at']??'')?>" required></label><label>Return<input type="datetime-local" name="return_at" value="<?=e($_GET['return_at']??'')?>" required></label><button class="btn primary">Check availability</button></form><?php foreach($available as$v):?><article class="card"><strong><?=e($v['brand'].' '.$v['model'])?></strong><br><?=e($v['category_name'])?> · <?=money($v['base_daily_price'])?>/day<form method="post"><?=csrfField()?><input type="hidden" name="action" value="booking_request"><textarea name="message" required><?=e('Vehicle '.$v['registration_number'].' from '.($_GET['pickup_at']??'').' to '.($_GET['return_at']??''))?></textarea><button class="btn primary">Request booking</button></form></article><?php endforeach;?></section>
<section class="card"><h2>Profile</h2><form method="post"><?=csrfField()?><input type="hidden" name="action" value="profile"><label>Name<input value="<?=e($customer['first_name'].' '.$customer['last_name'])?>" disabled></label><label>Email<input value="<?=e($customer['email'])?>" disabled></label><label>Phone<input name="phone" value="<?=e($customer['phone'])?>"></label><label>WhatsApp<input name="whatsapp" value="<?=e($customer['whatsapp'])?>"></label><label>Address<input name="address" value="<?=e($customer['address'])?>"></label><button class="btn primary">Update profile</button></form><h2>Upload document</h2><form method="post" enctype="multipart/form-data"><?=csrfField()?><input type="hidden" name="action" value="document"><label>Type<select name="document_type"><option>identity</option><option>passport</option><option>driving_licence</option><option>company</option><option>other</option></select></label><label>Number<input name="document_number"></label><label>Expiry<input type="date" name="expires_at"></label><label>PDF or image<input type="file" name="document" required accept="application/pdf,image/jpeg,image/png,image/webp"></label><button class="btn secondary">Upload</button></form></section></div>
<section class="card" style="margin-top:1rem"><h2>Booking history</h2><div class="table-wrap"><table><tr><th>Reference</th><th>Vehicle</th><th>Period</th><th>Total</th><th>Status</th><th>Requests / documents</th></tr><?php foreach($reservations as$r):?><tr><td><?=e($r['reference'])?></td><td><?=e($r['brand'].' '.$r['model'])?></td><td><?=e($r['pickup_at'])?><br><?=e($r['return_at'])?></td><td><?=money($r['total_amount'],$r['currency'])?></td><td><?=statusBadge($r['status'])?></td><td><?php if($r['contract_id']):?><a class="btn secondary" href="contract.php?id=<?=e($r['contract_id'])?>">Contract</a><?php endif;?><form method="post"><?=csrfField()?><input type="hidden" name="action" value="modification_request"><input type="hidden" name="reservation_id" value="<?=e($r['id'])?>"><input name="message" placeholder="Requested change" required><button class="btn secondary">Request change</button></form><form method="post"><?=csrfField()?><input type="hidden" name="action" value="cancellation_request"><input type="hidden" name="reservation_id" value="<?=e($r['id'])?>"><input name="message" placeholder="Cancellation reason" required><button class="btn danger">Request cancellation</button></form></td></tr><?php endforeach;?></table></div></section>
<section class="card" style="margin-top:1rem"><h2>Documents</h2><div class="table-wrap"><table><tr><th>Type</th><th>Number</th><th>Expires</th><th>Uploaded</th><th>Download</th></tr><?php foreach($documents as$d):?><tr><td><?=e($d['document_type'])?></td><td><?=e($d['document_number'])?></td><td><?=e($d['expires_at'])?></td><td><?=e($d['created_at'])?></td><td><a class="btn secondary" href="customer_document.php?id=<?=e($d['id'])?>">Download</a></td></tr><?php endforeach;?></table></div></section></main></body></html>
